C++ headers Integrity check - follows #10065
dlang/dmd pull request #10071
Opened 2019-06-21 19:01 UTC by SSoulaimane

2019-06-21 19:05 UTC, jacob-carlborg approved these changes

2019-06-22 04:12 UTC, ibuclaw requested changes

2019-06-22 04:12 UTC, ibuclaw commented on src/tests/cxxfrontend.c
> +    Dsymbol *s = m->search(loc, Identifier::idPool("Error"));
You should be able to use `Loc()` here.

2019-06-22 04:12 UTC, ibuclaw commented on src/tests/cxxfrontend.c
> +    assert(ad->ctor);
ad && ad->ctor

2019-06-22 04:12 UTC, ibuclaw commented on src/tests/cxxfrontend.c
> +    assert(0 == strcmp(ctor->type->toChars(), "Error(string)"));
Maybe also:
assert(ctor->isMember() && !ctor->is Nested());

To test a couple more virtuals at random intervals in the vtable.

2019-06-22 17:13 UTC, SSoulaimane commented
I also added two missing virtual function declarations to make the added tests succeed.

2019-06-26 15:42 UTC, ibuclaw approved these changes
OK

2019-06-26 15:44 UTC, ibuclaw commented
> I also added two missing virtual function declarations to make the added tests succeed.

Good to see it caught more problems. :-)

2019-06-26 16:46 UTC, merged