[stable] test/runnable/testargtypes.d: Don't test (debugging aid) output
dlang/dmd pull request #10104
Opened 2019-06-27 21:30 UTC by kinke

Testing isn't required, as the code checks correctness. The output is just an additional debugging aid; additionally, there are multiple DMD special cases, so the output is compiler-specific.

2019-06-27 23:57 UTC, JinShil approved these changes

2019-06-28 02:15 UTC, Geod24 requested changes
I think @ibuclaw 's point, which made sense to me, was to prevent test output randomly changing.
If you want to remove this output, I would suggest to keep the `TEST_OUTPUT` empty and actually remove the code that outputs.
One of the problem we see is that deprecations that triggers on tests without `TEST_OUTPUT` aren't caught.

2019-06-28 09:28 UTC, kinke commented
The output makes sense in the event of failures, as the same function is used > 50 times, so an AssertError from some line isn't worth anything.

> One of the problem we see is that deprecations that triggers on tests without TEST_OUTPUT aren't caught.

Then let's use `-de` as default flag for these tests.

2019-06-28 09:56 UTC, Geod24 commented
> The output makes sense in the event of failures, as the same function is used > 50 times, so an AssertError from some line isn't worth anything.

You have the "instantiated from" message so it isn't really an issue, is it ?

> Then let's use `-de` as default flag for these tests.

My use case would be satisfied with `-de`. From what I could trace from https://github.com/dlang/dmd/pull/9241 @ibuclaw also wanted to make lack of `TEST_OUTPUT` means empty `TEST_OUTPUT` due to a previous DDOC regression.

Anyway, I think removing the `pragma` along with the test is the path of least resistance here.

2019-06-28 16:36 UTC, kinke commented
> You have the "instantiated from" message so it isn't really an issue, is it ?

Ah yeah, static assert.

2019-06-28 17:53 UTC, Geod24 approved these changes

2019-06-28 19:51 UTC, ibuclaw commented
> I think @ibuclaw 's point, which made sense to me, was to prevent test output randomly changing.

Well the testsuite tool I use, all output from the compiler that is not explicitly recorded as being expect is treated as a failure.

In the best case, all compilable and runnable tests should be silent.

2019-06-29 03:39 UTC, merged