add restrictiveshared preview flags (hidden).
dlang/dmd pull request #10117
Opened 2019-07-01 06:58 UTC by thewilsonator

This is currently hidden because it currently induces no change. It serves to section off changes related to shared and thread safety.

2019-07-01 09:35 UTC, wilzbach requested changes
Can't we add the flag when there is an actual PR for it?

2019-07-01 21:43 UTC, WalterBright commented
We've never been calling it restrictive shared, more like atomic shared.

2019-07-01 21:43 UTC, WalterBright requested changes
I'd call it atomicshared or just atomic.

2019-07-01 21:45 UTC, WalterBright commented
> Can't we add the flag when there is an actual PR for it?

There'll be likely several PRs for it, as one big one will be too big to review. Progress is currently stalled by nobody willing to look at https://github.com/dlang/dmd/pull/10097

At this rate, it'll never happen :-(

2019-07-02 00:21 UTC, thewilsonator commented
> We've never been calling it restrictive shared, more like atomic shared.

_You've_ not been calling it restrictive. Possibly because the plan you have is not the plan the rest of the community has which has little to do with atomics other than as a basic building block (although it was noted that `core.atomic` is missing the weak forms of [cmpxchg](https://en.cppreference.com/w/cpp/atomic/atomic/compare_exchange) which we may or may not need to add, I'm not an atomic expert). 

I don't really care what the preview flag is called provided it is clearly about shared, I didn't go with "shared", because we already have `shared` (and this flag is under `-preview=`) its just completely useless, but I suppose thats fine too. 

"newshared", "nothorriblybrokenshared" are all fine with me, but I went with "restrictiveshared" because shared will become more restrictive (as in less operations are allowed on it). 

You can paint the bikeshed any colour you like, so long as its "shared".

2019-07-02 00:29 UTC, thewilsonator commented
> There'll be likely several PRs for it,

Definitely.

> as one big one will be too big to review. 

It'll be a miracle if one PR manages to get the semantics correct in one shot irrespective of its size or difficulty to review.

> Progress is currently stalled by nobody willing to look at #10097

Thats a backend PR, practically no-one is qualified to review those.  Also, thats for what you want to do. What the rest of us are doing is not thus handicapped.

> At this rate, it'll never happen :-(

Oh, it will. Just not necessarily what you had in mind.

2019-07-02 01:41 UTC, TurkeyMan commented
> I'd call it atomicshared or just atomic.

shared and atomic intrinsics are not related tasks.

2019-07-05 14:41 UTC, UplinkCoder commented
I need this compiler switch, can we please merge it?

2019-07-06 21:48 UTC, UplinkCoder commented
@WalterBright https://github.com/dlang/dmd/pull/10142 could a remove the static if, if this is merged.

2019-07-18 02:28 UTC, thewilsonator commented
Superseded by #10142

2019-07-18 02:28 UTC, closed without merging