Remove unused variables & enable dscanner check
dlang/dmd pull request #10170
Opened 2019-07-13 09:44 UTC by Geod24

2019-07-13 11:10 UTC, Geod24 commented
Hum, I forgot this is actually far from the full set of unused variables. The dscanner check matches tons of unused variables and parameter, so removed it, but for the moment this is already an improvement that can be reviewed.

2019-07-13 12:36 UTC, thewilsonator approved these changes

2019-07-14 06:16 UTC, PetarKirov approved these changes

2019-07-14 06:23 UTC, ZombineDev commented
testpdb fails both on the auto tester and Azure Pipelines, though I don't see why this should be caused by any of the changes in this PR.

2019-07-14 06:36 UTC, rainers commented on src/dmd/tocvdebug.d
> -    const uint len = len1 + cv_namestring(d.data.ptr + len1,id);
The call to cv_namestring must not be removed, it is copying the name.

2019-07-14 06:37 UTC, rainers requested changes

2019-07-14 06:37 UTC, rainers commented on src/dmd/tocvdebug.d
> -    const uint len = len1 + cv_namestring(d.data.ptr + len1,id);
same here.

2019-07-14 09:09 UTC, Geod24 commented
Thanks for the pointers @rainers . Fixed.

2019-07-14 09:28 UTC, rainers approved these changes

2019-07-14 14:37 UTC, merged