Support @noobject on module decalaration
dlang/dmd pull request #10188
Opened 2019-07-16 20:07 UTC by marler8997

An alternative to https://github.com/dlang/dmd/pull/10184

This PR allows modules to specify the `@noobject` attribute on their module declartion to disable importing the implicit object module, i.e.
```
@noobject module foo;

// the object.d module will not be imported because @noobject was specified on the module declaration
```

2019-07-16 22:50 UTC, ErnyTech commented
What happens if I have multiple files?  
Need to add @noobject in each one?

2019-07-16 22:52 UTC, marler8997 commented
Yeah. You add it to the files that you don't want to use `object.d`.

2019-07-16 23:46 UTC, JinShil commented
Despite being a beneficiary of such a feature, I don't think this is the best approach because it is much too specialized.  I would prefer we aim for more general-purpose, composable features.

If I could have my druthers I would require users to explicitly `import object;` (or rename `object.d` to `package.d` and `import druntime;`).  However, I that would be too radical, and my other attempts to help make the compiler more pay-as-you-go w.r.t. `object.d` have not been well-received (https://github.com/dlang/dmd/pull/7825, https://github.com/dlang/dmd/pull/9814).

My suggestion, given the history of previous attempts, is to add the ability to implicity import from the compiler command-line.  We already have the `-i=-foo` switch that allows us to exclude implicity importing certain modules.  Maybe we can exapand that with a `+` operator so users can implicitly import modules from the command line with `-i=+foo`.  Then we can add `-i=+object` to the `dmd.conf` file and remove the hard-coded logic in the compiler to implicitly import `object.d`.  If that abuses the intent of the `-i` switch, let's make a new one (e.g. `-implicitlyImport=object`).

Such a feature will resolve the issue at hand (having to create phony source files just to get a build), will remove some hard-coded logic from the compiler (which should be aiming for anyway), and will be more generally useful to everyone.  Also, it makes the compiler more "additive" (for lack of a better word); instead turning things OFF, we only need to turn things ON, which is more in the spirit of "pay-as-you-go".  If one wants something ON by default, they can add it to the `dmd.conf` file.

A couple of other use cases:

**Implicity importing runtime compiler assets**
We're currently converting many runtime hooks to templates that need to be publicly imported into `object.d` because it is the only tool we have at our disposal to accomplish this task:
https://github.com/dlang/druntime/blob/7d962321244ae1cb03a6c9f25ff85ece83f28277/src/object.d#L41-L63

This is somewhat unfortunate because `object.d` is a publicly documented module, and none of the `_d_xxx` should be explicitly employed by the user, but there they are, font-and-center, in the only place they can be at the moment.  If we had a way to tell the compiler to implicitly import certain modules, we can hide these symbols in a dark corner of the runtime and implicitly import them in `dmd.conf`.

**Specialized builds**
Users may also find the feature useful when doing specialized builds.  For example, importing an instrumentation framework into all files *only* for a debug build, or importing specialized platform assets when building the same software for different platforms.  Yes, there are other ways to do this in D, but this option may be preferrable over existing methods that could easily turn into `version`-hell.

2019-07-16 23:59 UTC, marler8997 commented
The `-i` option does not change what modules are imported, it only changes what modules are "included" in compilation.  Specifying `-i=-foo` does not mean the `foo` module will not be imported, it means it won't be compiled to object code.

The module itself is the sole owner and maintainer of it's imports.  Whether or not a module imports the `object` module is fundamental to the module itself, changing it would require a refactor of the module in question.  It's not something you can enable/disable from the command-line and have both versions work.  This makes the flag meaningless since the module will only compile one variant, either with or without it, meaning it's not really a command-line option is it?  It's really a part of the module definition, not a command-line option.

2019-07-17 00:16 UTC, JinShil commented
@marler8997 I don't disagree with anything you've said.  But the fundamental problem is that the compiler is implicitly importing `object.d` when it shouldn't be implicitly importing anything.  As you said the module is the sole owner and maintainer of its imports, so only the module should specify that it wants to import `object.d`.

Since we agree that the module is the sole owner of its imports and the compiler is partially assuming ownership of the module's imports, it would be prudent to return the compiler to a more fundamentally correct state by turning off the implicit import of `object.d`.   Unfortunately, that is not a practical option, so we are left with the next best thing which is a configuration option for the compiler to return it to a more fundamentally correct state.

2019-07-17 01:06 UTC, marler8997 commented
I can't say for sure but it may have been better for `object.d` to have been explicitly imported.  Of course like you say it's probably too late to change that.  But I don't see it as a big problem either way.

I've read #9814 and I lean towards agreeing with @andralex comment in saying that we should focus us making `object.d` pay-for-what-you-use rather than trying to provide extra features to mitigate our inability to do so within the language with the current implementation. The D Language should be all we need to implement a pay-for-what-you-use runtime.

Let me supplement this by clarifying a bit about how I see the `object` module.  The fundamental reason that `object.d` is needed right now is because the compiler defers some of its code generation to it.  So, rather than generating the AST inside the compiler for some of its code, like other compilers would do, it just generates references to symbols within `object.d` and puts the implementation in there.  However, this primary reason for why `object.d` is necessary gets conflated since `object.d` also contains alot of code that isn't referenced by code intrinsically generated by the compiler.

So in my mind, any code that could be referenced by compiler-generated code should always be imported/available in every module, and furthermore, isn't specific to the module but is actually specific to the compiler (so I'm changing what I said about the module owning all imports). This means you can still compile your module with a completely different `object.d` implementation so long as it maintains the same symbols required by the compiler and maintains the same public-facing API that is available to the module.

As I write this out, it makes me think that splitting up `object.d` could be an improvement to this situation.  If the compiler intrinsic functions were deployed along-side the compiler binary in a module, say "intrinsics.d".  This way we could keep the intrinsic functions but disable everything else in `object.d`.

Anyway I've gone off on a bit of a tangent.  I still think that if you want to disable the `object` module, then it should be done inside the module.  If a module needs to be compiled a certain way (i.e. a compiler that does not assume object is imported) then the module should declare that requirement rather than forcing the user to specify it as a compiler option and then failing with some seemingly unrelated compiler errors when then don't.

2019-07-17 02:23 UTC, JinShil commented
I've given this some thought, but I can't support it.

We don't need another specialized, niche feature added to the compiler to workaround fundamental problems.  Instead, we should be making fundamental improvements or adding transitional features that help us migrate towards those fundamental improvements.

This feature doesn't offer any practical benefit to the user over simply creating an `object.d` file, yet it arguable makes matters worse by adding more hard-coded logic to the compiler when we should be working to remove such logic from the compiler.

2019-07-17 04:15 UTC, Geod24 requested changes
I second @JinShil here. I can't support this.

2019-07-17 04:16 UTC, marler8997 commented
@Geod24 are you in favor of the command-line option instead?  If so why?

2019-07-17 04:20 UTC, marler8997 commented
@JinShil 

Based on your response it sounds like you think that #10184 will help move transition the language to more fundamental improvements?  Can you elaborate on that?

Also how do you handle intrinsics? We are currently using `object.d` for code that the compiler would otherwise generate?  Are you saying you want to move code from `object.d` into the compiler by generating AST during compile time?  That would be alot harder to maintain right?

2019-07-17 04:29 UTC, Geod24 commented
> @Geod24 are you in favor of the command-line option instead? If so why?

I'm still thinking about it, but I'm completely sure I don't want us to introduce a **language feature** for this.

2019-07-17 04:30 UTC, marler8997 commented
This isn't a language feature, it's using a user-defined attribute.  It's already apart of the language.  See the description for why we would want this to be configured in the module rather than a command-line option.   Of course, that's assuming we want the feature in the first place.

2019-07-17 04:44 UTC, JinShil commented
> Based on your response it sounds like you think that #10184 will help move transition the language to more fundamental improvements? 

See my comments at https://github.com/dlang/dmd/pull/10180#issuecomment-512093803 for some more detail about my perspective.

In general, I don't see `-dnostdlib` as a transitional feature.  A transitional feature would be one that we could eventually do away with or one that is provided primarily for backward compatibility and tucked into a dark closet with our other skeletons (e.g. `dmd.conf`).

> Also how do you handle intrinsics? We are currently using object.d for code that the compiler would otherwise generate? Are you saying you want to move code from object.d into the compiler by generating AST during compile time? That would be alot harder to maintain right?

All great questions.  D is a little different from C/C++ in that it has part of its implementation in the runtime itself, that many would want implicitly imported for convenience.  I don't think it's too much to ask to have users explicitly import the language features they intend to use (they can all be aggregated into one `package.d` if you want all that D has to offer), but that's already proven to be an unpopular opinion.

As I mentioned in my other in the other PRs and on Slack, I would prefer to have this logic delegated to the toolchain configuration (i.e. `dmd.conf`).  I believe it would only require one transitional compiler switch (e.g. `-implicitlyImport=object`), but I haven't explored it completely yet.  A `-implicitlyImport` compiler switch would also allow us to separate the runtime hooks, intrinsics, and other "compiler-only" mechanisms into separate files form `object.d` and implicitly import them through `dmd.conf`.  This will be good for some of the refactoring work that currently going on in druntime.  I also think it would empower users with other use cases including the use cases that prompted this PR (bare metal, embedded systems, operating systems, drivers, etc...) where one may not want `object.d` or may choose to organize a custom druntime a little differently.

2019-07-17 04:48 UTC, marler8997 commented
Ok well it sounds like we want the same things, just need to work out the best way to get there. Let's keep thinking on this and hopefully we'll hear back from @WalterBright on #9936 and #9944 .  If he rejects them then we'll have to rethink the strategy of moving things into `dmd.conf`.

2019-07-17 04:53 UTC, marler8997 commented
@JinShil you keep bringing up the point that the language shouldn't implicitly import anything.  This is something I've kept note of as well.  I've been playing around and exploring the zig language which uses this strategy.  It only imports what you explicitly import and only links to what you tell it to link to.  This means the helloworld example is a bit longer since you always need an import, but it makes bare-metal/alternate runtimes more straightforward.  Might be worth looking into if you're interested.  I've ported a few of my D projects to it so I could really learn it and I think it's got alot of potential.  It is still pretty new though and there's a few big changes coming down the pike soon but still very usable right now.

2019-07-17 04:58 UTC, JinShil commented
@marler8997 I'm aware of the Zig language and have been checking in on it periodically.  If it had a statically-checked memory safety mechanism and a better way to model object composition, I'd be more interested.  I think the `@reify` feature is supposed to help with the latter, but I don't know if there are any plans for statically-checked memory safety.

2019-07-17 05:01 UTC, marler8997 commented
That's funny because I just added a proposal for `@reify` earlier today, not knowing it was already proposed.  I seem to have convinced Andrew to implement at least a subset of it for simple types, so hopefully that gets implemented soon.

What kind of statically-checked memory safety are you looking for?  Does D have some checking that zig doesn't?

2019-07-17 05:04 UTC, JinShil commented
> What kind of statically-checked memory safety are you looking for? Does D have some checking that zig doesn't?

Yes, `@safe`, `scope` and `return` lifetime attributes, and hopefully someday [this](https://dlang.org/blog/2019/07/15/ownership-and-borrowing-in-d/).  I'm not aware of any such objective in Zig.

2019-07-17 05:11 UTC, marler8997 commented
Whoa this is a big proposal/change to the D language!  Very cool stuff.  Can't wait to see what happens with it.

2019-07-17 05:47 UTC, WalterBright commented
The need for such a feature is so specialized that the programmer doing it shouldn't have any difficulty creating a dummy object.d with nothing in it to import.

I don't think this feature pulls its weight.

2019-07-17 14:01 UTC, marler8997 commented
@WalterBright fair enough. Do you feel the same way about #10184?

2019-07-18 00:44 UTC, WalterBright commented
@marler8997 yes.

2019-07-18 00:47 UTC, marler8997 commented
Closing since proper justification for the feature has not been presented.

2019-07-18 00:47 UTC, closed without merging