Make RootObject equals and toChars const
dlang/dmd pull request #10293
Opened 2019-08-09 15:34 UTC by edi33416

This PR  is useful to the the C++ header [generator](https://github.com/dlang/dmd/pull/9971) to generate the dmd frontend header files that are used by `gdc`.

The issue that I'm attempting to solve: D has function covariance, but C++ does not. What this means is that if I have the following D code
```D
extern (C++) class A
{
  void foo() {}
}

extern (C++) class B :  A
{
  override void foo() const {}
}
```
the generated header will look like
```C++
class A
{
  virtual void foo();
}

class B : public A
{
  void foo() const;
}
```
Note that `B` has `void foo() const`
Compiling this code with `g++ -Woverloaded-virtual` (as `gdc` does) will result in the following warning
```bash
warning: 'virtual void A::foo()' was hidden

by `void B::foo() const`
```

2019-08-09 15:35 UTC, edi33416 commented
@andralex

2019-08-09 20:29 UTC, ibuclaw commented
Nothing all sources look to be updated, headers should be updated as well too if they haven't been.

2019-08-09 21:10 UTC, edi33416 commented
> Nothing all sources look to be updated,

I'm sorry, but what do you mean by this?

> headers should be updated as well too if they haven't been.

I haven't updated the headers as they have dropped the `const` from the function declaration in order to work. Adding the `const` won't change the name mangling so I left the headers unchanged, in the "hope" of getting the auto-generated header in soon. I've managed to build `gdc`'s `decl.cc` with the auto-generated header, so I really hope we'll get there soon.

2019-08-10 04:59 UTC, ibuclaw commented
> I'm sorry, but what do you mean by this?

I think I meant _not_, but autocomplete got in the way.  There were some D related errors at last look.

2019-08-10 07:01 UTC, rainers requested changes
See comments

2019-08-10 07:01 UTC, rainers commented on src/dmd/root/rootobject.d
> +    bool equals(RootObject o) const
While we are at it, I think the argument should be made `const`, too.

2019-08-10 07:03 UTC, rainers commented
> Adding the const won't change the name mangling 

It does on Windows and I would be surprised if it doesn't elsewhere (e.g. for overloads), but it is usually irrelevant for virtual function calls if the vtbl is generated on the D side.

2019-08-15 12:06 UTC, edi33416 commented on src/dmd/mtype.d
> +        return cast(inout(Type)) unqualThis.mutableOf();
What's the status for this going forward?

2019-08-15 17:40 UTC, rainers commented on src/dmd/declaration.d
> +                return (cast() fd).isUnique();
What I meant was to make `isUnique` const and do the cast there (in the call to `overloadApply` IIRC).

2019-08-15 17:41 UTC, rainers commented on src/dmd/expression.d
> +            Expressions* unqualElements = cast(Expressions*) elements;
This cast should be no longer necessary.

2019-08-15 17:53 UTC, rainers commented on src/dmd/mtype.d
> +        return cast(inout(Type)) unqualThis.mutableOf();
I think adding a comment that `mutableOf` needs a mutable `this` only for caching should be good enough for now. Moving that down to where the actual caching takes place (in `fixTo`) could be in another PR.

2019-08-19 13:09 UTC, edi33416 commented
@rainers do you know why the tests are failing? I didn't manage to find the `struct S` that's causing problems with `toString`. I guess that struct needs to override with a `toString() const`.

2019-08-19 14:01 UTC, Geod24 commented
@edi33416 : https://github.com/dlang/dmd/blob/4abeae0d53994610e2e7e6adf03c9313675949d0/src/dmd/root/array.d#L252

2019-08-19 14:40 UTC, edi33416 commented
> @edi33416 :
> 
> https://github.com/dlang/dmd/blob/4abeae0d53994610e2e7e6adf03c9313675949d0/src/dmd/root/array.d#L252

I hadn't rebase with master..

2019-08-19 17:22 UTC, rainers approved these changes

2019-08-19 17:25 UTC, rainers commented
LGTM. Please squash commits. (Or do we use "squash and merge"? I suspect it will just concatenate commit messages that don't look to nice).

2019-08-20 03:57 UTC, thewilsonator commented
I'll just do the squashing manually.

2019-08-20 03:57 UTC, merged

2019-08-20 04:33 UTC, Geod24 commented
@rainers : FYI, Using `squash and merge` on Github allows you to edit the message. But the bot just squash them, yes.

2019-08-21 11:45 UTC, edi33416 commented
> LGTM. Please squash commits. (Or do we use "squash and merge"? I suspect it will just concatenate commit messages that don't look to nice).

I thought the squash and merge will keep only the first commit message. That's why I didn't do it myself and why I just named the future commits "qf".. Will pay more attention in the future. Thanks @thewilsonator for doing it for me