Remove const qual from covariant methods in Type hierarchy
dlang/dmd pull request #10330
Opened 2019-08-21 14:24 UTC by edi33416

This PR  is useful to the the C++ header [generator](https://github.com/dlang/dmd/pull/9971) to generate the dmd frontend header files that are used by `gdc`.

For a detailed description of the motivation, please see [PR](https://github.com/dlang/dmd/pull/10293)

This is an alternative to #10319 , as making the methods `const` proved to be a non-trivial issue. For more details about this, follow the discussion from [this comment](https://github.com/dlang/dmd/pull/10319#issuecomment-522692762) downwards.

2019-08-21 14:25 UTC, edi33416 commented
CC @jacob-carlborg @rainers @ibuclaw @Geod24

2019-08-21 16:19 UTC, jacob-carlborg commented
What's the point of removing existing `const`?

2019-08-21 16:29 UTC, andralex commented
@jacob-carlborg D supports a finer-grained covariance than C++, which does not allow covariance on const methods overriding non-const methods.

2019-08-21 16:31 UTC, jacob-carlborg commented
Ok, I see.

2019-08-21 17:03 UTC, andralex approved these changes
cc @WalterBright

2019-08-21 20:15 UTC, Geod24 requested changes
This does not seem like an improvement to the code.
Covariant `const` is a great tool, and AFAIK is currently supported in the bindings we have, so loosing this because of auto-generation is far from appealing.

2019-08-21 20:29 UTC, rainers commented
The manual C++ headers just add the additional qualifiers as comments. Can't the header generator just do the same, i.e. emit the prototype of the function as declared in the introducing base class?

2019-08-23 16:19 UTC, edi33416 commented
Closing this as I [made](https://github.com/dlang/dmd/pull/9971/commits/c79401aeebed801227ac14e787754b3f41b13798) the header generator emit the prototype of the function as declared in the introducing base class, as @rainers suggested.

2019-08-23 16:19 UTC, closed without merging