build.d: Add build-examples
dlang/dmd pull request #10504
Opened 2019-10-22 00:32 UTC by MoonlightSentinel

This add `build-examples` to `build.d` and `win32.mak`

2019-10-22 05:32 UTC, wilzbach commented
Umh no one uses the makefiles to build DMD as a library. They few people who do use DMD as library use it via Dub (the Makefile build historically predates the Dub files). Hence, I would suggest simply moving the files here: https://github.com/dlang/dmd/tree/master/test/dub_package (you only need to add the respective dub header to them).
This saves us from adding another 113 lines to build.d. It's already starting to become quite large :/

2019-10-23 18:51 UTC, wilzbach requested changes
Sorry, I should have been clearer. There are no plans to support these examples in `build.d`.

2019-10-23 18:54 UTC, MoonlightSentinel commented
> Sorry, I should have been clearer. There are no plans to support these examples in `build.d`.

Okay, are the examples build by any CI?  `build-examples` is currently part of the autotester.

2019-10-23 19:04 UTC, wilzbach commented
> Okay, are the examples build by any CI? build-examples is currently part of the autotester.

Well, as mentioned, here is what I think we should do:
- move the examples in question to `test/dub_package`
- remove all references in `posix.mak`

Even the dub build is only semi-official, but at least get's used. There's no need to maintain another historic build relic.

2019-10-23 19:15 UTC, MoonlightSentinel commented
Okay

2019-10-23 19:15 UTC, closed without merging