Fix issue 20388 - Parse mixin as an expression in template parameters
dlang/dmd pull request #10584
Opened 2019-11-18 04:48 UTC by BorisCarvajal

2019-11-18 05:37 UTC, ghost requested changes
This fix is not good because something else regresses:

```d
void main() {
    baz!(mixin("int"))();
}

void baz(T)()
{
    static assert(is(T == int));
}   
```

EDIT: I see now that this new breaking change is intentional, i.e it's more interesting to fix what has worked for a longer time, so you can dismiss my request.

2019-11-18 08:50 UTC, ghost approved these changes
Best solution so far.

2019-11-18 14:42 UTC, RazvanN7 approved these changes

2019-11-18 14:42 UTC, merged

2020-12-23 12:44 UTC, tim-dlang commented
This could have introduced a regression: https://issues.dlang.org/show_bug.cgi?id=21501