Issue6592 - di header file created even if errors occur
dlang/dmd pull request #10635
Opened 2019-12-02 10:46 UTC by cristiancreteanu

Moved header file generation at the end to make sure the header file is generate only if no errors occur during compilation.

2019-12-02 11:09 UTC, RazvanN7 requested changes
Thank you for the pull request, but there are some guidelines when contributing to DMD:

 - When fixing an issue you should put "Fix Issue $Issue_number ..." in the commit message so that the bot automatically links your PR to the bugzilla report and automatically closes the issue when the PR is merged.

- Every PR should contain a test file that tests the changed behavior. This is to ensure that future patches do not change the added/established behavior. Take a look in the tests directory from the root of the repo.

Lastly, the patch is a breaking change. Header generation needs to be done before semantic analysis, because semantic usually modifies the AST, therefore influencing the output of the generated header files. More over, it is a performance regression in the situations where you don't care about actually compiling the code, but you want to simply generate header files.

I think that the right fix is to generate the header file, but after semantic, simply check if any errors occurred. If that is the case, then simply delete the file.

2019-12-05 08:21 UTC, WalterBright commented
I agree with @RazvanN7

2019-12-12 11:43 UTC, RazvanN7 commented on src/dmd/dmodule.d
> +            // fatal();
wju is this commented? Maybe it should calll `removeHdrFilesAndFail`?

2019-12-12 11:46 UTC, RazvanN7 commented on src/dmd/dmodule.d
> +            // fatal();
Oh, I see. If it fails, the code in mars.d will catch that.

2019-12-12 11:46 UTC, RazvanN7 approved these changes

2019-12-12 11:48 UTC, RazvanN7 commented
Congratulations on your first dmd PR! Auto-merge-squash toggled on.

2019-12-12 23:19 UTC, merged