obj-c info put in wrong section
dlang/dmd pull request #10723
Opened 2020-01-13 14:44 UTC by adamdruppe

see https://github.com/dlang/dmd/blob/master/docs/objective-c_abi.md#l_objc_label_class_

it looks like the original code was just a minor mistake; perhaps an auto-complete oversight with the starting c...

I emailed Jacob Carlborg and he agreed that was likely it. Without this fix, defining new classes in D doesn't fully work.

2020-01-13 14:47 UTC, thewilsonator commented
Can you write a test case for this, so LDC & GDC don't slip through the cracks.

2020-01-13 15:47 UTC, adamdruppe commented
Note that ldc and gdc have zero support for this feature right now. I want to port it all over to ldc at some point - and we'll have to to call ios support complete - but idk when I'll get around to it.

But I don't even know how to automatically test this. I manually did it in the iPhone simulator actually, which loads this metadata to find the main class. I have a lot of other worth to do and no time to figure it out right now.... so don't wait on me.

2020-01-13 16:10 UTC, jacob-carlborg commented
@adamdruppe could you please remind me what did not work without this change?

2020-01-13 16:15 UTC, adamdruppe commented
Blargh I just shut down the mac a few minutes ago. I might have to get back to you with more details later. But I took the hello world objective C sample and tried to move the class it defines over to D. That failed with a runtime class not found thing without this patch.

2020-01-13 18:07 UTC, jacob-carlborg commented
Is it something like a runtime error when the application is launched, something like this?

```
Unknown class AppDelegate in Interface Builder
```

2020-01-13 18:19 UTC, adamdruppe commented
Yes, something like that.

2020-01-13 18:42 UTC, jacob-carlborg commented
When it comes to testing there are a couple of alternatives that I can think of:

* A test which inspects the running binary and verifies that the correct section has the correct data. This will basically make sure that LDC and GDC get the correct implementation and that no one accidentally changes the section for this data.

* A test which basically does the above but both for a binary written in D and an object file written in Objective-C. Then the section data can be compared. This will make sure that DMD does whatever Clang does. For these two tests the following functions can be used: `getsectdatafromheader_64`, `_NSGetMachExecuteHeader` and `dlopen`. The pointer returned by `dlopen` is actually of type `mach_header_64*`. You can have a look at [2] for an example. These functions are now available in druntime.

* A test which does any of the above alternatives but uses `otool` instead to inspect the binary. The Objective-C sections can be pretty printed. See [1].

* A test which consists of an Xcode project with the code that Adam described above, but with some additional code that will close the application immediately. Then the test can grep for the above output: https://github.com/dlang/dmd/pull/10723#issuecomment-573794082. It's possible to build an Xcode project from the command line using `xcodebuild`. The actual binary needs to be run and not the application bundle, otherwise the output will not be redirected back to the shell.

[1] https://github.com/dlang/dmd/blob/master/docs/objective-c_abi.md#otool
[2] https://github.com/dlang/dmd/blob/49dfbe54f4a0f62a0694aec9fb4184739903a0c2/test/runnable/debug_info.d

2020-01-14 23:42 UTC, WalterBright approved these changes

2020-01-15 04:10 UTC, Geod24 commented
Please add an issue number / changelog entry (and fixing the commit title would be welcome)

2020-01-15 08:15 UTC, jacob-carlborg requested changes
Should have some form of test.

2020-01-15 17:52 UTC, adamdruppe commented
I won't have time on a Mac again for a while, so don't wait for me. I just don't understand why you'd rather have broken code than working code, with all other things being equal.

2020-01-17 02:57 UTC, WalterBright commented
@jacob-carlborg I also added an `objc` keyword to bugzilla to connect together Objective-C issues.

2020-01-17 02:58 UTC, WalterBright commented
https://issues.dlang.org/show_bug.cgi?id=20514

2020-01-17 08:18 UTC, jacob-carlborg commented
> I also added an objc keyword to bugzilla to connect together Objective-C issues.

Yes, I’ve noticed, thanks 👍.

2020-01-17 08:21 UTC, jacob-carlborg commented
```
forkgc2(87368,0x10c869000) malloc: *** error for object 0x7f96e2c03b80: double free
*** set a breakpoint in malloc_error_break to debug
```

Unrelated failure?

2020-02-10 03:11 UTC, adamdruppe commented
Your request for an automatic test is denied. It is a waste of time I don't have.

2020-02-10 06:35 UTC, jacob-carlborg commented
Anyone is free to merge the PR.

2020-02-10 07:33 UTC, Geod24 commented
It's incredibly depressing that in 2020, professional software developers still question the benefit of adding tests when fixing bugs.

2020-02-11 08:55 UTC, WalterBright commented
It's a one liner, I'll just pull it.

2020-02-11 08:55 UTC, merged