Fix Issue 20583 - no warnings printed when indexing through deprecated alias this
dlang/dmd pull request #10803
Opened 2020-02-19 05:34 UTC by RazvanN7

The `op_overload` visit method for `ArrayExp` does not check if the alias this is deprecated. I added the missing check.

2020-02-19 05:35 UTC, thewilsonator approved these changes

2020-02-19 06:22 UTC, Geod24 commented
@thewilsonator: I appreciate your enthusiasm and availability, and I'm glad to have someone willing to sometimes pull the trigger when more prudent folks hesitate, but for the love of god, can you please stop merging unreviewed code within literal seconds after a PR has been submitted ? Myself and countless contributors have asked you many, many times not to do so, as a consequence of real problems that showed up as a result of a hasty merge, and this is one more example. It's completely fine to miss something on a PR, but not giving other people the occasion to review is not.

2020-02-19 06:22 UTC, Geod24 requested changes
In this case, the fix is actually touching on a more serious issue, that error checking is completely bypassed, so error messages are not properly displayed.

Example of the issue:
```D
struct X
{
    int[1] x;
    ref int[1] get() @system
    {
        return this.x;
    }
    deprecated alias get this;
}

void main () @safe
{
    X x;
    version(A) int[1] y = x;
    else            int y = x[0];
}
```

With `version = A` we get a meaningful error message (lines numbers do not match):
```
test.d(24): Error: @safe function D main cannot call @system function test.X.get
test.d(14):        test.X.get is declared here
test.d(24): Deprecation: alias get this is deprecated
``` 

Without it, we get:
```
test.d(25): Error: no [] operator overload for type X
```

Now what I imagine would be the right way to fix it would be to call `resolveAliasThis` a second time with `gag = false` (or potentially, since `alias this` is the last thing tried, just call it once with `gag = false`).

2020-02-19 06:55 UTC, RazvanN7 commented
> or potentially, since alias this is the last thing tried, just call it once with gag = false

That is not possible because `op_overload` is called from different contexts and in some situations there are other alternatives left that are treated after the call to `op_overload`.

2020-02-19 07:24 UTC, RazvanN7 commented
@Geod24  The general rule of thumb is that if `alias this` fails for whatever reason, the error reported is with regards to the initial initial expression (not the aliased this one). So it seems that `version(A)` is actually the faulty one. The example that you've chosen is a very specific one, but think about a more general case:

```d
 struct X
  {
      int x;
      alias x this;
  }
  
  void main ()
  {
      X x;
      string y = x;                                                                                                                           
  }
```
In this situation, the reported error is that `X` is not implicitly convertible to `string` which is the correct one. What you are proposing is solved by always giving precedence to the alias this error, which as I've shown should not be done.

So I think that this should be merged as is and the version(A) should be filed as a bug report.

2020-02-19 10:13 UTC, Geod24 commented
> The general rule of thumb is that if `alias this` fails for whatever reason, the error reported is with regards to the initial initial expression (not the aliased this one). 

Where does that come from ? Because it's not exactly what's being done.
If I can attempt a rephrasing, I would say:
> Error messages point out error in user code without exposing the compiler's internal state.

> The example that you've chosen is a very specific one, but think about a more general case [...]

<offtopic>I didn't really choose it, it was quite obvious from the diff in this PR. I implemented `deprecated alias this` so I was surprised that the fix was to call `checkDeprecatedAliasThis` from *outside* `resolveAliasThis`, which is where the check is currently done.</offtopic>

It wouldn't make sense for the compiler to error about `int` not being convertible to `string` when the type being converted is `X`. However, it does make sense for it to complain that a function that would allow the conversion can't be called in this context. This is what is currently done, and what user expect (another example of this with a similar functionality: https://forum.dlang.org/post/uagailyudxmammcneltr@forum.dlang.org).

> What you are proposing is solved by always giving precedence to the alias this error, which as I've shown should not be done.

As explained in the previous paragraph, this is quite a misrepresentation. The `alias this` should not be considered if there's an overload resolution error, however if the overload resolves but cannot be called, then that error should be shown.

I went over the code and took a look at most places.
Error swallowing is done in opover's [UnaExp](https://github.com/dlang/dmd/blob/97c2c62a2eab8e401b54f0fed80f1b96797676e9/src/dmd/opover.d#L368-L379) and [ArrayExp](https://github.com/dlang/dmd/blob/97c2c62a2eab8e401b54f0fed80f1b96797676e9/src/dmd/opover.d#L543-L555) which are essentially copy-paste of each other, as well as [`SwitchStatement`](https://github.com/dlang/dmd/blob/f7aaa7d1446e4e96aee5c287b2ba9e74437378ec/src/dmd/statementsem.d#L2518), but it is done for `CaseStatement`...
Meaningful errors message are provided for [CastExp](https://github.com/dlang/dmd/blob/64d714fb92bd45d107b2c38e5c36855576b3036a/src/dmd/dcast.d#L114-L119), for [implicit convertion, obviously](https://github.com/dlang/dmd/blob/64d714fb92bd45d107b2c38e5c36855576b3036a/src/dmd/dcast.d#L114-L119), for [static assert](https://github.com/dlang/dmd/blob/ee19c0b5c0465dfe1581111bb20042988a32dfdb/src/dmd/staticcond.d#L111-L119) although there is a bug in diagnostic (the wrong type is shown if the returned type does not have a boolean value, sigh...), in [ExpInitializer](https://github.com/dlang/dmd/blob/64d714fb92bd45d107b2c38e5c36855576b3036a/src/dmd/initsem.d#L650), and finally [here](https://github.com/dlang/dmd/blob/f7aaa7d1446e4e96aee5c287b2ba9e74437378ec/src/dmd/statementsem.d#L2518).

> That is not possible because `op_overload` is called from different contexts and in some situations there are other alternatives left that are treated after the call to `op_overload`.

Good to know. Got any link ? Curious about what has lower priority than an `alias this`.

2020-02-20 01:57 UTC, RazvanN7 commented
> It wouldn't make sense for the compiler to error about int not being convertible to string when the type being converted is X. However, it does make sense for it to complain that a function that would allow the conversion can't be called in this context. This is what is currently done, and what user expect (another example of this with a similar functionality:

The difference between the your example and mine can be highlighted by acting depending on the error you get while you do semantic with gagged errors. The underlying problem here is that the error mechanism in dmd makes difficult (if not impossible) to act on a case by case basis because you have no way of telling what what the error.

> Good to know. Got any link ? Curious about what has lower priority than an alias this.

Take a look at [1][2][3], in all of this situations if an alias this is not found there is extra logic that handles that case. The problem stems from the fact that op_overload mixes alias this logic with operator overloading logic. The clean way to solve this is to extract the alias this checks out of op_overload and handle them in expressionsem; that would make it easier to add checks depending what the type of error you get.

[1] https://github.com/dlang/dmd/blob/master/src/dmd/expressionsem.d#L9308
[2] https://github.com/dlang/dmd/blob/master/src/dmd/expressionsem.d#L9733
[3] https://github.com/dlang/dmd/blob/master/src/dmd/expressionsem.d#L10637

2020-03-02 06:08 UTC, RazvanN7 commented
@Geod24 What do you think about this? ^

2020-03-02 08:16 UTC, Geod24 commented
I digged a bit more into the way deprecated is handled. To put it midly, it's a mess. Because of the additional symbols that were added to deprecated, I could see 4 differents ways to mark a symbol deprecated. I'm trying to fix some of the most glaring holes on my free time, but I've been slow so far. [This issue](https://issues.dlang.org/show_bug.cgi?id=20307) proved to be a wonderful starting point.

Regarding your comment:
> The underlying problem here is that the error mechanism in dmd makes difficult (if not impossible) to act on a case by case basis because you have no way of telling what type of errors you encountered.

The frontend can distinguish between failing to fail a symbol, failing to fail an overload in an overload set, and failing to call a function. If it finds an overload in a set, it gives you a proper error message. Things get a bit muddy with templates, but with overload set, you do get the right message.

2021-07-06 10:33 UTC, closed without merging