Fix Issue 13292 - DMD accepts both -m32 and -m64
dlang/dmd pull request #11058
Opened 2020-04-25 15:43 UTC by wolframw

Now raises an error when conflicting `-mXXX` arguments are given.
However, multiple `-mXXX` are still valid, iff all `XXX` are the same.

2020-04-25 16:29 UTC, wolframw commented
I did not expect destroying other tests with this change... I'll have a look on it later.

2020-04-25 16:33 UTC, MoonlightSentinel requested changes
I don't think we should do this because it's pretty common to allow flags to override previous flags. E.g. gcc allows both `-m32 -m64` and other `dmd` flags can be specified mutliple times as well (e.g. `-checkaction=C -checkaction=context`)

2020-04-25 16:33 UTC, MoonlightSentinel commented on test/fail_compilation/fail13292.sh
> +exit 0
Avoid bash tests, either convert this into a dshell test or create `fail_compilation/fail13292.d` with an appropriate `TEST_OUTPUT section`, e.g.
```
/*
REQUIRED_ARGS: -m32 -m64
TEST_OUTPUT:
----
Error: Conflicting target architectures specified: $?:32mscoff=-m32mscoff and -m32|32=-m32 and -m64|64=-m64 and -m32$.
----
*/
```

2020-04-25 17:01 UTC, MoonlightSentinel commented
> I did not expect destroying other tests with this change... I'll have a look on it later.

E.g. `compilable/b18197.d` relies on the ability to override the target architecture (which defaults to the hosts) because the bug is `-m32(mscoff)` specific.

2020-04-25 21:16 UTC, wolframw commented
> I don't think we should do this because it's pretty common to allow flags to override previous flags. E.g. gcc allows both `-m32 -m64` and other `dmd` flags can be specified mutliple times as well (e.g. `-checkaction=C -checkaction=context`)

Do you think it's better changing the error message to a warning or just scratching this whole thing?
(This issue is tagged "bootcamp", I sort of—perhaps naïvely so—assumed this to have a similar meaning to "preapproved".)

2020-04-25 21:52 UTC, MoonlightSentinel commented
> Do you think it's better changing the error message to a warning or just scratching this whole thing?

Personally the latter because current behaviour is pretty common  but let's see what other people think.

> (This issue is tagged "bootcamp", I sort of—perhaps naïvely so—assumed this to have a similar meaning to "preapproved".)

To quote the [wiki](https://wiki.dlang.org/Onboarding):

> The "bootcamp" bugs are manually earmarked by senior contributors as bugs that are fit for a beginner to tackle. The ideal bootcamp bug is easy but not too easy, has good impact, can be fixed in 1-3 days by a motivated beginner, and offers a good learning experience.

2020-04-28 23:38 UTC, wolframw commented
"earmarked by senior contributors" and "has good impact" is exactly what makes me assume that the fix to such an issue has at least some value and will not end up in the bin (which is what I meant with "bootcamp" being similar to "preapproved").
Nonetheless, I now agree that this isn't a good idea. Any tests that have their own `-m` are pretty much unfixable, as far as I understand, which is in itself a good example why overriding the `-m` flag can be useful. Thanks for the helpful comments anyway.

2020-04-28 23:38 UTC, closed without merging

2020-04-28 23:57 UTC, Geod24 commented
@wolframw : Thanks for tackling this, and sorry it didn't end up being something we can merge.
I incorporated the discussion in this PR in the issue and marked it as WONTFIX.

For reference, anyone can do triage on Bugzilla, so we might have slightly different interpretation of what it means depending on when the label was applied / who applied it. I just did a quick search and some of those issues are [definitely not trivial](https://issues.dlang.org/show_bug.cgi?id=3462) and require deep understanding of how things work, while some other seem [much simpler](https://issues.dlang.org/show_bug.cgi?id=20616).