start adding support for storage classes for ...
dlang/dmd pull request #11125
Opened 2020-05-10 09:00 UTC by WalterBright

Currently, attributes are accepted for ... function parameters, but they are ignored. They are needed to support calling things like `printf` from @live functions. This is a start on that, by rejecting invalid attributes.

2020-05-10 12:04 UTC, ibuclaw approved these changes
Ok, though looks like the stc field is unused for now.

2020-05-10 14:20 UTC, Geod24 requested changes
Since it's a user-facing change, can you either add a changelog entry, or a Bugzilla issue, so it shows up in the changelog ?
Additionally, can we use "variadic" or something similar to refer to those changes ?
I was personally puzzled by the changes, as `...` in  title usually means the title is too long and continues in the body. Not to mention that grepping for it is quite hard.

2020-05-10 14:37 UTC, MoonlightSentinel commented
Shouldn't this change issue a deprecation instead of an error? Those attributes are useless right now but it's still a special case for `...`  which might break existing code.

2020-05-10 19:46 UTC, WalterBright commented
> deprecation

Deprecation is for good code written in good faith that is now obsolete. Code like `void foo(int x, ref ...)` was always wrong and should be an error.

2020-05-10 19:51 UTC, WalterBright commented
> Ok, though looks like the stc field is unused for now.

Not for long :-) But doing it here enables me to submit independent PRs that rely on it in parallel, rather than doing them serially.

2020-05-10 19:53 UTC, WalterBright commented
The DAutoTest and semaphoreci failures look irrelevant.

2020-05-10 19:53 UTC, merged

2020-05-10 19:56 UTC, WalterBright commented
In support of: https://issues.dlang.org/show_bug.cgi?id=20818

2020-05-11 19:12 UTC, CyberShadow commented
> The DAutoTest and semaphoreci failures look irrelevant.

That doesn't seem to be the case.

The addition of the `import dmd.hdrgen;` line caused the Dub `parser` subpackage to transitively import the `dmd.dub` module through `dmd.hdrgen`, which now causes it to fail to compile because the `parser` package does not have a `stringImportPaths` definition for the `res` subdirectory, so the string import of `default_ddoc_theme.ddoc` fails.