Fix Issue #17712 - Add test cases
dlang/dmd pull request #11300
Opened 2020-06-19 16:30 UTC by ntrel

This bug seems to have been fixed, so this adds the 2 test cases to the test suite. Those test cases were causing a link error about missing symbols.
https://issues.dlang.org/show_bug.cgi?id=17712

2020-06-19 17:15 UTC, PetarKirov approved these changes

2020-06-19 17:21 UTC, PetarKirov commented
It would be interesting to bisect the dmd commit which fixed this bug. In any case, nice catch @ntrel!

2020-06-19 17:23 UTC, PetarKirov commented
Hmm, I just saw that the second test case uses phobos. I think it's also likely that a change to phobos could have changed the outcome of the test case. @ntrel do you think you could try to minimize the second test case, so it doesn't depend on phobos? That way changes to phobos should not affect this test.

2020-06-19 18:03 UTC, schveiguy commented
I think the point is that nobody knows what causes the bug if it still exists. So it's difficult to find a test case that doesn't depend on Phobos when we can't get the bug to trigger with the actual code that used to trigger it.

Technically I would think this test goes into Phobos, but I don't know if Phobos has infrastructure to run tests like DMD does. Are there no test cases in dmd that depend on Phobos?

2020-06-19 18:11 UTC, MoonlightSentinel commented
There are some tests but we are trying to get rid of Phobos inside of the test suite to make those tests reliable.

2020-06-19 18:34 UTC, MoonlightSentinel requested changes
No phobos addtions to the test suite

(I'll try to find a reduced test case using dustmite)

2020-06-19 18:35 UTC, schveiguy commented
I'm happy to have someone change to a test that doesn't use phobos. But the problem I see is, the test doesn't fail, and we don't know what circumstances trigger the bug. So any test we add that isn't exactly like the original tests that failed gives us little chance to find the bug later if it happens to reoccur.

If we are against tests that use Phobos more than testing for regressions, then we should simply remove the test, not insert a test that nobody knows whether it's effective.

2020-06-19 20:56 UTC, NilsLankila commented
Before merging this maybe that using digger will show that the commit who has fixed the bug already brought a good ernough test case.

2020-06-19 22:48 UTC, NilsLankila commented
2nd case digger report:

```
digger: c2eefb0d8d850715f492197b0b1a033d9ad5411a is the first good commit
commit c2eefb0d8d850715f492197b0b1a033d9ad5411a
Author: Razvan Nitu <razvan.nitu1305@gmail.com>
Date:   Sat Apr 27 15:22:34 2019 +0300

    dmd: Merge pull request #9636 from JinShil/dep_visible
    
    https://github.com/dlang/dmd/pull/9636
    
    Remove visiblity and lookup deprecation (Take 2)

diff --git a/dmd b/dmd
index ff11ca9a2..d51135331 160000
--- a/dmd
+++ b/dmd
@@ -1 +1 @@
-Subproject commit ff11ca9a275b7bd0c017fe9815b24cef89d6dd50
+Subproject commit d51135331f26ac43dedf30a789f3ce5a06fc57ff
digger: Bisection completed successfully.
```

first:

```
digger: 88546219d3aaecab4e5c31f6e22597a944a7e138 is the first good commit
commit 88546219d3aaecab4e5c31f6e22597a944a7e138
Author: The Dlang Bot <code+dlang-bot@dawg.eu>
Date:   Fri Sep 7 22:20:09 2018 +0200

    phobos: Merge pull request #6659 from shove70/patch-1
    
    https://github.com/dlang/phobos/pull/6659
    
    Fix Issue 17712 - [REG 2.074] [LINK] Undefined reference to std.conv.toChars!(10, char, 1, uint).toChars(uint)
    merged-on-behalf-of: Nathan Sashihara <n8sh@users.noreply.github.com>

diff --git a/phobos b/phobos
index f03cce20e..217c9af28 160000
--- a/phobos
+++ b/phobos
@@ -1 +1 @@
-Subproject commit f03cce20ea9a67d560331f3358ee774eb1516303
+Subproject commit 217c9af28f6fc9a4f8dc6f11d0eae0ed58805c43
digger: Bisection completed successfully.

```

2020-06-20 07:25 UTC, ibuclaw commented
> I'm happy to have someone change to a test that doesn't use phobos. But the problem I see is, the test doesn't fail, and we don't know what circumstances trigger the bug. So any test we add that isn't exactly like the original tests that failed gives us little chance to find the bug later if it happens to reoccur.
> 

This is what dustmite is for. One can simply get an old version of dmd/phobos with the bug (in a container if need be) and reduce the test until it is stripped of all external dependencies.

2020-06-20 14:13 UTC, ntrel commented
> I don't know if Phobos has infrastructure to run tests like DMD does.

I don't think so. I had a look at porting `dmd/test` to Phobos but it's a bit complicated.

> digger reports 2nd case was fixed by
>> https://github.com/dlang/dmd/pull/9636

Great!

2020-06-20 19:07 UTC, NilsLankila commented
given the dmd PR found by digger (#9636) and assuming its diagnostic is correct, my analysis is that speculative instantiation failed because of the bug that gave access to private members of public imports. So given a public and a private overload, the one actually used was not marked as necessary to be codegen-ed and the one that was not used was marked. If this is true then the tests proposed by this PR are not useful because for example a regression affecting 17712 would be detected if [this test](https://github.com/dlang/dmd/pull/9636/files#diff-e0110728027b5841f15a39f7df29c492), added along with #9636, starts regressing.

2020-06-21 08:32 UTC, ntrel commented
So I made a pull to put the test cases in Phobos:
https://github.com/dlang/phobos/pull/7536
But there it seems b17712.d is failing even without reverting #6659! Here it seems to pass OK.

2020-06-21 08:34 UTC, ntrel commented
Also, Kagamin has a reduced test case for b17712.d, haven't tried it:
https://forum.dlang.org/post/tajisdafczvdabngaaun@forum.dlang.org

2020-06-22 09:51 UTC, MoonlightSentinel commented
Dustmite found a test case (using DMD 2.082.1) that still fails today:
https://issues.dlang.org/show_bug.cgi?id=17712#c21

2020-06-22 13:25 UTC, schveiguy commented
Nice. We should probably close this for now then. And I wonder if that shouldn't just be a new bug report to refocus energy on it.

2020-06-23 08:42 UTC, closed without merging