Pass quiet/verbose information from makefile to build.d
dlang/dmd pull request #11346
Opened 2020-06-29 18:19 UTC by andralex

I needed to take a look at what build.d is running, and there may be an occasional need for that. There was a `QUIET` flag in use (introduced I think by @MartinNowak), so I'm working off of that.

With this PR the quiet mode would be the default, override with `QUIET=` in the command line. (This is a minor change from the previous state of affairs.) The variable is passed down to src/posix.mak and then verboseness of build.d is decided depending on that.

2020-06-29 18:56 UTC, MoonlightSentinel requested changes
You can already use `make -f posix.mak VERBOSE=1` to achive the same result ...

2020-06-30 04:11 UTC, wilzbach requested changes
See https://forum.dlang.org/post/mailman.4224.1593453876.31109.dlang-internal@puremagic.com

2020-06-30 04:32 UTC, Geod24 commented
> See https://forum.dlang.org/post/mailman.4224.1593453876.31109.dlang-internal@puremagic.com

We should start to actively discourage its usage. There's no perfect way to do that, but [at least a message could help](https://github.com/dlang/dub/blob/b8d593945c0c6e7ef6bc82dd3fe6324f021eba19/build.sh#L4-L6).

2020-06-30 22:22 UTC, andralex commented
Cool, I'll close this. @Geod24 please add the exact cmdline in the warning text.

2020-06-30 22:22 UTC, closed without merging