Fix Issue 21058 - __traits(getOverloads) forgets "this" with third ar…
dlang/dmd pull request #11432
Opened 2020-07-19 19:58 UTC by rmanthorpe

…gument or if first overload is a template

2020-07-20 10:21 UTC, UplinkCoder commented
can you do it without changing the name `e` to `exp` ?

2020-07-20 10:32 UTC, rmanthorpe commented
The local `e` was shadowing another `e`. Is it a problem? I can just rearrange to put more into the `if(fd)` block.

2020-07-21 09:13 UTC, UplinkCoder commented on src/dmd/traits.d
> +                if (dte.e1.op == TOK.dotType || dte.e1.op == TOK.this_)
I would negate this branch and leave the default ex = null.

2020-07-21 09:15 UTC, UplinkCoder approved these changes
Looks good to me.
Except for one comment I made.

2020-07-21 10:15 UTC, UplinkCoder commented
very nice and small now

2020-07-26 16:53 UTC, ghost approved these changes

2020-07-26 16:57 UTC, ghost requested changes

2020-07-26 16:57 UTC, NilsLankila commented on src/dmd/traits.d
> +                if (!fd) {
Left curly brace on its own line, [as specified in point 3](https://github.com/dlang/dmd/blob/master/CONTRIBUTING.md#the-following-will-not-be-viewed-with-favor).

2020-07-27 09:47 UTC, ghost approved these changes

2020-07-27 10:01 UTC, NilsLankila commented
Thanks forf this bugfix @rmanthorpe, just one thing is that for small fixups to the main commit you should rather amend, but the "auto-merge-squash" label should do more or less the same.

2020-07-27 10:08 UTC, rmanthorpe commented
Thanks @NilsLankila I'll bear that in mind in the future!

2020-07-27 10:55 UTC, merged