Add __traits(isDynamicArray, T), second try
dlang/dmd pull request #11591
Opened 2020-08-18 09:02 UTC by nordlow

Discussion at https://forum.dlang.org/post/nhnofvzmijywsgqyyibw@forum.dlang.org.

Reopening of https://github.com/dlang/dmd/pull/9014.

2020-08-18 11:19 UTC, ghost approved these changes
The changelog entry needs a bit of work but otherwise this new trait is an easy win.

2020-08-18 11:19 UTC, NilsLankila commented on changelog/trait_isdynamicarray.dd
> +__traits(isDynamicArray, T)
The example should be comething that compiles.

2020-08-18 11:19 UTC, NilsLankila commented on changelog/trait_isdynamicarray.dd
> +has been added that checks whether a type `T` is a dynamic array (slice) or not.
slice between parens is confusing, I'd remove it.

2020-08-18 11:21 UTC, MoonlightSentinel requested changes
The `enum` issue needs to be resolved and both `is` and this trait need to yield the same result

2020-08-18 11:36 UTC, wilzbach commented
Instead of specialized benchmarks, why not replace the Phobos template with this trait and check for a difference?
(Should be easy to do as it's only changing the implementation in std.traits.)

2020-08-18 11:46 UTC, nordlow commented
> Instead of specialized benchmarks, why not replace the Phobos template with this trait and check for a difference?
> (Should be easy to do as it's only changing the implementation in std.traits.)

These are micro-optimizations that might have an effect in very specific cases. It will most likely not have a measureable effect on the overload phobos compilation time.

2020-08-18 12:03 UTC, wilzbach commented
> > Instead of specialized benchmarks, why not replace the Phobos template with this trait and check for a difference?
> > (Should be easy to do as it's only changing the implementation in std.traits.)
> 
> These are micro-optimizations that might have an effect in very specific cases as dmd, druntime and phobos gets further optimizations. It will most likely not have a measurable effect on the overall Phobos compilation time.

FWIW If you can't measure the impact on Phobos, it typically doesn't get merged here.

Also @UplinkCoder conflated internal changes in the compiler which can always be merged as they don't affect the user with adding a new public API which should have a measurable impact.

2020-08-18 12:48 UTC, andralex commented
The measurements were ignored and this has become a sheer negotiation. Do we really want to do compiler development by horse-trading?

We should close this PR and move on. The person-hours we already spent on this are already overwhelming the cumulative future savings in compilation times from now through the Sun becoming a white dwarf.

2020-08-18 14:00 UTC, nordlow commented
Ok with me to close this.

2020-11-04 02:15 UTC, RazvanN7 commented
@nordlow I'm taking the liberty to close this as it seems that a consensus has been reached.

2020-11-04 02:15 UTC, closed without merging