Fix issue 21234: Import expression can read files outside of -J path in case of symlink/hardlink
dlang/dmd pull request #11836
Opened 2020-10-09 10:13 UTC by andrey-zherikov

This change make import expression (`import("...")`) to work on Posix the same way as it works on Windows.

The original code tries to resolve symlinks on Posix and rejects a file if its real path is outside of -J options (although hardlinks pointing outside of -J are allowed).

This approach has the following issues:
- It doesn't allow the use case where -J directory has symlinks to cherry-picked files from other places (hardlinks and/or copying of files are not always possible).
- Different behavior on Posix vs. Windows.

From the other side, providing -J option to compiler means explicit consent to use the content of -J directory regardless of the type of this content (regular file/symlink/pipe etc).

See https://issues.dlang.org/show_bug.cgi?id=21234 for more details.

2020-10-09 11:16 UTC, thewilsonator approved these changes

2020-10-09 13:05 UTC, MoonlightSentinel requested changes, later dismissed
Please add a test case

2020-10-09 16:43 UTC, andrey-zherikov commented
> Please add a test case

Done.

2020-10-14 09:51 UTC, andrey-zherikov commented
Sorry, rebase didn't work the way I expected so I re-applied my changes on top of master and force-pushed them.

2020-10-14 12:04 UTC, merged