fix Issue 19662 - x86_64: Different code output when compiling with i…
dlang/dmd pull request #11944
Opened 2020-11-10 09:20 UTC by WalterBright

…nline/boundscheck on/off

The test case from bugzilla works for me, let's see how it does in the test suite.

2020-11-10 10:35 UTC, thewilsonator commented
Seems to be specifically windows x64.

2020-11-10 10:37 UTC, WalterBright commented
Can someone email me the object file it generates for one of the failed runs of test19662.d ?

2020-11-10 10:50 UTC, thewilsonator commented
sorry my windows box is out of commission. Easiest way is probably to set up DMD as a cross complier by hardcoding 
```
enum TARGET : bool
{
    Linux        = xversion!`linux`,
    OSX          = xversion!`OSX`,
    FreeBSD      = xversion!`FreeBSD`,
    OpenBSD      = xversion!`OpenBSD`,
    Solaris      = xversion!`Solaris`,
    Windows      = xversion!`Windows`,
    DragonFlyBSD = xversion!`DragonFlyBSD`,
}
```
in `globals.d` to be 
```
enum TARGET : bool
{
    Linux        = false,
    OSX          = false,
    FreeBSD      = false,
    OpenBSD      = false,
    Solaris      = false,
    Windows      = true,
    DragonFlyBSD = false,
}
```

2020-11-10 11:15 UTC, MoonlightSentinel commented
> Can someone email me the object file it generates for one of the failed runs of test19662.d ?

[test19662.zip](https://github.com/dlang/dmd/files/5516810/test19662.zip)

2020-12-08 13:55 UTC, Geod24 commented
Any update on this @WalterBright ?

2021-01-07 13:15 UTC, RazvanN7 commented
@WalterBright what is the status of this PR?

2022-07-18 09:00 UTC, RazvanN7 approved these changes

2022-07-18 09:00 UTC, merged

2022-09-05 19:09 UTC, ibuclaw requested changes
Wrong test directory. Build is still broken.