Fix 21570 - __traits(isStaticArray, ...) accepts enums with static...
dlang/dmd pull request #12142
Opened 2021-01-21 14:22 UTC by MoonlightSentinel

...array as base type.

The spec[1] states that a named enum creates a distinct type which is
implicitly convertible to it's base type. Hence `__traits(isStaticArray, <enum>)`
should yield `false` as done for an equivalent `is(...)` expression.

[1] https://dlang.org/spec/enum.html#named_enums

2021-01-22 12:01 UTC, RazvanN7 requested changes
This requires a changelog entry and a deprecation as it is silently changing behavior. Looks good otherwise.

2021-01-22 12:02 UTC, RazvanN7 commented
Also, it looks like there are some public examples that need to be updated.

2021-01-22 12:38 UTC, MoonlightSentinel commented
> This requires a changelog entry and a deprecation as it is silently changing behavior. Looks good otherwise.

How should that deprecation work? Retain the current behaviour and issue a deprecation message for `enum`s?

> Later edit: Hm... it seems that this might not be a bug? Look at this documentation example [1].

Those examples were added long after the introduction of `isStaticArray` to document the current behaviour (see dlang/dlang.org#2507). But if this is intended behaviour it should be documented more obviously, especially because of the missmatch to `is(...)`.

2021-01-22 13:06 UTC, RazvanN7 commented
> How should that deprecation work? Retain the current behaviour and issue a deprecation message for enums?
Yes.

> Those examples were added long after the introduction of isStaticArray to document the current behaviour (see dlang/dlang.org#2507). But if this is intended behaviour it should be documented more obviously, especially because of the missmatch to is(...).

cc @WalterBright @ibuclaw @Geod24

2021-01-25 09:23 UTC, RazvanN7 commented
Why did you delete `Fix` keyword? This does bring a solution to the issue.

2021-01-25 09:24 UTC, RazvanN7 approved these changes

2021-01-25 10:29 UTC, MoonlightSentinel commented
Because this PR just adds a warning for the user, the current behaviour remains unchanged, But I can re-add the fix if preferred.

2021-01-25 10:36 UTC, RazvanN7 commented
My point was that the deprecation should close the issue. An action was taken (i.e. the behavior is deprecated and will be changed) and the bug report no longer has any usefulness. So please re-add the "Fix" keyword.

2021-01-25 10:39 UTC, MoonlightSentinel commented
Fair enough

2021-01-25 10:47 UTC, RazvanN7 commented
Can you also, please, add a changelog entry?

2021-01-25 10:58 UTC, MoonlightSentinel commented
Sorry, see `static_array_enum.md`

2021-01-25 11:06 UTC, RazvanN7 approved these changes

2021-01-25 11:07 UTC, RazvanN7 commented
This would also require a spec change . Specifically, this: https://dlang.org/spec/traits.html#isStaticArray

2021-03-05 11:39 UTC, RazvanN7 commented
After discussing with Walter, it seems that this is not actually a bug. `__traits(isStaticArray)` is designed to see through to the base type. Other `traits` such as `isArithmetic`, `isFloating` etc. work similarly (e.g. in the case of enums they use the basetype), therefore what should be done is to update the spec to clarify this.

2021-03-05 11:49 UTC, closed without merging