Fix Issue 21538 - Overriding with more attributes on delegate parameter is allowed
dlang/dmd pull request #12160
Opened 2021-01-27 16:10 UTC by RazvanN7

```d
interface I
{
    void f(const void delegate() dg) const @safe;
}

class C : I
{
    // this overrride should not be legal
    override void f(const void delegate() @safe dg) const @safe { }
}

void main() @safe
{
    const void delegate() @system dg = { };
    C c = new C;
    // c.f(dg); // error, expected
    (cast(I) c).f(dg); // no error
}
```

Because dmd allows overriding methods to be covariant with the overriden methods, you can end up with the above case which may lead to the execution of unsafe code in safe contexts (imagine that `dg` is called inside `C.f`).

The issue here is that the rules for overriding a class method should not be the same with the rules for overriding an interface method. This PR fixes this by not accepting parameter covariance in the method that implements an interface method. The parameres should be exaclty the same. Return type covariance is still permitted.

I know that this should target stable, issue a deprecation (as it is possible to break code) and add a changelog entry. I just want to see what the potential breakage is.

2021-01-27 16:19 UTC, MoonlightSentinel commented
Not sure if this fix is correct. I've had a short look at that issue and noticed that `covariant` apparently yields inversed results for delegates. Fixing that would be more appropriate AFAICT but it also broke several tests related to attribute-based overloading of `opApply`.

TL:DR: The behaviour is already correct if you replace `delegate` with `function`, so the fix should also target delegates.

2021-01-28 08:45 UTC, RazvanN7 commented
What do you mean by inversed results? It seems to me that the result is fine, a @safe delegate is covariant with a @system one and that is what the covariant function currently yields.

2021-01-28 09:58 UTC, MoonlightSentinel commented
> What do you mean by inversed results? It seems to me that the result is fine, a @safe delegate is covariant with a @System one and that is what the covariant function currently yields.

Sorry, I meant that covariant returns reversed results for delegates compared to checking their function pointers:

```D
typeof(dg1).covariant(typeof(dg2)) = ! typeof(dg1.funcptr).covariant(typeof(dg2.funcptr))
```

---

A more exhaustive example of the current missmatch between functions pointers and delegates:

```d
alias StrongFunction = void function() @safe @nogc pure nothrow;
alias WeakFunction = void function();

class InterfaceFunction {
	void weak(WeakFunction dlg);
	void strong(StrongFunction dlg);
}

class ClassFunction : InterfaceFunction {
	override void weak(StrongFunction dlg) {} // invalid, rejected
	override void strong(WeakFunction dlg) {} // valid, accepted
}

alias StrongDelegate = void delegate() @safe @nogc pure nothrow;
alias WeakDelegate = void delegate();

class InterfaceDelegate {
	void weak(WeakDelegate dlg);
	void strong(StrongDelegate dlg);
}

class ClassDelegate : InterfaceDelegate {
	override void weak(StrongDelegate dlg) {} // invalid, accepted
	override void strong(WeakDelegate dlg) {} // valid, rejeected
}
```

---

This difference can be explained by comparing the function pointer and delegate  branches in `covariant` IIRC:

https://github.com/dlang/dmd/blob/74afd79afaad88c30ed77ef9bc0eda7333b723e5/src/dmd/mtype.d#L630-L634

Checks `tp2 => tp1`

https://github.com/dlang/dmd/blob/74afd79afaad88c30ed77ef9bc0eda7333b723e5/src/dmd/mtype.d#L640-L644

Checks `tp1 => tp2`

2021-02-08 07:19 UTC, Geod24 requested changes
As @MoonlightSentinel mentioned, this is the wrong fix. `interface` and `class` shouldn't behave differently. In your example, one can replace `interface` with `abstract class` and the code will compile.

There were a lot of bug raised by the author, and I think we should consider them together and not in isolation, as they expose flaws in the type system.

2021-02-08 07:19 UTC, Geod24 commented on test/fail_compilation/fail21538.d
> +    (cast(I) c).f(dg); // no error
```suggestion
    C c = new C;
    I i = c;
    // c.f(dg); // error, expected
    i.f(dg); // no error
```

Better to avoid the `cast`.

2021-03-18 13:34 UTC, closed without merging