Update description of DWARF files
dlang/dmd pull request #12183
Opened 2021-02-05 09:03 UTC by Luhrel

2021-02-05 09:16 UTC, RazvanN7 approved these changes

2021-02-05 09:18 UTC, RazvanN7 requested changes
Sorry, I was hasty in approving this. Let's wait to merge this after the DWARF5 implementation otherwise we might end up having documentation that does not yet match the implementation.

2021-02-17 11:02 UTC, Luhrel commented
@RazvanN7 As https://github.com/dlang/dmd/pull/11426 is merged, I think we can merge this.
The other DWARF sections are still not updated, but it's compatible (gdb can interpret them).

2021-02-17 12:02 UTC, RazvanN7 approved these changes

2021-02-17 17:29 UTC, merged