DIP1034: make lambdaHasSideEffect true for noreturn functions
dlang/dmd pull request #12430
Opened 2021-04-13 12:59 UTC by n8sh

Prevents spurious warning `"calling XXX without side effects discards return value of type 'noreturn'; prepend a 'cast(void)' if intentional"`.

Also changes the result of `hasSideEffect` and behavior of `isTrivialExp`.

There appears to be a general inconsistency where a function that performs side-effectful operations may be considered side-effectless but if that is indeed a problem addressing it is beyond the scope of this PR.

2021-04-13 13:01 UTC, thewilsonator approved these changes

2021-04-13 13:12 UTC, RazvanN7 commented
The function `lambdaHasSideEffects` is modified to return `true` for `noreturn` functions. But the test does not test a lambda function but a normal function. Also, if `noreturn` functions are considered to have side effects how can they be considered pure?

I suggest that a bug report is submitted and linked to this issue so that reviewers can better understand the test case and what is the expected result.

2021-04-13 13:13 UTC, RazvanN7 requested changes
Requires a bugzilla entry.

2021-04-13 13:29 UTC, n8sh commented
>The function `lambdaHasSideEffects` is modified to return true for noreturn functions. But the test does not test a lambda function but a normal function.

`lambdaHasSideEffects` is not specific to lambda functions / anonymous functions.

>Also, if noreturn functions are considered to have side effects how can they be considered pure?

For the purpose of `lambdaHasSideEffects` things like `assert(0)` are considered to have side effects even though they do not interact with D's notion of purity.

2021-04-13 13:39 UTC, n8sh commented
Added issue number and targeted stable instead of master.

2021-04-13 13:43 UTC, n8sh commented
>std/math/rounding.d(929): Error: `y.vu[4]` is used before initialized

Oh come on, wtf?

2021-04-13 13:45 UTC, RazvanN7 commented
You might have not rebased on the latest version of stable. Anyway, I think that targeting master is fine. If you target stable, [1] will not benefit from this.

[1] https://github.com/dlang/phobos/pull/7834

2021-04-13 13:50 UTC, RazvanN7 approved these changes

2021-04-15 09:31 UTC, thewilsonator commented
removing auto merge, this has a bunch of failing tests, maybe try rebasing?

2021-04-17 14:35 UTC, merged