Fix Issue 21212 - Segfault with -dip1000
dlang/dmd pull request #12545
Opened 2021-05-20 18:04 UTC by UplinkCoder

2021-05-20 23:35 UTC, thewilsonator requested changes

2021-05-20 23:35 UTC, thewilsonator commented on test/compilable/issue21936.d
> +    }    void registerConstructors(T)()
spacing

2021-05-20 23:35 UTC, thewilsonator commented on test/compilable/issue21936.d
> +import std.datetime;
NO

2021-05-21 00:13 UTC, UplinkCoder commented
@thewilsonator valid points. fixed now.

2021-05-21 00:14 UTC, thewilsonator approved these changes

2021-05-21 00:15 UTC, thewilsonator commented
If this is a regression then this should target stable.

2021-05-21 00:17 UTC, UplinkCoder commented
@thewilsonator I couldn't figure out how to make it target stable.
can you do this?

2021-05-21 00:18 UTC, thewilsonator commented
follow the bot's instructions

2021-05-21 00:37 UTC, UplinkCoder commented
@thewilsonator had to force push because there was still a std.datetime import

2021-05-21 01:59 UTC, merged