dmd.cparse: Add support more C targets
dlang/dmd pull request #12565
Opened 2021-05-22 23:01 UTC by ibuclaw

C Integer sizes are not fixed, with notable variations being:
 - `boolsize`: 4 bytes on PowerPC. Otherwise 1 byte.
 - `shortsize`: 1 byte on AVR (`-mint8`). Otherwise 2 bytes.
 - `intsize`: 2 bytes on AVR, CR16, H8300, M32C, M68000 (`-mshort`), MSP430, PDP11 (`-mint16`), RL78, XSTORMY16. Otherwise 4 bytes.
 - `longsize`: 2 bytes on AVR (`-mint8`). Otherwise 4 or 8 bytes.
 - `long_longsize`: 4 bytes on AVR (`-mint8`). Otherwise 8 bytes.

This follows on from #12537, and as per https://github.com/dlang/dmd/pull/12507#issuecomment-841729977, this allows GDC to set C type sizes as requested from the target backend we are compiling for, so there isn't a mismatch.

@WalterBright

2021-05-23 08:54 UTC, WalterBright commented on src/dmd/cparse.d
> +    private AST.Type integerTypeForSize(ubyte size, bool unsigned)
Instead of the extra parameter, I suggest two functions would be simpler. Adding `unsignedTypeForSize` should do the trick.

2021-05-23 08:58 UTC, WalterBright commented on src/dmd/cparse.d
> -    const ubyte wchar_tsize;      /// size of C wchar_t, 2 or 4
don't remove wchar_tsize

2021-05-23 08:58 UTC, WalterBright requested changes, later dismissed
don't remove wchar_tsize

2021-05-23 22:35 UTC, ibuclaw commented
`wchar_tsize` remains, and `unsignedTypeForSize` added.

2021-05-28 10:26 UTC, RazvanN7 approved these changes

2021-05-28 10:27 UTC, RazvanN7 commented
Why is this a draft?

2021-05-28 13:35 UTC, ibuclaw commented
> Why is this a draft?

To present people from merging it.

2021-05-28 13:36 UTC, ibuclaw commented
Overflow handling needs a bit more scrutiny.  I'm doing comparison tests between gcc and dmd for 16-bit targets.

2022-02-25 10:02 UTC, merged