Extract ClassDeclaration.isBaseOf
dlang/dmd pull request #12883
Opened 2021-07-16 17:20 UTC by benjones

There's a few sort of unrelated overloads of that method (one for types, one for class decls, one for base classes), which was a little confusing to me.  I renamed the base class one because I think there was an issue with overloading a method and a function with UFCS.

Moving this to typesemantic will eliminate another call to symbolsemantic in an AST module.

2021-07-16 23:54 UTC, thewilsonator reviewed
Otherwise looks good

2021-07-16 23:54 UTC, thewilsonator commented on src/dmd/dclass.d
> +bool isBaseOf(ClassDeclaration derived, ClassDeclaration cd, int* poffset)
Please add this back to the headers, it is used by LDC (and I presume GDC).

2021-07-17 08:58 UTC, ibuclaw requested changes, later dismissed

2021-07-17 08:58 UTC, ibuclaw commented on src/dmd/aggregate.h
> -    virtual bool isBaseOf(ClassDeclaration *cd, int *poffset);
Used by gdc.

2021-07-17 20:09 UTC, benjones commented
Is it OK to turn this into a function, or is it not worth changing the API for this?  I assume making the extracted have this signature would work, but require changes a some callsites in the other compilers? `extern(C++) bool isBaseOf(ClassDeclaration derived, ClassDeclaration cd, int* poffset)

2021-07-17 23:03 UTC, thewilsonator commented
> Is it OK to turn this into a function

(assuming you're going to move this to semantic) it is, the function needs to be available in the headers though.

>I assume making the extracted have this signature would work, but require changes a some callsites in the other compilers? extern(C++) bool isBaseOf(ClassDeclaration derived, ClassDeclaration cd, int* poffset)

Correct.

2021-07-19 16:40 UTC, benjones commented
OK, I think this is g2g.  I believe it is an easily fixed breaking change for the C++ API

2021-07-20 00:20 UTC, thewilsonator approved these changes

2021-07-20 00:21 UTC, merged