[DSSv3] Fix Issue 17400: new line before candidates in error messages
dlang/dmd pull request #12915
Opened 2021-07-25 08:58 UTC by dandrei279

Add 2 new lines before candidates in error messages so the text is easier to read.

Before:
```
fail_compilation/fail14997.d(19): Error: none of the overloads of `this` are callable using argument types `()`, candidates are:
fail_compilation/fail14997.d(14):        `fail14997.Foo.this(int a)`
fail_compilation/fail14997.d(15):        `fail14997.Foo.this(string a)`
```

After:
```
test/fail_compilation/fail14997.d(19): Error: none of the overloads of `this` are callable using argument types `()`

Candidates are:
test/fail_compilation/fail14997.d(14):        `fail14997.Foo.this(int a)`
test/fail_compilation/fail14997.d(15):        `fail14997.Foo.this(string a)`
```

2021-07-25 09:00 UTC, thewilsonator commented
Thanks, You will need to update the tests cases that test for this.

2021-07-25 09:01 UTC, thewilsonator approved these changes

2021-07-25 09:43 UTC, ibuclaw requested changes
This won't look pretty in other compilers who do caret printing.

2021-07-25 11:42 UTC, dandrei279 commented
> This won't look pretty in other compilers who do caret printing.

Do you suggest other format? Or just to leave it the way it is?

2021-07-25 12:05 UTC, ibuclaw commented
For reference:
```
fail_compilation/fail14997.d:19:14: error: none of the overloads of ‘this’ are callable using argument types ‘()’, candidates are:
   19 |     auto a = new Foo;
      |              ^
fail_compilation/fail14997.d:14:5: note: ‘fail14997.Foo.this(int a)’
   14 |     this (int a) {}
      |     ^
fail_compilation/fail14997.d:15:5: note: ‘fail14997.Foo.this(string a)’
   15 |     this (string a) {}
      |     ^
```

What you are proposing is:
```
fail_compilation/fail14997.d:19:14: error: none of the overloads of ‘this’ are callable using argument types ‘()’, candidates are:

Candidates are:
   19 |     auto a = new Foo;
      |              ^
fail_compilation/fail14997.d:14:5: note: ‘fail14997.Foo.this(int a)’
   14 |     this (int a) {}
      |     ^
fail_compilation/fail14997.d:15:5: note: ‘fail14997.Foo.this(string a)’
   15 |     this (string a) {}
      |     ^
```

2021-07-26 15:47 UTC, ibuclaw commented
You can also inspect this in dmd with `-verrors=context`

Example before:
```
test/fail_compilation/fail20730b.d(26): Error: template `fail20730b.atomicOp` cannot deduce function from argument types `!("+=")(shared(uint), int)`, candidates are:
        atomicOp!"+="(refs, 1);
                     ^
test/fail_compilation/fail20730b.d(41):        `atomicOp(string op, T, V1)(ref shared T val, V1 mod)`
  with `op = "+=",
       T = uint,
       V1 = int`
  must satisfy the following constraint:
`       __traits(compiles, mixin("(int)mod"))`
T atomicOp(string op, T, V1)(ref shared T val, V1 mod)
  ^
```
Example after:
```
test/fail_compilation/fail20730b.d(26): Error: template `fail20730b.atomicOp` cannot deduce function from argument types `!("+=")(shared(uint), int)`

Candidates are:
        atomicOp!"+="(refs, 1);
                     ^
test/fail_compilation/fail20730b.d(41):        `atomicOp(string op, T, V1)(ref shared T val, V1 mod)`
  with `op = "+=",
       T = uint,
       V1 = int`
  must satisfy the following constraint:
`       __traits(compiles, mixin("(int)mod"))`
T atomicOp(string op, T, V1)(ref shared T val, V1 mod)
  ^
```

2021-07-26 15:59 UTC, ibuclaw commented
> @ibuclaw Do you suggest other format? Or just to leave it the way it is?

You might be able to get away with moving "Candidates are" to `printCandidates` and use `errorSupplemental` to emit it.

2021-08-02 08:19 UTC, RazvanN7 approved these changes

2021-08-02 08:20 UTC, RazvanN7 commented
@ibuclaw Is this good to go?

2021-08-02 08:44 UTC, ibuclaw commented
Looking at the TEST_OUTPUT examples, I wouldn't say this is an improvement.  Try any example with `-verrors=context` and you'll see why.

2021-08-02 08:50 UTC, ibuclaw requested changes
Suggested clearer messages.

2021-08-02 08:50 UTC, ibuclaw commented on test/fail_compilation/constraints_func2.d
>  `       __traits(hasMember, R, "stuff")`
The sort of format that would be more `-verrors=context` friendly.
```suggestion
fail_compilation/constraints_func2.d(119): Error: template `imports.constraints.test24` cannot deduce function from argument types `!()(int)`
fail_compilation/imports/constraints.d(34): Candidate is: `test24(R)(R r)`
  with `R = int`
  must satisfy the following constraint:
`       __traits(hasMember, R, "stuff")`
```

2021-08-02 08:50 UTC, ibuclaw commented on test/fail_compilation/constraints_func3.d
>  fail_compilation/imports/constraints.d(41):        `overload(T)(T v1, T v2)`
```suggestion
fail_compilation/constraints_func3.d(60): Error: template `imports.constraints.overload` cannot deduce function from argument types `!()(int, string)`
fail_compilation/imports/constraints.d(39): Candidates are: `overload(T)(T v)`
fail_compilation/imports/constraints.d(40):                 `overload(T)(T v)`
fail_compilation/imports/constraints.d(41):                 `overload(T)(T v1, T v2)`
```

2021-08-03 07:07 UTC, RazvanN7 commented
ping @dandrei279

2021-08-03 07:25 UTC, dandrei279 commented
> ping @dandrei279

@RazvanN7 On it. I reckon in about 6-7 hours I'm done

2021-08-03 20:55 UTC, ibuclaw commented on src/dmd/func.d
> +            bool single_candidate = td.overnext is null;
```suggestion
            const single_candidate = td.overnext is null;
```

2021-08-03 21:01 UTC, ibuclaw commented on test/fail_compilation/constraints_func3.d
>  TEST_OUTPUT:
Perhaps make a copy of this file -> `constraints_func4.d` and add:
```suggestion
REQUIRED_ARGS: -verrors=context
TEST_OUTPUT:
```
So there's a good example in the testsuite of how this interacts with the `-verrors=context` switch.

2021-08-03 21:02 UTC, ibuclaw requested changes, later dismissed
Some const, add a new test for `-verrors=context` as per above comment, then squash it all into a single commit.

2021-08-04 05:11 UTC, dandrei279 commented
Thank you @ibuclaw for your constant detailed feedback.

2021-08-04 06:58 UTC, RazvanN7 commented
@dandrei279 Please squash these into a single commit. This can be done by doing:

```
git rebase -i HEAD~n    // n - number of commits, 10 in this case
```

Then pick the first commit and f the rest.

2021-08-04 06:58 UTC, RazvanN7 commented on src/dmd/func.d
> -            if (!tf.isref && isRefReturnScope(vthis.storage_class))
This looks like a rebase screw up.

2021-08-04 13:12 UTC, RazvanN7 commented
@ibuclaw Is this good to go?

2021-08-04 13:46 UTC, ibuclaw commented on test/fail_compilation/constraints_func4.d
> +`       N!T`
```
`       N!T`
```
I see that the formatter could still do with some improvements, but this is nothing related to this change here.

2021-08-05 09:16 UTC, merged