ImportC: implement semantics for _Generic
dlang/dmd pull request #12974
Opened 2021-08-11 10:17 UTC by WalterBright

Also discovered and fixed a couple mistakes in cparse for _Generic.

Straightforward implementation.

2021-08-11 10:20 UTC, WalterBright commented
It's important to implement this, as it is intended for `math.h`

2021-08-13 08:35 UTC, RazvanN7 requested changes
This requires the following test cases:

- a generic expression that contains exactly 1 type error
- a generic expression that contains multiple type errors
- a generic expression that contains 1 expression error
- a generic expression that contains multiple expression errors

2021-08-13 16:25 UTC, WalterBright commented
@RazvanN7 code coverage is now 100%.

2021-08-14 10:15 UTC, RazvanN7 approved these changes

2021-08-14 10:15 UTC, merged