ImportC: static initializers for bit fields
dlang/dmd pull request #13002
Opened 2021-08-22 08:27 UTC by WalterBright

Implements static initializers (rather than dynamic ones with StructLiteralExp).

This code is uglier than I would like. Once it works, we can see about trying to find a simpler way.

Since I haven't implemented the non-trivial layout for Posix, the test cases stick to layouts that would be the same across platforms.

2021-08-22 15:29 UTC, ljmf00 requested changes
```c
struct S {
    unsigned a:2;
    unsigned :0;
    unsigned b:3, c:4;
};
```

Need a test case for unnamed bit fields.

> **§6.7.2.1. Structure and union specifiers:** A bit-field declaration with no declarator, but only a colon and a width, indicates an unnamed bit-field. As a special case, a bit-field structure member with a width of 0 indicates that no further bit-field is to be packed into the unit in which the previous bitfield, if any, was placed.

- http://www.open-std.org/jtc1/sc22/WG14/www/docs/n1570.pdf
- https://en.cppreference.com/w/c/language/bit_field

2021-08-22 20:21 UTC, WalterBright commented
> Need a test case for unnamed bit fields.

Done.

2021-08-22 20:50 UTC, ljmf00 approved these changes
> > Need a test case for unnamed bit fields.
> 
> Done.

LGTM, although don't take my approval as valid as I'm not from the organization. The nested `version (none)` conditional statements could be removed, although I understand that might be useful in the future for further debugging.

2021-08-23 09:15 UTC, RazvanN7 approved these changes

2021-08-23 19:47 UTC, WalterBright commented
oops, I hit the wrong ImportC tag :-(

2021-08-23 20:38 UTC, merged