fix Issue 22236 - sizeof an empty C struct should be 0, not 1
dlang/dmd pull request #13009
Opened 2021-08-24 08:38 UTC by WalterBright

I'd forgotten about this little incompatibility between C and C++. Rediscovered it while working on ImportC. I'm surprised it has not been reported yet.

Anyhow, this is needed for ImportC as well.

Note: This is not just for ImportC. It is also for:
```
extern (C) struct S { }
```

2021-08-24 08:52 UTC, ibuclaw commented
But empty structs are not valid C? :-)

2021-08-24 09:03 UTC, ibuclaw approved these changes

2021-08-24 09:43 UTC, WalterBright commented
Wouldn't it be nice if:

Azure Pipelines / Azure pipelines (Windows_VisualD_LDC x86-mscoff)

would come with a brief description of what it is trying to do that is different from the other Azure tests?

2021-08-24 10:24 UTC, Geod24 commented
> would come with a brief description of what it is trying to do that is different from the other Azure tests?

From a quick look, DMD is compiled in release mode on the failing ones.

2021-08-24 10:35 UTC, WalterBright commented
> From a quick look, DMD is compiled in release mode on the failing ones.

That isn't what I meant. DMD is compiled in release mode on successful tests, too. What exactly is  Azure Pipelines / Azure pipelines (Windows_VisualD_LDC x86-mscoff) testing? What does DMD have to do with LDC?

2021-08-24 10:36 UTC, WalterBright commented
I found where the problem is lurking. Will fix it tomorrow.

2021-08-24 22:05 UTC, dukc requested changes
Hmm, there is not supposed to be a difference between memory layouts of `extern (C)` and `extern (D)` structs. You need to update `https://dlang.org/spec/struct.html#struct_layout` if you do this.

For me, having two different memory layout schemes for structs that differ only when empty seems kludgy, especially as the intended use case is 100% undefined behaviour in C.

I think it's better to add a public type to DRuntime that represents empty structs in C APIs.

2021-08-25 05:55 UTC, merged

2021-08-25 06:12 UTC, WalterBright commented
@dukc yes, the spec needs updating, and I did so.

You do have a good point. But here's the problem. gcc and clang both issue warnings on code the developers consider bad, even though legal. But with the zero size struct, they *silently* accept it. What this suggests is that a lot of Important C Code relies on this behavior. Since ImportC is a C compiler, not a C++ compiler, it's probably best to conform to this behavior.

The fly in the ointment is that `extern "C"` structs in g++ and clang++ set the empty struct size as 1. I recommended a solution in our spec, but it's not attractive. If we do an ImportC++, it'll emulate *that* behavior, too.

2021-08-25 10:21 UTC, ibuclaw commented
> @dukc yes, the spec needs updating, and I did so.
> 
> You do have a good point. But here's the problem. gcc and clang both issue warnings on code the developers consider bad, even though legal. But with the zero size struct, they _silently_ accept it. What this suggests is that a lot of Important C Code relies on this behavior. Since ImportC is a C compiler, not a C++ compiler, it's probably best to conform to this behavior.
> 

They don't silently accept it, you won't find it in any key infrastructure code.

GCC
```
empty.c:1:8: warning: struct has no members [-Wpedantic]
```
Clang
```
empty.c:1:1: warning: empty struct is a GNU extension [-Wgnu-empty-struct]
```

2021-08-25 10:55 UTC, dukc commented
There are all kinds of hacks around in C code, so I agree it's reasonable to assume D code may have to interface with C empty structs sometimes, and we should support that.

But that was not the point. The point is that from user perspective, having an `extern(C)` struct memory layout that is usually the same as `extern (D)` but different in one corner case is confusing. I think it would be much less confusing to have a DRuntime symbol that is used as a substitute for empty structs in C interfaces. The symbol can be specially recognized by the compiler, if we can't find a suitable type to alias to.

2023-05-12 15:49 UTC, CyberShadow commented
Could this please also get extended to D structs? There is no reason why an empty D struct takes space, and this results in inefficient code when metaprogramming.