Bitfields posix
dlang/dmd pull request #13027
Opened 2021-08-27 08:30 UTC by WalterBright

I had a lot of grief with this, due to the way Posix lays out bit fields not being documented.

The two test files are actually identical, except for the TEST_OUTPUT section. That section is generated by compiling the code with an actual C compiler, and inserting its output into that section.

I'll make a win32 and win64 version in a later PR.

@ibuclaw you have a good handle on how gcc works with this, so your review is especially appreciated. I'm not terribly confident everything is 100% right.

2021-08-27 08:48 UTC, ibuclaw requested changes
Just done a quick skim through for obvious things so far, will look a bit more in a moment.

2021-08-27 09:25 UTC, ibuclaw submitted a review, later dismissed

2021-08-28 06:39 UTC, WalterBright commented on src/dmd/declaration.d
> +
Unfortunately, it's not that simple. Doing that breaks several of the other tests.

2021-08-28 08:36 UTC, WalterBright commented on src/dmd/declaration.d
> +
done

2021-08-28 08:36 UTC, WalterBright commented on test/runnable/bitfieldsposix32.c
> +struct A0  { int a; long long b:34, c:4; };          // 12 4 (32 bit) 16 8 (64 bit)
incorporated

2021-08-29 00:39 UTC, merged