fix Issue 22275 - importC: Error: incompatible types for '(dest) !is (buf)': 'char*' and 'char[1]'
dlang/dmd pull request #13049
Opened 2021-09-04 21:16 UTC by ibuclaw

Move logic to `typeCombine`, add  handling for array types to saturate to pointers.

2021-09-05 06:39 UTC, WalterBright commented on src/dmd/dcast.d
> +            }
This code is only partially correct. For example, this should compile:
```
int *p;
p = 1;
```
To correct this code, use the function `cimplictConvto()`.

2021-09-05 06:41 UTC, WalterBright commented on src/dmd/dcast.d
> +        }
Use `arrayFuncConv()` instead, which already does this (and also handles function conversion to pointer).

2021-09-05 06:45 UTC, WalterBright commented on test/compilable/testcstuff2.c
> +}
Please add test case:
```
char *p;
p = x ? p : 1;
p = x ? 1 : p;
```

2021-09-05 06:46 UTC, WalterBright requested changes
see comments

2021-09-14 07:46 UTC, WalterBright commented
@ibuclaw ping ?

2021-09-27 11:46 UTC, RazvanN7 commented
@ibuclaw Please apply the review feedback and let's get this in.

2021-09-27 14:20 UTC, closed without merging