Implement the LDC' specific `__traits(initSymbol)`
dlang/dmd pull request #13298
Opened 2021-11-13 12:46 UTC by MoonlightSentinel

`__traits(initSymbol, S)` was introduced in ldc-developers/ldc#3774 and
provides access to the initializer symbol of `S` in a way that does not
rely on `TypeInfo` or other hacks.

This commit contains some small adjustments to the initial patch which
improve the user experience:

- generated `VarExp` points to the `TraitsExp` instead of the symbol LoC
- CTFE issues a specific error message
- more extensive tests

Co-authored-by: Nicholas Wilson <iamthewilsonator@hotmail.com>

2021-11-13 14:36 UTC, thewilsonator commented
also cc @ibuclaw

2021-11-13 14:39 UTC, kinke commented
Thx guys. Will need a spec & changelog addition too. And then we can upstream a cleaned-up version of https://github.com/ldc-developers/druntime/pull/201/files.

2021-11-13 17:09 UTC, ljmf00 commented
Oh damn, I just thought about implementing this yesterday. Thanks a lot! This is particularly useful for using classes in `betterC`. It also removes some runtime nasty implementations.

2021-11-13 17:19 UTC, ljmf00 requested changes

2021-11-13 17:19 UTC, ljmf00 commented on src/dmd/traits.d
> +            return dimError(1);
Please add a test case with more than one parameter.

2021-11-13 17:30 UTC, ljmf00 commented
> Thx guys. Will need a spec & changelog addition too. And then we can upstream a cleaned-up version of [ldc-developers/druntime#201 (files)](https://github.com/ldc-developers/druntime/pull/201/files).

Isn't this also useful if we templatize `_d_newclass` compiler hook? See [here](https://github.com/ldc-developers/druntime/blob/ldc/src/rt/lifetime.d#L78).

2021-11-16 12:31 UTC, MoonlightSentinel commented on src/dmd/traits.d
> +            return dimError(1);
Done

2021-11-16 17:20 UTC, ljmf00 approved these changes
Overall this looks good to me, although it still needs a spec PR.

2021-11-16 18:11 UTC, MoonlightSentinel commented
See  dlang/dlang.org#3122

2021-11-17 03:10 UTC, merged