Replace http:// with https:// for msdn links
dlang/dmd pull request #13453
Opened 2021-12-22 16:25 UTC by ibuclaw

Verified all links work.

MSDN itself though seems to be a deprecated site, and all links redirect to docs.microsoft.com.  The linked for VS.80 are all retired documentation, so the version has been bumped (I guess it'll all be retired again in a couple years though).

2021-12-22 19:05 UTC, ljmf00 requested changes
Please use URL encoded parenthesis to make the link clickable on Github UI and some other editors.

2021-12-22 19:05 UTC, ljmf00 commented on src/dmd/backend/cod1.d
> +        // https://msdn.microsoft.com/en-US/library/ew5tede7(v=vs.100)
```suggestion
        // https://msdn.microsoft.com/en-US/library/ew5tede7%28v=vs.100%29
```

2021-12-22 19:05 UTC, ljmf00 commented on src/dmd/backend/cod1.d
> +        // https://msdn.microsoft.com/en-US/library/ew5tede7(v=vs.100)
```suggestion
        // https://msdn.microsoft.com/en-US/library/ew5tede7%28v=vs.100%29
```

2021-12-22 19:05 UTC, ljmf00 commented on src/dmd/backend/cod3.d
> +     * https://msdn.microsoft.com/en-US/library/dd2wa36c(v=vs.100)
```suggestion
     * https://msdn.microsoft.com/en-US/library/dd2wa36c%28v=vs.100%29
```

2021-12-22 19:05 UTC, ljmf00 commented on src/dmd/backend/cod3.d
> +         * https://msdn.microsoft.com/en-US/library/dd2wa36c(v=vs.100)
```suggestion
         * https://msdn.microsoft.com/en-US/library/dd2wa36c%28v=vs.100%29
```

2021-12-22 19:05 UTC, ljmf00 commented on src/dmd/backend/cod3.d
> +                {   // See https://msdn.microsoft.com/en-us/library/tawsa7cb(v=vs.100).aspx
```suggestion
                {   // See https://msdn.microsoft.com/en-us/library/tawsa7cb%28v=vs.100%29.aspx
```

2021-12-22 19:05 UTC, ljmf00 commented on src/dmd/backend/pdata.d
> + *   https://msdn.microsoft.com/en-US/library/ft9x1kdx(v=vs.100).aspx
```suggestion
 *   https://msdn.microsoft.com/en-US/library/ft9x1kdx%28v=vs.100%29.aspx
```

2021-12-22 19:05 UTC, ljmf00 commented on src/dmd/backend/pdata.d
> + *   https://msdn.microsoft.com/en-US/library/ddssxxy8(v=vs.100).aspx
```suggestion
 *   https://msdn.microsoft.com/en-US/library/ddssxxy8%28v=vs.100%29.aspx
```

2021-12-22 19:05 UTC, ljmf00 commented on src/dmd/target.d
> +            // https://msdn.microsoft.com/en-us/library/7572ztz4(v=vs.100).aspx
```suggestion
            // https://msdn.microsoft.com/en-us/library/7572ztz4%28v=vs.100%29.aspx
```

2021-12-22 19:05 UTC, ljmf00 commented on src/dmd/tocsym.d
> +                 *    https://msdn.microsoft.com/en-us/library/ff553493(VS.85).aspx
```suggestion
                 *    https://msdn.microsoft.com/en-us/library/ff553493%28VS.85%29.aspx
```

2021-12-25 08:27 UTC, MartinNowak approved these changes

2021-12-25 09:21 UTC, merged