Fix issue 22634 - assert for too many symbols should be error
dlang/dmd pull request #13467
Opened 2021-12-28 11:23 UTC by tim-dlang

2021-12-28 13:27 UTC, thewilsonator commented
cc @UplinkCoder

2021-12-28 22:20 UTC, WalterBright requested changes, later dismissed

2021-12-28 22:20 UTC, WalterBright commented on src/dmd/expressionsem.d
> +                        e.error("too many symbols with name `%s`", s.ident.toChars());
"too many" leaves the user dangling wondering how many is too many. A better message would be along the lines of : "more than 65534 symbols generated".

2021-12-29 17:32 UTC, RazvanN7 approved these changes

2021-12-29 17:33 UTC, merged