Add Target.ObjectFormat, use it
dlang/dmd pull request #13512
Opened 2022-01-12 05:54 UTC by thewilsonator

2022-01-12 07:14 UTC, ibuclaw commented on src/dmd/dsymbolsem.d
> +        if (target.objectFormat() == Target.ObjectFormat.coff)
This condition should be a target hook.

2022-01-12 07:14 UTC, ibuclaw commented on src/dmd/dsymbolsem.d
> +                    cd.classKind == ClassKind.cpp &&
And this one too.

2022-01-12 07:14 UTC, ibuclaw commented on src/dmd/target.d
> +    Target.ObjectFormat objectFormat()
Then this can be extern(D) instead.

2022-01-12 08:22 UTC, thewilsonator commented
Feel free to do those in a follow up PR.

2022-01-12 14:40 UTC, ibuclaw requested changes, later dismissed
#13513

2022-01-13 13:29 UTC, RazvanN7 commented
ping @thewilsonator

2022-01-16 01:38 UTC, thewilsonator commented
pong @ibuclaw

2022-01-17 16:20 UTC, RazvanN7 approved these changes

2022-01-17 16:51 UTC, maxhaton approved these changes

2022-01-17 22:39 UTC, merged