End deprecation period for using 'alias this' for partial assignment.
dlang/dmd pull request #13673
Opened 2022-02-16 23:41 UTC by ibuclaw

This has been deprecated in 2.086, time move it on to be a permanent error.

The comments were wrong, we still need to check the RHS for `alias this` first.  If that succeeds with a match, then that takes precedence over the partially constructed LHS `alias this` rewrite.

2022-02-17 00:40 UTC, thewilsonator approved these changes

2022-02-17 01:31 UTC, Geod24 commented
You already raised a PR for this, on which I commented: https://github.com/dlang/dmd/pull/12903

2022-02-17 01:32 UTC, Geod24 requested changes, later dismissed
There's a false positive which would make this a regression.

2022-02-17 07:05 UTC, ibuclaw commented
> There's a false positive which would make this a regression.

Thanks, I've already forgotten about that. The other PR is wrong anyway due to what I have mentioned in the OP.

2022-02-17 07:10 UTC, ibuclaw commented
Need to check https://issues.dlang.org/show_bug.cgi?id=21674

2022-02-17 09:55 UTC, ibuclaw commented
@Geod24 I had a look, and it seems to me that the conditions that check this deprecation/error are looking in the wrong place / too shallow for the intended purpose.

https://issues.dlang.org/show_bug.cgi?id=21674#c7

Would you prefer I address those comments separately, or tack them onto this PR?

2022-02-17 16:27 UTC, ibuclaw commented
Cherry-picked regression fix -> converted to draft until the next stable->master merge.

2022-02-17 17:17 UTC, ibuclaw commented on changelog/alias_this_assignment.dd
> +    r = 0; // Error, cannot use `alias this` to partially initialize variable `r` of type `Rejected`. Use `r.aliased`
I believe the idea is that you are re-initializing it with a new value.

See also the original industry bug report: https://issues.dlang.org/show_bug.cgi?id=19441

2022-02-18 08:59 UTC, RazvanN7 approved these changes
Anything else blocking this?

2022-02-18 11:42 UTC, ibuclaw commented
@RazvanN7 Waiting for merge stable->master to go in, then I'll rebase.

2022-02-18 15:31 UTC, merged