add test case for scoping error with opApply
dlang/dmd pull request #13697
Opened 2022-02-21 08:22 UTC by WalterBright

This adds an important test case.

Changed the return expression to what it always is as sapply is never null. Whether it should be false or not is an issue for another day.

2022-02-21 11:26 UTC, MoonlightSentinel requested changes, later dismissed
Split the PR into two commits because the changes to `scr/dmd/*` don't "add a test case"

2022-03-03 14:48 UTC, dkorpel commented
@WalterBright Can you address Florian's review?

2022-03-07 10:11 UTC, dkorpel approved these changes

2022-03-07 15:10 UTC, RazvanN7 approved these changes

2022-03-07 15:28 UTC, merged