fix Issue 22825 - #line parsing doesn't follow the spec
dlang/dmd pull request #13727
Opened 2022-02-27 10:24 UTC by ibuclaw

Because these special token sequences are sensitive to newlines, they should not be allowed after the introducing `#` token.

2022-02-27 10:26 UTC, ibuclaw commented on src/dmd/lexer.d
> +        this.tokenizeNewlines = false;
Bikeshed topic, whether to just make this field a parameter of `scan()` or not.  I'm on the fence either way.

2022-02-27 10:46 UTC, thewilsonator approved these changes

2022-02-27 11:07 UTC, ibuclaw commented on src/dmd/lexer.d
> +        this.tokenizeNewlines--;
Bikeshed topic, whether to just make this field a `bool` parameter of scan() or not. I'm on the fence either way.

2022-02-28 07:43 UTC, WalterBright requested changes
I think this problem will take care of itself if you implement the changes requested in https://github.com/dlang/dmd/pull/13728

2022-02-28 09:51 UTC, ibuclaw commented
> I think this problem will take care of itself if you implement the changes requested in #13728

#13728 only take care of `# line` because of shared code path in `case '#'`, but everything else that follows would still be in violation.  As I said, this PR modifies `poundLine`, the other modifies `pragmaPack`.

2022-02-28 11:17 UTC, ibuclaw commented
Having read your comments, I see what you mean though, we'll wait and see after (or if) the other PR has been accepted though.

2022-02-28 11:19 UTC, ibuclaw commented
In the meantime, added a spec PR here dlang/dlang.org#3234

2022-03-05 05:17 UTC, WalterBright commented
@ibuclaw needs rebase!

2022-03-18 17:17 UTC, closed without merging

2022-03-18 17:17 UTC, ibuclaw commented
Tests moved to #13728.

2022-03-18 17:17 UTC, ibuclaw commented
Tests moved to #13728.