add Extra to Dsymbol
dlang/dmd pull request #13762
Opened 2022-03-05 08:03 UTC by WalterBright

Most of the fields in Dsymbol are never used, they're just `null`. However, an enormous number of Dsymbol's are generated, so this consumes gobs of memory. This PR pulls out two fields, and puts them in Extra which is allocated separately.

If this goes well, we can transfer many more to Extra.

2022-03-05 10:48 UTC, dkorpel reviewed
D-scanner doesn't like the extra semicolons

2022-03-05 10:48 UTC, dkorpel commented on src/dmd/dsymbol.d
> +        Symbol* csym() { return extra ? extra.csym : null; };
```suggestion
        Symbol* csym() { return extra ? extra.csym : null; }
```

2022-03-05 10:48 UTC, dkorpel commented on src/dmd/dsymbol.d
> +        Symbol* isym() { return extra ? extra.isym : null; };
```suggestion
        Symbol* isym() { return extra ? extra.isym : null; }
```

2022-03-05 10:59 UTC, dkorpel commented
I like this idea. I did a little test to see how often Dsymbol fields remain in their initial state after semantic3. In the `Dsymbol` constructors I append `this` to an `allDsymbols` array and then run this code in mars.d:

```D
    printf("Symbols: %d\n", cast(int) allDsymbols.length);
    enum l = Dsymbol.tupleof.length;
    int[l] defaultCount = 0;
    foreach(d; allDsymbols) {
        static foreach(i; 0..l) {
            if (d.tupleof[i] is d.tupleof[i].init) {
                defaultCount[i]++;
            }
        }
    }
    static foreach(i; 0..l) {
        printf("%20s: %3.2f%%\n", Dsymbol.tupleof[i].stringof.ptr, 100.0 * defaultCount[i] / allDsymbols.length);
    }
```

It gave me these numbers for Druntime:
```
237672 Dsymbols
                csym	99.99%
                isym	99.99%
             comment	99.99%
        ddocUnittest	99.99%
              errors	99.98%
             depdecl	99.98%
        cppnamespace	99.96%
      userAttribDecl	99.95%
        prettystring	99.91%
            localNum	99.77%
              _scope	94.03%
         semanticRun	69.89%
              parent	58.88%
               ident	27.76%
                 loc	17.32%
```

And Phobos:
```
1074846 Dsymbols
        cppnamespace	99.97%
                csym	99.97%
                isym	99.97%
             comment	99.97%
        ddocUnittest	99.97%
             depdecl	99.96%
      userAttribDecl	99.96%
              errors	99.71%
        prettystring	99.69%
            localNum	99.44%
              _scope	94.25%
         semanticRun	54.95%
               ident	48.69%
              parent	41.07%
                 loc	28.65%
```
This doesn't account for other build types and the fact that fields may have been used and reset afterwards, but it does show that indeed most of these fields are just wasting bytes and `csym` and `isym` are a good start to put in extra.

2022-03-05 19:16 UTC, WalterBright commented
Some good statistics. They're more compelling than I expected. I'll try going the route of moving them to derived classes, and for what's left put in Extra.

2022-03-05 19:37 UTC, ibuclaw requested changes
Both this and #13763 breaks downstream compilers. If the goal is to reduce memory footprint, just remove these backend fields and use private hash maps in tocsym to track which Dsymbols have been generated.

2022-03-05 21:39 UTC, WalterBright commented
I don't know what will and won't break gdc and lcd, but I'm surprised that `isym` would break it, as it's a dmd backend symbol.

But your hash table idea is a good one, I think I'll try it out.

2022-03-05 22:14 UTC, ibuclaw commented
> I don't know what will and won't break gdc and lcd, but I'm surprised that `isym` would break it, as it's a dmd backend symbol.

See aliases in gluelayer module: https://github.com/dlang/dmd/blob/c5dfeb1bccf04b2b9a17c11ed97dc1c559618cff/src/dmd/gluelayer.d#L74-L76

I don't have any desire in altering the shared front-end to add more maintenance burden to the process of keeping it in sync.  So it is simply convenient to re-use these fields when walking over all nodes to generate code.

It would appear that LDC would use these fields as well, but it's a bit more explicit in versioning in their own variant of `csym` for their own code generator.

https://github.com/ldc-developers/ldc/blob/eec920e9916816c5c102e0ec01146b2907a29e29/dmd/dsymbol.d#L253-L262

2022-03-05 22:18 UTC, ibuclaw commented
> But your hash table idea is a good one, I think I'll try it out.

This is what I'm trialing out too, but only because it's the most logical way forward to unbreak the build. :-)

2022-03-08 16:42 UTC, maxhaton commented
I have a patch to give coverage info for struct fields somewhere, intended for this very kind of shuffle-timization. I'll try and find it and make a PR

2022-03-12 01:44 UTC, WalterBright commented
Hash tables are a better idea.

2022-03-12 01:44 UTC, closed without merging