Fix issue 22882: Floating-point leading zeroes bug
dlang/dmd pull request #13827
Opened 2022-03-16 16:58 UTC by aposteriorist

This is a simple fix to issue #22882, though I'm sure something cleaner could be done.

Floating-point literals with leading zeroes incorrectly throw an octal digit error, as follows:

`writeln(07.0);` // 7
`writeln(08.0);` // Error: octal digit expected, not `8`
`writeln(010.9);` // 10.9
`writeln(018.9);` // Error: octal digit expected, not `8`
`writeln(00077777.0);` // 77777
`writeln(00077778.0);` // Error: octal digit expected, not `8`

The error is in lexer.d; errorDigit is set in number() in the initial switch case, but when a '.' is subsequently handled later in the function, the error state is never unset.

2022-03-17 02:38 UTC, Geod24 commented
This needs a test to prevent any future regression.

2022-03-17 06:18 UTC, ibuclaw requested changes
Missing tests.

2022-03-17 09:36 UTC, dkorpel commented
Thanks for the bugfix! As mentioned, this needs to be added to the test suite. Take the number literals from the bugzilla issue, and use them in the file `test/fail_compilation/numliteral.c`. You can't use `writeln` because dmd's tests may not import the standard library, so instead use something like this:
```D
float x = 08.0;
static assert(00077777.0 == 77777.0);
```

2022-03-18 16:42 UTC, aposteriorist commented
Actually, I was mistaken. Floating-point literals with leading zeroes work as they should, as of 2.090. I was testing from a lower version. This change is unnecessary and the pull request should be closed.

Since we're here, `test/fail_compilation/numliteral.c` is a test for failure to compile via ImportC, right? But the last test currently in that file,
`// https://issues.dlang.org/show_bug.cgi?id=22549`
`int z = 078.0 + 008. + 009e1;`,
successfully compiles via ImportC. Am I correct in thinking that particular test belongs in `test/compilable/` in this case?

2022-03-18 17:05 UTC, dkorpel commented
> Am I correct in thinking that particular test belongs in `test/compilable/` in this case?

It's not uncommon to have related positive and negative test cases in a single file in fail_compilation. There's no strict guideline on where to place test cases, it's usually judged on an individual basis based on properties like:

- putting related tests in the same file makes it easier to see existing test coverage of a certain language feature
- less files makes the test suite run faster and makes the test folder easier to browse
- but a too large file might make the test too complex. It should remain simple to connect the expected output with the code of the test case.

2022-03-18 21:11 UTC, closed without merging