Fix 22934 - Emit context pointer as `this` instead of `this`
dlang/dmd pull request #13887
Opened 2022-03-25 15:06 UTC by MoonlightSentinel

Because the latter is obviosly not a valid identifier.

2022-03-25 15:30 UTC, dkorpel approved these changes

2022-03-25 15:42 UTC, MoonlightSentinel commented
Fixed the typo in the commit title

2022-03-25 23:52 UTC, thewilsonator approved these changes

2022-03-26 00:21 UTC, ljmf00 requested changes, later dismissed
This will break the `dtoh` end-user API. Probably we should add a changelog entry explaining it.

2022-03-26 02:00 UTC, MoonlightSentinel commented
How so? Any header affected by this change wasn't compilable anyways (`this` is a reserved identifier`)

2022-03-27 05:10 UTC, merged