fix Issue 22935 - importC: offsetof with array element gives 'derefer…
dlang/dmd pull request #13925
Opened 2022-03-30 08:03 UTC by WalterBright

…ence of invalid pointer'

Could use a refactoring to eliminate some copy/pasta, but that's best left to a followup.

2022-03-30 09:07 UTC, dkorpel commented on src/dmd/optimize.d
> +                    const offset = mulu(index, ts.nextOf().size(e.loc), overflow);
D-scanner doesn't like this unused variable

2022-03-30 09:09 UTC, dkorpel requested changes, later dismissed
Add tests for the error branches

2022-03-31 08:23 UTC, RazvanN7 approved these changes

2022-03-31 08:23 UTC, merged

2022-04-18 04:59 UTC, WalterBright commented
Appears to cause https://issues.dlang.org/show_bug.cgi?id=22976