fix Issue 23166 - seg fault when compiling with -inline
dlang/dmd pull request #14191
Opened 2022-06-07 03:15 UTC by WalterBright

I don't know why this wasn't discovered before.

2022-06-07 06:14 UTC, thewilsonator requested changes, later dismissed
ICEs go to stable.

2022-06-07 06:24 UTC, ibuclaw commented
> ICEs go to stable.

Yes please.

2022-06-07 07:37 UTC, WalterBright commented
This is a bug that's been in the compiler for a decade or even longer. It's never been reported before. Why risk destabilizing the compiler?

2022-06-07 12:29 UTC, dkorpel approved these changes

2022-06-09 11:24 UTC, RazvanN7 approved these changes

2022-06-10 00:22 UTC, merged