Implement `private(this)` visibility attribute
dlang/dmd pull request #14238
Opened 2022-06-22 16:00 UTC by dkorpel

Based on recent discussions in the newsgroup about `private` to the class instead of module:

[`restricted` member variables](https://forum.dlang.org/post/ccqkjqeueuapanfrbdxj@forum.dlang.org)
[Adding a new design constraint to D](https://forum.dlang.org/post/sldtyzrqpsqgobsgcmpy@forum.dlang.org)

The `private(this)` syntax is inspired by Scala's `private[this]` and D's `package(name)`. 
It's only enabled under the `-preview=privateThis` switch since it's not part of the language yet.

2022-06-22 18:03 UTC, ibuclaw commented
> The `private(this)` syntax is inspired by Scala's `private[this]` and D's `package(name)`. It's only enabled under the `-preview=privateThis` switch since it's not part of the language yet.

Unlike Scala, this compiles when it shouldn't though:
```
class C
{
    private int secret;

    void thisTest()
    {
        this.secret = 1; // OK
    }

    void otherTest(C other)
    {
        other.secret = 2; // OK, but expect FAIL, as we are in the
                          // instance method of `this`, not `other`.
    }
}
```

2022-06-22 18:05 UTC, ibuclaw requested changes
As per comment, I think this should be considered as well.

2022-06-22 19:06 UTC, dkorpel commented
> As per comment, I think this should be considered as well.

Do you think that behavior is useful, or is the point that the syntax is misleading when it doesn't do the same as Scala? I didn't see anyone ask for that behavior.

2022-06-22 19:11 UTC, 12345swordy commented
> > As per comment, I think this should be considered as well.
> 
> Do you think that behavior is useful, or is the point that the syntax is misleading when it doesn't do the same as Scala? I didn't see anyone ask for that behavior.

I don't see that behavior is useful, as I came from the c# background not Scala. Regardless a DIP for this in order, as it not quite clear on what it should do.

2022-06-22 19:41 UTC, dkorpel commented
> as it not quite clear on what it should do.

You just said it yourself:

> It should be accessible within the body of the class in which the private(this) is declared at.

Notice that this is a preview feature, similar to `-preview=rvaluerefparam`. It's not a definitive language addition or commitment to a specific design.

2022-06-22 19:56 UTC, ntrel commented
C++ also allows access to private members of a (declared) parameter of type X from within a method of X.

2022-06-22 20:28 UTC, maxhaton commented
In line with the forum thread I don't think I've ever actually seen a bug that would've been fixed by this.

2022-06-22 20:28 UTC, maxhaton commented on changelog/private-this.dd
> +Note that this feature it not accepted as part of the D language yet.
```suggestion
Note that this feature has not been accepted into the D language yet.
```

2022-06-22 22:44 UTC, Geod24 requested changes
Likewise, I don't see this as an useful addition to the language. The unit of encapsulation in D is the module, and the module == file, package == directory is one of the core assumption of the language. Trying to circumvent it will make the language worse, not better.

2022-06-23 00:21 UTC, 12345swordy commented
>Trying to circumvent it will make the language worse, not better.

You need to demonstrate this instead of asserting it. The one module per file restriction causes the workaround of putting a class into its own file just to have private follow the traditional OOP paragram.
Many of us do not like that workaround. You rather get rid of the one module per file restriction?

> > as it not quite clear on what it should do.
> 
> You just said it yourself:
> 
> > It should be accessible within the body of the class in which the private(this) is declared at.
> 
> Notice that this is a preview feature, similar to `-preview=rvaluerefparam`. It's not a definitive language addition or commitment to a specific design.

Not quite, I have no idea on what is on your mind with it comes private(this) in terms of rules. A brief description on how it should work would be helpful here.

2022-06-23 00:28 UTC, ibuclaw commented
> It should though. It should be accessible within the body of the class in which the private(this) is declared at. 

Why should it? How is accessing other instances privates a good idea?

> Otherwise how are you supposed to create a deep copy constructor?
> 

Then private is not the visibility you are looking for.

2022-06-23 00:35 UTC, mdparker commented
> ou need to demonstrate this instead of asserting it. 

@12345swordy That's backwards. Whether his assertion is right or wrong, it's up to those pushing this feature to demonstrate its benefit.

> the workaround of putting a class into its own file just to have private follow the traditional OOP paragram

That's not a workaround. That's the design of D. As has been pointed out in the forums, if something shouldn't have access to an aggregate's innards, then they don't belong in the same module. The concept is the same for class internals in Java, but Java doesn't have D-style modules. We've just moved it up one level. The module is the unit of encapsulation, not the class. The module is part of the private interface of any aggregate defined in the module. That's the way to look at this.

However, there is a hole. Because the module is part of the private interface, then the module's public interface is effectively part of the aggregate's public interface. And as has been pointed out in the forums, that allows one to bypass invariant checks and mutex locks (on synchronized classes). But a `private(this)` doesn't fully plug that hole, as any `private` member will still be vulnerable to it.

2022-06-23 00:36 UTC, 12345swordy commented
> > It should though. It should be accessible within the body of the class in which the private(this) is declared at.
> 
> Why should it? How is accessing other instances privates a good idea?

Like I said before: Creating a deep copy constructor. It does not make sense that a class can't access other instance private when they share the same type definition here. I.E. Class A should access the private instance of an class A variable.   I am not talking about two different types here.
 
> > Otherwise how are you supposed to create a deep copy constructor?
> 
> Then private is not the visibility you are looking for.
Nonsense, I am operating from a C# background version of private not a Scala background version of private.

2022-06-23 00:38 UTC, mdparker commented
> Nonsense, I am operating from a C# background version of private not a Scala background version of private.

And we're operating from a D version of private. Looks like there's no standard definition after all.

2022-06-23 00:40 UTC, 12345swordy commented
> > ou need to demonstrate this instead of asserting it.
> 
> @12345swordy That's backwards. Whether his assertion is right or wrong, it's up to those pushing this feature to demonstrate its benefit.
> 
> > the workaround of putting a class into its own file just to have private follow the traditional OOP paragram
> 
> That's not a workaround. 
YES, IT IS. It been brought up in the forums already here. No need for repeated explanations here.

2022-06-23 00:47 UTC, 12345swordy commented
@mdparker 
"if something shouldn't have access to an aggregate's innards, then they don't belong in the same module."
non sequitur. The conclusion does not follow the premises. Replace module with File/Dictionary/Computer to see the absurdity.

2022-06-23 00:59 UTC, ibuclaw commented
> > As per comment, I think this should be considered as well.
> 
> Do you think that behavior is useful, or is the point that the syntax is misleading when it doesn't do the same as Scala? I didn't see anyone ask for that behavior.

It is logically consistent with package(Package) at least, if you consider the missing link between the two being private(Class).

2022-06-23 01:08 UTC, 12345swordy commented
> @12345swordy No, it isn't a non sequitur.

Yes it is. The statement by itself is a non sequitur.

> In D, the module is part of the aggregate's private interface. 

Which can be change via a DIP.

2022-06-23 01:09 UTC, ibuclaw commented
> @mdparker 
> "if something shouldn't have access to an aggregate's innards, then they don't belong in the same module."
> non sequitur. The conclusion does not follow the premises. Replace module with File/Dictionary/Computer to see the absurdity of the statement. 

"If something shouldn't have access to a private key, then they don't belong in the same file/dictionary/computer."

Makes perfect sense to me.

2022-06-23 01:14 UTC, 12345swordy commented
I can keep seeing the false dichotomy when it comes to files usage here. It not an all or nothing when it comes to file usage here, there is a thing called partial file access by corporation with other people here. If you can't understand that notation here, then I am done with D here.

2022-06-23 06:08 UTC, maxsamukha commented
> In line with the forum thread I don't think I've ever actually seen a bug that would've been fixed by this.

I can't remember I've ever seen a bug that would've been fixed by module-private. By that argument, why have 'private' at all if we could just leave private members undocumented or document them as 'don't touch this'? Python goes with '_', and nobody complains.

No matter how I dislike module-private, I would leave it alone for these reasons:

1) The debate about whether `private(this)` should be class-level or object-level will go forever, and nobody will be happy anyway; and having both `private(this)` and `private(class)` is a no go.

2) Object-level would not be specified and implemented reasonably:

```d
class C
{
    void otherTest(C other)
    {
        other = this;
        other.secret = 2; // should pass?
    }
}
```

3) Class-level would have the same issues with 'invariant/synchronized' as module-level does:
```
synchronized class C
{
    // lock 'others'? in which order?
    void otherTest(C[] others)
    {
    }
}
```

2022-06-23 07:00 UTC, ibuclaw commented
> > In line with the forum thread I don't think I've ever actually seen a bug that would've been fixed by this.
> 
> I can't remember I've ever seen a bug that would've been fixed by module-private. By that argument, why have 'private' at all if we could just leave private members undocumented or document them as 'don't touch this'? Python goes with '_', and nobody complains.
> 
> No matter how I dislike module-private, I would leave it alone for these reasons:
> 
> 1) The debate about whether `private(this)` should be class-level or object-level will go forever, and nobody will be happy anyway; and having both `private(this)` and `private(class)` is a no go.
> 
> 2) Object-level would not be specified and implemented reasonably:
> 

If there is no implicit or explicit `this` dereference, then reject it. Var lifetime/borrow tracking doesn't have to be involved in the process - especially given that `@live` is still a moving target.

> 
> 3) Class-level would have the same issues with 'invariant/synchronized' as module-level does:

Right, so object-level would mean that there'll be no need to generate invariants for the object-private fields, as they would be invisible even in reflection code (getMembers). It would be wishful thinking to say the same for synchronized, but for shared references to the same instance.

2022-06-23 08:28 UTC, dkorpel commented
> I don't see this as an useful addition to the language

This PR doesn't add this to the language, it adds an experimental preview feature. Please review it as that, and keep discussion of the merits of the idea on the forums so the comments here can focus on reviewing the implementation.

2022-07-08 16:53 UTC, closed without merging