Fix Issue 22390 - Compiler crash when iterating empty array of bottom types
dlang/dmd pull request #14294
Opened 2022-07-12 10:10 UTC by RazvanN7

I'm not sure this is the right fix. I tracked this down to the backend where the opcode for a specific jump is generated. Since `noreturn` is neither signed, nor unsigned I simply went with what is done for pointers. 

cc @WalterBright .

2022-07-12 10:12 UTC, thewilsonator commented
ICEs go to stable

2022-07-12 10:13 UTC, RazvanN7 commented
Firstly, I don't feet comfortable this going to stable. Secondly, this is currently needed to unblock https://github.com/dlang/phobos/pull/8283 which is targeting master.

2022-07-12 10:58 UTC, Geod24 commented
Since `.1` has just been tagged I think we can let this go to master. CC @ibuclaw

2022-07-12 17:00 UTC, dukc commented
> Secondly, this is currently needed to unblock https://github.com/dlang/phobos/pull/8283 which is targeting master.

I'm not sure my trivial PR is worth to delay crash fixes like this one :smile: . Thanks anyway!

2022-07-14 04:43 UTC, WalterBright commented
Code generation winds up instantiating the template core.array.equality, which attempts to generate code for it. But code for it makes no sense.

`empty==empty` should simply constant fold to `true`.

2022-07-14 04:48 UTC, WalterBright requested changes
See my comment

2022-07-14 07:12 UTC, WalterBright commented
Two arrays of noreturn should simply compare the lengths when doing an equality check.

2022-07-14 08:08 UTC, RazvanN7 commented
@WalterBright Thanks for the clarification. It does make sense to check the length in this situation. I have updated the code.

2022-07-15 09:31 UTC, merged