Add a visitor for CtorDeclaration in transitivevisitor.d
dlang/dmd pull request #14315
Opened 2022-07-18 18:58 UTC by lucica28

The class ParseTimeTransitiveVisitor currently does not implement the visit function for AST.CtorDeclaration and this functionality might be necessary when traversing an ast.

2022-07-18 22:14 UTC, thewilsonator approved these changes

2022-07-18 22:16 UTC, thewilsonator commented
```
ERROR: Newly generated header file (/home/circleci/dmd/generated/linux/release/64/frontend.h) doesn't match with the reference header file (/home/circleci/dmd/compiler/src/dmd/frontend.h)

DETAILS:

diff --git a/home/circleci/dmd/compiler/src/dmd/frontend.h b/home/circleci/dmd/generated/linux/release/64/frontend.h
index 996aa7f7e..18fad6265 100644
--- a/home/circleci/dmd/compiler/src/dmd/frontend.h
+++ b/home/circleci/dmd/generated/linux/release/64/frontend.h
@@ -8034,6 +8034,7 @@ public:
     void visit(FuncLiteralDeclaration* f) override;
     void visit(PostBlitDeclaration* d) override;
     void visit(DtorDeclaration* d) override;
+    void visit(CtorDeclaration* d) override;
     void visit(StaticCtorDeclaration* d) override;
     void visit(StaticDtorDeclaration* d) override;
     void visit(InvariantDeclaration* d) override;
```
please add this new function to the headers

2022-07-20 00:07 UTC, thewilsonator requested changes, later dismissed
Please also add to `visitor.h`

2022-07-21 08:41 UTC, RazvanN7 approved these changes

2022-07-21 14:17 UTC, merged