add scope to constructors
dlang/dmd pull request #14323
Opened 2022-07-22 07:25 UTC by WalterBright

This is so that https://github.com/dlang/dmd/pull/14175 is less likely to run out of memory due to `scope` allocating on the heap rather than the stack.

It's only about half the job, I'll do the rest later once we see how this goes.

2022-07-22 09:08 UTC, RazvanN7 commented
I wasn't able to find any documentation about scope as a function attribute. What does it specifically do? Does it make the constructor callable only for stack allocations? I think that we should better document this.

2022-07-22 17:05 UTC, WalterBright commented
`scope` applied to a member function applies to the `this` hidden parameter.

2022-07-22 17:35 UTC, WalterBright commented
@RazvanN7 see https://dlang.org/spec/function.html#return-scope-parameters paragraph 3.

2022-07-23 05:25 UTC, ibuclaw requested changes, later dismissed
Let's wait on an agreement for what implementation/migration path is to be accepted first.

2022-07-23 19:53 UTC, ljmf00 commented
> @RazvanN7 see https://dlang.org/spec/function.html#return-scope-parameters paragraph 3.

It's an indirect reference to a point that should be more explicit in the spec. There's nothing specific about constructors and how it behaves when applied just `scope`.

2023-02-07 02:20 UTC, WalterBright commented
@ibuclaw > Let's wait on an agreement for what implementation/migration path is to be accepted first.

Why is an implementation / migration path needed? Adding `scope` to the constructor does not harm anything.

2023-02-07 13:03 UTC, RazvanN7 approved these changes
Looks ok to me, but maybe it somehow affects the other backends? cc @kinke @ibuclaw

2023-02-07 16:54 UTC, ibuclaw commented
> @ibuclaw > Let's wait on an agreement for what implementation/migration path is to be accepted first.
> 
> Why is an implementation / migration path needed? Adding `scope` to the constructor does not harm anything.

I assume because there's another PR that adds a new deprecation that needs more work/requires approval, or some forum post where there was push back in this feature.

2023-02-07 17:17 UTC, WalterBright commented
@ibuclaw you're thinking of https://github.com/dlang/dmd/pull/14175. It needs to be merged, too, but this change to the dmd source is good regardless of whether 14175 is merged or not.

2023-02-07 17:18 UTC, merged

2023-02-08 07:15 UTC, ibuclaw commented
> @ibuclaw you're thinking of https://github.com/dlang/dmd/pull/14175. It needs to be merged, too, but this change to the dmd source is good regardless of whether 14175 is merged or not.

Is it really though?

Attribute soup -> terrible
Is the attribute ignored/adds no value without #14175 -> terrible if so
The referenced PR is rejected -> terrible, plus this ought to be reverted if so.