fix Issue 21197 - Wrong lifetime inference with DIP1000 in dmd 2.093.0
dlang/dmd pull request #14360
Opened 2022-08-11 03:25 UTC by WalterBright

2022-08-11 04:55 UTC, WalterBright commented
This is a 2 year old regression. It doesn't need to go in stable.

2022-08-11 09:26 UTC, dkorpel requested changes, later dismissed

2022-08-11 09:26 UTC, dkorpel commented on compiler/test/compilable/test21197.d
> +// https://issues.dlang.org/show_bug.cgi?id=21997
https://issues.dlang.org/show_bug.cgi?id=21197

2022-08-11 09:26 UTC, dkorpel commented on compiler/test/compilable/test21197.d
> +// https://issues.dlang.org/show_bug.cgi?id=21997
```suggestion
// https://issues.dlang.org/show_bug.cgi?id=21197
```

2022-08-12 11:05 UTC, RazvanN7 approved these changes

2022-08-12 11:05 UTC, merged