Remove core.demangle : decodeDmdString
dlang/dmd pull request #14410
Opened 2022-09-04 08:21 UTC by Geod24

Thanks to the new mangling scheme, it shouldn't be needed anymore.

2022-09-04 09:42 UTC, thewilsonator approved these changes

2022-09-04 12:28 UTC, rainers commented
As long as there is OMF support, I would recommend to keep it. Symbols of length longer than 128 are still compressed, see https://github.com/dlang/dmd/blob/master/compiler/src/dmd/backend/cgobj.d#L2442.

2022-09-04 12:42 UTC, Geod24 commented
Thanks, I'll change the PR to document this then.

2022-09-04 12:46 UTC, thewilsonator commented
>As long as there is OMF support 

Speaking of which, when is that getting the axe?

2022-09-04 23:07 UTC, Geod24 commented
Reworked the PR to document things.

2022-09-05 06:00 UTC, rainers approved these changes

2022-09-05 06:06 UTC, rainers requested changes
Sorry, just remembered that I've been using `decodeDmdString` in a couple of tools, including Visual D. Making it `package` will break that, so it is likely others might be affected, too.

Can it still be public without being added to the documentation?

2022-09-05 07:03 UTC, Geod24 commented
Sure thing, fixed

2022-09-05 07:05 UTC, rainers approved these changes

2022-09-05 08:10 UTC, merged