Change globals.noSharedAccess from bool to FeatureState
dlang/dmd pull request #14425
Opened 2022-09-09 18:29 UTC by atilaneves

2022-09-09 22:53 UTC, thewilsonator requested changes
Needs (regular) header updated too. Otherwise looks great.

2022-09-12 14:19 UTC, atilaneves commented
There's a header other than frontend.h that needs updating?

2022-09-12 14:21 UTC, thewilsonator commented
Yes, `globals.h`

2022-10-06 09:02 UTC, thewilsonator approved these changes

2022-10-07 15:06 UTC, merged