core.demangle: Remove the need to shift type ctors and function attributes
dlang/dmd pull request #14469
Opened 2022-09-22 07:44 UTC by Geod24

```
This make it so that those are only written when needed, instead of written eagerly then shifted.
```

The goal is to remove `shift` so that we can use an output range for the demangler.

2022-09-22 07:53 UTC, thewilsonator approved these changes

2022-09-22 08:53 UTC, Geod24 commented
Well found out we don't test `return scope` and co properly, but looking at `dmangle.d` it is obvious what the code should be.

2022-09-22 11:54 UTC, dkorpel requested changes, later dismissed
It looks like this doesn't respect the order of e.g. `return scope` / `scope return` anymore since that info is lost when only setting bit flags, correct?

2022-09-22 11:54 UTC, dkorpel commented on druntime/src/core/demangle.d
> +                while (auto str = typeCtors.toStringConsume(modifiers)) {
Put `{` on a new line.

The same for more instances of this brace style below.

2022-09-22 11:54 UTC, dkorpel commented on druntime/src/core/demangle.d
> +///
Please put a small description here

2022-09-22 11:54 UTC, dkorpel commented on druntime/src/core/demangle.d
> +///
Empty comment

2022-09-22 12:38 UTC, dkorpel commented on druntime/src/core/demangle.d
> +///
Is documentation generated for `private` symbols? And why add this `private` symbol to ddoc but not the others?

2022-09-22 23:34 UTC, ljmf00 commented
Side note: I have an half backed rewritten version of core.demangle without exceptions for normal control flow and some parsing tricks to skip some runtime checks. See https://github.com/ljmf00/demangler/blob/basic-implementation/source/corex/demangle.d . It doesn't work fully but feel free to take any inspiration, if you are into improving heavily the runtime demangler 😀.

2022-09-23 09:13 UTC, Geod24 commented
@ljmf00 : Good to know, and hoping it will land soon! My use case is actually that I would like to do this:
![Magic!!](https://user-images.githubusercontent.com/2180215/191928698-fddea988-5a5c-4a22-8418-d048de6ee7d8.png)
And to do it cleanly, I need to be able to replace `put` at runtime (to decide whether or not to add colors), which is why I'm removing `shift` calls.

2022-09-23 09:33 UTC, Geod24 commented
```shell
% cat foo.d && echo "-----" && dmd -c foo.d && nm foo.o && echo "=====" && nm foo.o | ddemangle
class Foo {
    inout(void*) bar () inout @safe return scope;
    void foo () inout @safe scope;
    void foor () inout @safe return;
    void rab () inout @safe scope return;
}
-----
0000000000000000 t 
                 U _D14TypeInfo_Class6__vtblZ
0000000000000000 D _D3foo12__ModuleInfoZ
                 U _D3foo3Foo3barMNgFNjNfZNgPv
                 U _D3foo3Foo3rabMNgFNlNfZv
                 U _D3foo3Foo4foorMNgFNlNfZv
0000000000000000 V _D3foo3Foo6__initZ
0000000000000000 V _D3foo3Foo6__vtblZ
0000000000000000 V _D3foo3Foo7__ClassZ
                 U _D3foo3FooQiMNgFNlNfZv
                 U _D6object6Object5opCmpMFCQqZi
                 U _D6object6Object6toHashMFNbNeZm
                 U _D6object6Object8opEqualsMFCQtZb
                 U _D6object6Object8toStringMFZAya
                 U _D6Object7__ClassZ
                 U _d_dso_registry
                 U __start_minfo
                 U __stop_minfo
=====
0000000000000000 t 
                 U TypeInfo_Class.__vtbl
0000000000000000 D foo.__ModuleInfo
                 U inout return @safe inout(void*) foo.Foo.bar()
                 U inout scope @safe void foo.Foo.rab()
                 U inout scope @safe void foo.Foo.foor()
0000000000000000 V foo.Foo.__init
0000000000000000 V foo.Foo.__vtbl
0000000000000000 V foo.Foo.__Class
                 U inout scope @safe void foo.Foo.foo()
                 U int object.Object.opCmp(Object)
                 U nothrow @trusted ulong object.Object.toHash()
                 U bool object.Object.opEquals(Object)
                 U immutable(char)[] object.Object.toString()
                 U Object.__Class
                 U _d_dso_registry
                 U __start_minfo
                 U __stop_minfo
```

This is with DMD v1.200.2. Great.

2022-09-23 23:55 UTC, Geod24 commented
@dkorpel : Added tests, fixed the bug, and fixed style issues.

2022-09-26 02:32 UTC, RazvanN7 approved these changes

2022-09-26 02:32 UTC, merged