separate out mangleType()
dlang/dmd pull request #14468
Opened 2022-09-22 06:56 UTC by WalterBright

The Mangler code is very tangled up. This is an attempt at untangling it somewhat, by pulling all the Type mangling into mangleType(). I unsuccessfully tried to minimize the diffs, this was as small as I could get.

2022-09-22 07:03 UTC, thewilsonator requested changes
Split the `mangleParameter` changes into a separate PR, that will cut ~200 lines for the diff

2022-09-22 18:32 UTC, maxhaton approved these changes

2022-09-22 18:35 UTC, WalterBright commented
@thewilsonator it's a good idea, but since it's already passing it's better to move on.

2022-09-22 18:35 UTC, merged

2022-09-23 13:56 UTC, ibuclaw commented
This caused a build regression.
```d
0x22591ad onAssertError
	../../../../libphobos/libdruntime/core/exception.d:558
0xa8158d dmd.dmangle.mangleType(Type, ubyte, OutBuffer*, ref Backref).visitWithMask(Type, ubyte)
	../../gcc/d/dmd/dmangle.d:417
0xa8158d dmd.dmangle.mangleType(Type, ubyte, OutBuffer*, ref Backref).visitWithMask(Type, ubyte)
	../../gcc/d/dmd/dmangle.d:254
0xa815ac dmd.dmangle.mangleType(Type, ubyte, OutBuffer*, ref Backref)
	../../gcc/d/dmd/dmangle.d:422
0xa810b3 dmd.dmangle.mangleFuncType(TypeFunction, TypeFunction, ubyte, Type, OutBuffer*, ref Backref)
	../../gcc/d/dmd/dmangle.d:512
0xa815ac dmd.dmangle.mangleType(Type, ubyte, OutBuffer*, ref Backref)
	../../gcc/d/dmd/dmangle.d:422
0xa815fb mangleToBuffer(Type*, OutBuffer*)
	../../gcc/d/dmd/dmangle.d:43
```

2022-09-23 14:04 UTC, ibuclaw commented on compiler/src/dmd/dmangle.d
> +        case Tuns128:    visitType(t); break;
No.

2022-09-23 14:04 UTC, ibuclaw commented on compiler/src/dmd/dmangle.d
> +            assert(0);
No! This is not equivalent to the original.

2022-09-23 14:05 UTC, ibuclaw commented on compiler/src/dmd/dmangle.d
>      }
The original handled _all_ other types permissively.