Fix security issue 22495
dlang/dmd pull request #14538
Opened 2022-10-08 09:34 UTC by dukc

2022-10-08 09:36 UTC, thewilsonator approved these changes

2022-10-08 10:36 UTC, dukc commented
Hmm it appears this solution would have to unfix https://issues.dlang.org/show_bug.cgi?id=13512.

So we'd have to somehow know if the file is in UTF-8 or some ASCII-extended code page. How could we reliably detect that?

2022-10-09 06:50 UTC, ibuclaw commented
> Hmm it appears this solution would have to unfix https://issues.dlang.org/show_bug.cgi?id=13512.
> 
> So we'd have to somehow know if the file is in UTF-8 or some ASCII-extended code page. How could we reliably detect that?

Isn't the BOM always present when any utf16 or 32 characters exist within a file?

2022-10-09 14:21 UTC, maxhaton requested changes, later dismissed

2022-10-12 06:04 UTC, dukc commented
> Isn't the BOM always present when any utf16 or 32 characters exist within a file?

The problem exists with UTF8 too.

Thinking about this, the only solution would be to detect the native encoding of the system, and then allow it in the shebang if and only if the rest of the file is pure ASCII.

The problem is, that's too complicated to do as a bugfix PR. So essentially two choices:

 - unfixing 13512
 - leaving this issue unsolved for shebangs.

Doing the latter would not allow "invisible" D code, but it would still allow disguising shebang line as something else than it really is. I should note that even with option 1, you can probably invisibly disable (didn't test) D code at the top of file, by using other line endings than "\n" so that the compiler will think the following lines belong to the shebang line.

2022-10-12 06:06 UTC, dukc commented on compiler/src/dmd/root/utf.d
> +@safe bool utf_is_bidi_control(dchar c)
Other functions in this module are named the same way. Or did you mean something else?

2022-10-13 16:11 UTC, dukc commented on compiler/src/dmd/lexer.d
> +                    if (*p & 0x80)
Done.

2022-10-14 19:19 UTC, ibuclaw commented
> > Isn't the BOM always present when any utf16 or 32 characters exist within a file?
> 
> The problem exists with UTF-8 too.
> 

Which UTF-8 character controls the flow of text? Looking at the list of cases in the switch present here, there aren't any.

2022-10-14 20:51 UTC, ibuclaw commented
OK, I see that UTF decided to use [a range of high bits](https://github.com/dlang/dmd/blob/master/compiler/src/dmd/root/utf.d#L455-L464) to denote a UTF-16 or 32 character, which didn't match my expectation of using bits xFF and xFFFF respectively. :-)

I also see that this range of UTF bits are also in conflict with the high end bits [used for KOI-8 characters](https://en.wikipedia.org/wiki/KOI-8).

But could there _really_ be an ambiguity?

Just looking at the individual short hex codes against the KOI-8 table.
'\u061C' - 0xD8+0xA8 - ь+invalid character
'\u200E' - 0xE2+0x80+0x8E - Б+invalid character+invalid character
'\u200F' - 0xE2+0x80+0x8F - Б+invalid character+invalid character
'\u202A' - 0xE2+0x80+0xAA - Б+invalid character+invalid character
'\u202E' - 0xE2+0x80+0xAE - Б+invalid character+invalid character
'\u2066' - 0xE2+0x81+0xA6 - Б+invalid character+invalid character
'\u2069' - 0xE2+0x81+0xA9 - Б+invalid character+invalid character

Yeah, if the aim is to _only_ match and reject bad characters, then it looks like there can't be any ambiguity - at least for this KOI-8 encoding.

If the problem is that `utf_decodeChar` fails after encoutering a cyrillic B character, then proceeds to decode it as something else, then the reasonable default would be to suppress the error, and assume that it must be a 1 byte character of another encoding, then move onto the next byte.

If the problem is that `uft_decodeChar` could ever incorrectly succeed, then that might be something to think about.

2022-10-14 20:55 UTC, ibuclaw commented
On Posix complaint environments, I'd assume that LC_ALL would be set appropriately if you are not using UTF.

2022-10-15 14:25 UTC, dukc commented
If I reject only Bidi characters in the shebang but allow otherwise malformed UTF-8, there will be no problem with KOI-8, but potentially with other code pages such as [windows-1252](https://en.wikipedia.org/wiki/Windows-1252). Putting just any garbage (from Unicode perspective) at the shebang line will usually work, but someone may someday get a strange error.

That's unlikely enough though that it's probably the least evil option here. I'll do it that way.

2022-10-15 17:44 UTC, dukc commented
Done.

@CyberShadow Got ya! [Raw binary data](https://github.com/CyberShadow/ae/blob/71c4567bc7f328860657a08ed60b6f8361a7e002/utils/iconv.d#L106) in strings!

2022-10-15 17:59 UTC, maxhaton commented on compiler/src/dmd/root/utf.d
> +@safe bool utf_is_bidi_control(dchar c)
It's not dmd style, the others need to be restyled too

2022-10-15 17:59 UTC, CyberShadow commented
> @CyberShadow Got ya! [Raw binary data](https://github.com/CyberShadow/ae/blob/71c4567bc7f328860657a08ed60b6f8361a7e002/utils/iconv.d#L106) in strings!
> 
> EDIT: Not binary data, but non-graphic Unicode anyway.

What is the problem, please?

Also, wouldn't it make more sense to look for undesirable characters after decoding, not before?

2022-10-15 18:06 UTC, dukc commented
> What is the problem, please?

Oh sorry, I was probably too aggressive because I thought it was funny. Anyway, raw Unicode directionality overriding characters embedded in those strings.

2022-10-15 18:09 UTC, CyberShadow commented
Got it, thanks. Thought it was something more benign like a no-break space. I agree it makes little sense to allow raw control characters like that (or at least only do so for specific circumstances, like if the entire line is part of a string literal).

I'll fix it in ae tomorrow, feel free to send a PR to expedite that.

2022-10-15 18:12 UTC, dukc commented
BuildKite doesn't seem to be required so it can wait to tomorrow I think.

2022-10-16 01:59 UTC, ibuclaw commented
> If I reject only Bidi characters in the shebang but allow otherwise malformed UTF-8, there will be no problem with KOI-8, but potentially with other code pages such as [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252). Putting just any garbage (from Unicode perspective) at the shebang line will usually work, but someone may someday get a strange error.
> 
> That's unlikely enough though that it's probably the least evil option here. I'll do it that way.

Having a further think about it, who's parsing the shebang anyway? Surely not us, so what issue could arise if we just keep on incrementitg the buffer pointer until the first newline?

It's not a security risk if we don't read it.

I know it sounds like I'm saying just make it someone else's problem, but bidirectional controls being parsed in the shebang would be a shell bug, not compiler.

2022-10-17 07:38 UTC, CyberShadow commented
> I'll fix it in ae tomorrow, feel free to send a PR to expedite that.

[Fixed](https://github.com/CyberShadow/ae/commit/11480387b75a4fe8cf0ddcd95e2382b279fc982c) and tagged.

2022-10-17 19:20 UTC, dukc commented
> Having a further think about it, who's parsing the shebang anyway? Surely not us, so what issue could arise if we just keep on incrementitg the buffer pointer until the first newline?

The potential issue is that if the shell has a vulnerability, a shebang line that seems to be doing something completely different can instead call DMD, where it could not if we kept this check.

This is very theoretical though. If the shell indeed allows doing that it has far bigger problems than DMD not rechecking this one. Also it would be very unlikely for anyone to want to secretly invoke DMD on something that is openly a D source file. So I agree, not worth to keep the shebang check around.

2022-10-17 19:30 UTC, dukc commented on compiler/src/dmd/root/utf.d
> +@safe bool utf_is_bidi_control(dchar c)
Changed name for this function but not for others. That would be way out of scope of this PR.

2022-10-17 19:33 UTC, dukc commented
Done.

I left the refactorings that were needed by the shebang check in place. They are, in my opinion, in the right direction anyway so no point in removing them since they're already in place. I'll remove them if you disagree.

2022-10-18 07:37 UTC, ibuclaw commented
> > Having a further think about it, who's parsing the shebang anyway? Surely not us, so what issue could arise if we just keep on incrementitg the buffer pointer until the first newline?
> 
> The potential issue is that if the shell has a vulnerability, a shebang line that seems to be doing something completely different can instead call DMD, where it could not if we kept this check.
> 

Maybe, but I'm just seeing it from the point of: if someone invoked the compiler by running `./foo.d` the damage has already been done. And the best thing we can do for damage limitation is:
1. Hope people test with `dmd foo.d` before executing via shebang.
2. Hope that any detection errors aren't false positive because the 8-bit sequence is valid for character encoding X-123.
Better I think to focus on the part we have full control over, and directly affects us if we get it wrong.

2022-10-18 07:45 UTC, ibuclaw approved these changes
Lgtm for now, if someone else has a grand idea for shebangs later, we'll run with that.

2022-10-18 07:49 UTC, ibuclaw commented
@dukc a brief changelog to make this visible would be appreciated.

2022-10-26 19:35 UTC, dukc commented
> I don't know what kind of special way you're thinking of

Red fonts, or possibly asking to update immediately. I don't know whether that would be appreciated or needless drama, so I thought it'd be faster for someone who has authority to decide to word the message himself.

Anyway, I added the entry exactly as you wrote it.

2022-10-27 18:08 UTC, dukc commented
ping @ibuclaw

2022-10-27 19:54 UTC, ibuclaw commented
Every security vulnerability disclosed since meltdown that gives itself a name, a website... is needless drama. :-)

2022-10-27 20:28 UTC, CyberShadow commented
I would not call this a vulnerability / (and the change a security fix). I think this is better described as a security precaution and improvement.

2022-10-28 09:24 UTC, ibuclaw requested changes
I've just noticed the changelog name, that should be properly prefixed so it's picked up. :-)

2022-10-28 18:46 UTC, dukc commented
@ibuclaw I assume you mean it the casing had to be corrected. Done. Also fixed the if condition style Dennis said about earlier.

2022-10-28 19:45 UTC, dukc commented
Oh it really needed a prefix. No other entries in my local fork have that prefix so I didn't know what you were talking about.

2022-10-28 20:13 UTC, ibuclaw commented
> Oh it really needed a prefix. No other entries in my local fork have that prefix so I didn't know what you were talking about.

Yes, see #14600 for the change that enforces this. As part of the dmd/runtime merger we still need a way to differentiate between compiler and runtime changes (moving dmd changelog to compiler was rejected, so this is the next least worst thing we can do to keep mostly the same status quo for now).

2022-10-28 20:14 UTC, ibuclaw approved these changes

2022-10-28 22:05 UTC, merged