Fix Issue 3720 - Taking address of member functions possible without an instance
dlang/dmd pull request #14688
Opened 2022-12-12 16:47 UTC by RazvanN7

```d
struct S {
    int a;
    void fun() {
        this.a = 1;
    }
}

void main() {
    auto fp = &S.fun;
    fp();
}
```

The type of `S.fun` is set to `void*`. That way, you cannot call fp directly.

Next step would be to make `delegate.funcptr` return a `void*` also.

I had to modify some dmd tests because now `typeof(S.fun)` is going to return `void*`. I expect such cases to be rare, but this will definitely require a changelog entry and a spec PR. An alternative would be to trigger a deprecation when `typeof(&S.fun)` is encountered. What do you think?

2022-12-12 17:00 UTC, RazvanN7 commented on compiler/test/runnable_cxx/test7925.d
> +    //assert(callMember!(c1.f0)(c1) == 100);
This seems to test the same thing as the above delegate test. What am I missing @ibuclaw ?

2022-12-12 17:14 UTC, Herringway commented
Why? What value does this inconsistency bring to the language?

2022-12-12 18:47 UTC, Geod24 requested changes
No. This is very clearly a hack. Changing the `typeof` so the pointer cannot be called is wrong.
Not to mention, we need more typing on `delegate`, not less.

2022-12-12 21:29 UTC, adamdruppe commented
Yeah, this is definitely wrong. What I'd like to do is formalize the delegate abi a little so we can actually define it. So it might return `void function(S* _this)` instead of `void function()`. Unhide the hidden parameter and define things so that makes sense consistently.

2022-12-13 09:25 UTC, RazvanN7 commented
Most people will agree that taking the address of `S.fun` makes sense only if you want to compare it with another address. Another use case (probably the single one) is to assign it to another delegate's funcptr, but I would argue that that is a niche use case. And all of those would still work if we make the funcptr property have `void*` type.

Taking the address of the delegate is like going to live into the wild, the type system does not protect you anymore and you need to specify everything yourself (via casts). I don't see how making this ugly pattern legal by typing it more is going to help. We need to discourage people to use this kind of code. Typing it even more is the opposite of simplifying the language.

I understand that this may not be the best solution, but @Geod24 @adamdruppe your comments are not constructive at all. Comments like "it's wrong", "it should be like this" without providing a rationale are not helpful at all. Could you maybe present your use cases so that we reach a consensus? I think that your use cases may have other solutions that do not require making the language more complex.

2022-12-13 18:13 UTC, Herringway commented
> Most people will agree that taking the address of `S.fun` makes sense only if you want to compare it with another address. Another use case (probably the single one) is to assign it to another delegate's funcptr, but I would argue that that is a niche use case. And all of those would still work if we make the funcptr property have `void*` type.

I disagree.  Because maintaining interior pointers is unreliable for structs, storing delegates isn't feasible. That leaves us with function pointers, which are currently unusable due to being underdefined, or hacks like [this](https://github.com/dlang-community/D-YAML/blob/9456888327bec4c4c21689e315c7fe99814e1a23/source/dyaml/emitter.d#L1259-L1262). This should be more defined, not less.

Furthermore, taking the address of S.fun is only allowed in `@system` code. Writing `@system` code is already like going to live in the wild. If you want to be protected by the type system, you use `@safe`.

I would also like to point out that casting `void*` to a function pointer is undefined behaviour in C(++), and I'm not aware of D being any different in this regard. If that is the case, then there's nothing of value to be gained from this change.

Taking the address of S.fun should return something useful, or simply be an error.

2022-12-13 18:22 UTC, adamdruppe commented
> Most people will agree that taking the address of S.fun makes sense only if you want to compare it with another address.

Where's your evidence for this? Of course, even if you did prove most people would agree, declaring that makes it right is still an appeal to popularity fallacy, so where is your actual rationale for it?

The existence of tests that had to be commented out (one of which btw, you merged - just last year! - to close another bug report) ought to show that there is another use case to this. How do you justify this regression?

My proposal is to match the actual ABI and make the function both type-safe and actually callable with a runtime function pointer without as many unreliable casts. (Note that with a template alias, you can call `S.fun` now by attaching a child this to it.)

2023-01-03 17:42 UTC, JohanEngelen commented
> Most people will agree that taking the address of `S.fun` makes sense only if you want to compare it with another address. Another use case (probably the single one) is to assign it to another delegate's funcptr, but I would argue that that is a niche use case. And all of those would still work if we make the funcptr property have `void*` type.
> 
> Taking the address of the delegate is like going to live into the wild, the type system does not protect you anymore and you need to specify everything yourself (via casts). I don't see how making this ugly pattern legal by typing it more is going to help. We need to discourage people to use this kind of code. Typing it even more is the opposite of simplifying the language.
> 
> I understand that this may not be the best solution, but @Geod24 @adamdruppe your comments are not constructive at all. Comments like "it's wrong", "it should be like this" without providing a rationale are not helpful at all. Could you maybe present your use cases so that we reach a consensus? I think that your use cases may have other solutions that do not require making the language more complex.

I think you should split this into two parts:
1. `S.fun` currently has no proper meaning. It should be an error. If people use it, then explain that it currently has no meaning in the language. Yes it may have worked for them, but only because of "luck" (remember that D is not assembly, and the value of a pointer just happens to be something you can muck with, but may not have a real meaning in the D language).
2. Start debate about what `S.fun` could possibly mean, make a DIP, etc.

Point 1 needs to be fixed asap, because it leads to hard to find bugs.
Part of the fix could be to provide a solution path for people that did use it for hacks (comparing function similarity is a hack, assigning it to another delegate's funcptr is also a hack); this could be done by introducing a new druntime function or a trait.

Point 2 is a discussion that should not be done inside this PR.

2023-01-04 11:49 UTC, RazvanN7 commented
@JohanEngelen Typing it as `void*` does offer an alternative for people. You just have to manually type the result of `&S.fun` to whatever you need it to be. Simply making it an error will actually cause more breakage. Also, I don't see the point of adding new druntime functions for use of this feature because we will then have to deprecate them also when we come up with a new design.

I think that what could be done is add a deprecation for taking the address of `&S.fun`. Maybe that is the path of least resistance. Or type is as `void*` and also output a deprecation/warning stating that this is dangerous.

2023-01-04 14:51 UTC, JohanEngelen commented
> @JohanEngelen Typing it as `void*` does offer an alternative for people. You just have to manually type the result of `&S.fun` to whatever you need it to be. Simply making it an error will actually cause more breakage.

My viewpoint is that this is an "accepts invalid" bug. Hence breakage is desired.

2023-01-04 17:15 UTC, Geod24 commented
> I understand that this may not be the best solution, but @Geod24 @adamdruppe your comments are not constructive at all. Comments like "it's wrong", "it should be like this" without providing a rationale are not helpful at all. Could you maybe present your use cases so that we reach a consensus? I think that your use cases may have other solutions that do not require making the language more complex.

My comment was solely about the solution you provide, not the bug you are tackling. I can express it in more words, if you'd like:

The compiler should have as much static information as possible / convenient. Because with more static information, we can take better decisions: detect errors earlier, generate more efficient code / diagnostic, etc...
This PR, as I understand it, removes some static information (typed function => `void*`). A byproduct of this is that the compiler is not able to use this function (it doesn't even know it's a function). But this conflict with our goal to have as much static information as we can. So it's wrong because the fix is not at the right place. Preventing taking the address of it, on the other hand, doesn't have the same downside.

2023-02-14 17:34 UTC, RazvanN7 commented
@Geod24 I have implemented typing `&S.fun` as `void function(S*)`. I am putting the context pointer at the end of the parameter list as that is where the compiler puts it, however, there is one problematic case: variadic functions. In case of a variadic function, the context pointer is currently put before `...`, however, I am not sure where the compiler puts it in normal circumstances.

2023-02-14 17:37 UTC, RazvanN7 commented
With this change, I think that `delegate.funcptr` becomes useless as it was mainly use be assigned the address of some member function. Since we effectively changing the type of the address of a member function we are breaking all the code that uses funcptr that way.

2023-02-15 09:32 UTC, ibuclaw commented
>  I am putting the context pointer at the end of the parameter list as that is where the compiler puts it,

Wait what? Context pointer is the _first_ parameter.

2023-02-15 09:33 UTC, RazvanN7 commented
@ibuclaw That's how I implemented it at first, but then I noticed that I'm getting segfaults for functions that have more than 0 parameters.

2023-02-15 09:41 UTC, RazvanN7 commented
Initially, I put the context pointer in the type as being the first parameter, but then this example issued a segfault:

```d
  struct S
  { 
      int a;
      void fun(int _)
      {
          this.a = 1;
      }   
  }
  
  void main()
  {
      auto fp = &S.fun;
      S s;
      fp(&s, 2);
      import std.stdio;
      writeln(s.a);
   }
 ``` 

When I put the ctx pointer at the end, and called `fp(2, &s)` it worked. I deduced from here that the compiler generates code that thinks the context pointer is at the end of the parameter list.

2023-02-15 10:04 UTC, ibuclaw commented
@RazvanN7 looks like you're trying to do X86 ABI hacks in the front-end AST then.  What you're doing won't work - see for example https://github.com/dlang/dmd/pull/13590 and the decades of grief that caused us in order to get opCmp and opEquals working uniformly across all architectures.

Remember, X86 ABI pushes arguments RTL, contrary to every single other platform which pushes LTR.

2023-02-15 10:11 UTC, RazvanN7 commented
@ibuclaw Thanks for shedding some light on this. It seems that the frontend doesn't really have a way to express a function type for which the context pointer is provided by the user (other than delegates.funcptr).

2023-02-22 12:29 UTC, Bolpat commented
My two cents:

The first thing to consider is that `&S.f` is easily written with the intention of `&s.f` (with `s` an instance of `S`), thus making it an error provides indeed value. In simple cases, programmers can write out `function(ref S _this, …) => _this.f(…)` explicitly, but we can provide a mechanism for that in Phobos or via `__traits`, e.g. `__traits(explicitObjectParameter, S.f)`.

Assuming `&S.f` is not made a compile error:
* The instance parameter must be the first parameter. Everything else surprises programmers with experience in e.g. [Extension Methods in C#](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods) and [Explicit Object Parameters in C++](https://en.cppreference.com/w/cpp/language/member_functions#Explicit_object_parameter), which put the instance parameter first. It also needlessly complicates meta-programming, especially when sequencing the instance parameter before a variadic parameter (if any).
* The instance parameter should be what it is in a member function: For a `struct` or `union`, that is a `ref`erence, not a pointer. It has no business being `null` or having pointer arithmetic done to it. For a `class`, the instance parameter should be a class handle (which is sadly nullable in D).

The syntax `&S.f` can be a shorthand for `function(ref S _this, …) => _this.f(…)` (where `…` is the parameters of `f`), but it has the downside that the address might not be stable, i.e. might give different values when the pointer is converted to `size_t`.
If that is desired, D could automatically define them as module-level functions that correspond to non-static member functions, but take the object parameter explicitly. Those can be hidden or exposed for intentional use by regular programming. Exposing them has an interesting consequence:
The module `S` is in has a function `f` with the instance parameter as the first parameter. This would allow true UFCS: A member function can now be called as if it were a free function! For virtual class methods, this must forward to a member function call so overriding works.

I’d imagine the module-level function implementation as follows: For every aggregate type `T` defined in a module and every non-static member function `f` defined in `T` generate module-level `__T_f` with the same visibility and return type as `f`, and parameters are the instance parameter plus the parameters of `f`; also generate module-level `alias f = __T_f`.
The syntax `&S.f` becomes `&__S_f` (where `__S_f` is searched for in the module `S` is defined in). When multiple types `S1`, `S2`, … define a non-static member functions `f`, module-level `f` is an overload set spanning all these functions, but `&S1.f`, `&S2.f`, … already disambiguate by the first type, and target-type overload resolution is not needed for those that define exactly one overload.

2023-05-17 12:26 UTC, closed without merging