Fix Issue 23585 - Add bp relative symbols (frame-relative, see ntreh.…
dlang/dmd pull request #14746
Opened 2022-12-27 23:09 UTC by maxhaton

…d for apparently the only use) to local symbols during inlining.

2022-12-27 23:10 UTC, maxhaton commented
If it breaks something it'll have to be in the `break`

2022-12-28 02:46 UTC, thewilsonator reviewed
Are you able to verify without using phobos?

2022-12-28 02:46 UTC, thewilsonator commented on compiler/test/compilable/extra-files/inliner23585b.d
> +    import std.file : exists;
No std lib in the test suite

2022-12-28 03:32 UTC, maxhaton commented
I had a go and failed

2022-12-28 11:21 UTC, ibuclaw commented
> I had a go and failed

Try again. ;-)

2022-12-28 11:26 UTC, ibuclaw requested changes

2022-12-28 11:26 UTC, ibuclaw commented on compiler/test/compilable/inliner23585a.d
> +// COMPILED_IMPORTS: extra-files/inliner23585b.d
This is the wrong directive to use. What you want is `EXTRA_SOURCES`

2022-12-28 12:44 UTC, ibuclaw commented
Didn't #14730 fix the bug?

2022-12-28 14:18 UTC, maxhaton commented
I was still able to reproduce the bug locally, I think Razvan put the hack
in the wrong stack. Same reduction possivly though.

Slightly alarmijg that copying a tree is this difficult, deprecate -O.

On Wed, 28 Dec 2022, 12:45 Iain Buclaw, ***@***.***> wrote:

> Didn't #14730 <https://github.com/dlang/dmd/pull/14730> fix the bug?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dlang/dmd/pull/14746#issuecomment-1366625540>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABLI75BFTX7P6YY7UYF2EJ3WPQY4XANCNFSM6AAAAAATKY4Y34>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-30 14:56 UTC, maxhaton commented
Previous one did get I think, closing.

2022-12-30 14:56 UTC, closed without merging