frontend.d: unnecessary unittest
dlang/dmd pull request #14925
Opened 2023-02-27 18:35 UTC by WalterBright

Static asserts do not need to be in unittests.

2023-02-27 18:40 UTC, Geod24 requested changes, later dismissed
They don't need to, but it makes more sense to have such sanity check done only in unittest, as opposed to them being run whenever the binary is compiled.

2023-02-27 18:41 UTC, WalterBright commented
> They don't need to, but it makes more sense to have such sanity check done only in unittest, as opposed to them being run whenever the binary is compiled.

Static asserts are run at compile time. Why would this be a problem?

2023-02-27 18:43 UTC, Geod24 commented
As I said, it's a sanity check. Why would we compile code we don't need to compile, except to slow down compilation ?
In other words, what does this PR improve ?

2023-02-27 18:46 UTC, WalterBright commented
> what does this PR improve ?

1. removes pointless complexity
2. the check is always run instead of only in a separate unittest run
3. the check is computationally trivial
4. it emphasizes that initialization of the globals in dmd is not necessary to do the check

2023-03-01 07:16 UTC, PetarKirov approved these changes
If the static assert triggered an expensive CTFE call I would agree with @Geod24 that it should remain inside a unit test, but in this case it looks better without being wrapped in one

2023-03-01 20:53 UTC, merged