recognize Gnu Asm statements
dlang/dmd pull request #15007
Opened 2023-03-20 02:37 UTC by WalterBright

The difficulty is gnu asm statements appear with regularity in the various gnu system headers. ImportC doesn't recognize them and gives an incomprehensible error message when it sees them.

This PR recognizes gnu asm statements, and replaces them with an assert that reports:
```
core.exception.AssertError@test.c(8): Gnu Asm not supported - compile this function with gcc or clang
```
giving a file & line where the gnu asm was, and suggesting corrective action. It's a runtime assert, so is not a problem for the user unless the code is actually executed.

2023-03-20 05:50 UTC, ibuclaw requested changes
The frontend can compile gnu style asm statements in dmd iasmgcc though.

https://github.com/dlang/dmd/pull/14890

2023-03-21 08:38 UTC, RazvanN7 commented
@WalterBright since #14890 has been merged, I assume we can close both this and #15012 ?

2023-03-21 19:53 UTC, WalterBright commented
@RazvanN7 merge https://github.com/dlang/dmd/pull/15012

2023-03-21 19:54 UTC, WalterBright commented
superseded by https://github.com/dlang/dmd/pull/15012

2023-03-21 19:54 UTC, closed without merging

2023-03-22 10:18 UTC, ibuclaw commented
> I didn't know you had done this, good work! I made some requests in it, so it can replace this PR.

Thanks. I'm in no position to do anything for the next day or two. Please do smash this and the other PR together!

2023-03-22 10:18 UTC, ibuclaw commented
> I didn't know you had done this, good work! I made some requests in it, so it can replace this PR.

Thanks. I'm in no position to do anything for the next day or two. Please do smash this and the other PR together!