change ESCAPE from flag to bool
dlang/dmd pull request #15058
Opened 2023-03-31 04:42 UTC by WalterBright

not worth being a flag

2023-03-31 07:23 UTC, WalterBright commented
Simplified the array logic, too.

2023-03-31 08:09 UTC, RazvanN7 approved these changes

2023-03-31 08:12 UTC, RazvanN7 requested changes
Hang on! You are transforming a compile time constant into a field that is allocated. This makes `VisualCPPMangler` use more memory.

2023-03-31 11:12 UTC, dkorpel requested changes, later dismissed

2023-03-31 11:12 UTC, dkorpel commented on compiler/src/dmd/cppmanglewin.d
> +    bool ESCAPE;    // ESCAPE: toplevel const non-pointer types need a '$$C' escape in addition to a cv qualifier.
```suggestion
    bool escape;    // ESCAPE: toplevel const non-pointer types need a '$$C' escape in addition to a cv qualifier.
```
Variable field should be camelCase

2023-03-31 11:16 UTC, dkorpel commented
> This makes `VisualCPPMangler` use more memory.

It's stack allocated, subtracting the stack pointer a few more bytes is not going to make a difference.

2023-03-31 15:53 UTC, WalterBright commented
@RazvanN7 there are 5 bit flags, consuming 4 bytes, aligned on 8 bytes. Transforming them into 5 bools uses 5 bytes, aligned on 8 bytes. No difference in memory consumption. The bools also need less code to manipulate.

2023-03-31 16:07 UTC, RazvanN7 commented
Right, my point was that the enum does not allocate anything at run time. But anyway, as @dkorpel pointed out this is only stack allocated, so it doesn't matter.

2023-03-31 16:07 UTC, RazvanN7 approved these changes

2023-03-31 20:01 UTC, dkorpel commented on compiler/src/dmd/cppmanglewin.d
> +	IGNORE_CONST = false;
This is indented with tabs instead of spaces

2023-04-01 03:18 UTC, WalterBright commented on compiler/src/dmd/cppmanglewin.d
> +    bool ESCAPE;    // ESCAPE: toplevel const non-pointer types need a '$$C' escape in addition to a cv qualifier.
ok

2023-04-01 09:34 UTC, merged