change IS_DMC from bit flag to bool
dlang/dmd pull request #15057
Opened 2023-03-31 03:39 UTC by WalterBright

Having it as a bit flag is just pointless complexity. It won't save a meaningful amount of memory. The other bit flags need to be converted to bool as well.

2023-03-31 08:16 UTC, RazvanN7 commented
> It won't save a meaningful amount of memory

What do you mean? Right now it doesn't use any memory, whereas if you transform all of its fields into bools, you will end up with 5 extra bytes per instance. It does seem like there are not many instances of `VisualCPPMangler` created during a compilation cycle, however, I don't really see the benefit of this change, I don't see the usage of an `enum` as pointless complexity.

2023-03-31 11:17 UTC, dkorpel requested changes

2023-03-31 11:17 UTC, dkorpel commented on compiler/src/dmd/cppmanglewin.d
> +    bool IS_DMC;        // Digital Mars C++ mangling
```suggestion
    bool isDmc;        // Digital Mars C++ mangling
```
Variable field name should be camelCase

2023-03-31 11:22 UTC, dkorpel commented
> I don't see the usage of an enum as pointless complexity.

It's not the enum, it's packing multiple booleans into a single field, requiring the use of bitwise operators to read/write them instead of simple field access.

2023-04-01 01:04 UTC, WalterBright commented
Merged into https://github.com/dlang/dmd/pull/15058

2023-04-01 01:04 UTC, closed without merging