shortcut trivial CTFE expression evaluation
dlang/dmd pull request #15120
Opened 2023-04-19 20:25 UTC by WalterBright

Some testing showed a large percentage of calls were to evaluate integers.

2023-04-20 08:47 UTC, RazvanN7 commented on compiler/src/dmd/dinterpret.d
> +    if (e.isIntegerExp())
Also, we should probably delete the visitation method of `IntergerExp` in the `Interpret` visitor.

2023-04-20 17:22 UTC, dkorpel commented
> Some testing showed a large percentage of calls were to evaluate integers.

What code base did you test it on, and how much build time does this PR cut out of it?

2023-04-20 18:39 UTC, WalterBright commented on compiler/src/dmd/dinterpret.d
> +    if (e.isIntegerExp())
I first thought I'd see how this worked out before looking to extend it.

2023-04-20 18:44 UTC, WalterBright commented
I tested it on some random files. Nothing systematic. I don't have a good benchmark to try it on. Contrived CTFE benchmarks can be pretty misleading. It's mainly extending the shortcuts from ctfeInterpret() to apply to the leaves rather than just the root.

@RazvanN7 refactoring includes performance optimizations. There aren't semantic changes here.

2023-04-20 20:51 UTC, dkorpel commented on compiler/src/dmd/dinterpret.d
> +    if (e.isIntegerExp())
So how does it work out, what is the speed up?

2023-04-20 20:52 UTC, dkorpel requested changes
This adds cyclomatic complexity, while there's no evidence that this makes a measurable difference

2023-04-21 02:15 UTC, WalterBright commented
> This adds cyclomatic complexity,

No, there are no cycles added.

> while there's no evidence that this makes a measurable difference

Don't need to. I've done a lot of profiling of interpreter code in other projects. Adding special paths for trivial execution of very common cases wins.

2023-04-21 06:34 UTC, ibuclaw commented
I agree with @dkorpel, when I write it down, I don't see any improvement in compilation times at all, rather the marginal gain made from IntegerExp only gets shunted to a marginal loss for every other node - and that's making a generous assumption that integer literals appear in a compilation as frequently as every other kind of node.

2023-05-11 06:18 UTC, closed without merging