betterC: do not store variable in TLS
dlang/dmd pull request #15161
Opened 2023-05-02 03:23 UTC by ryuukk

Due to issues like this: https://issues.dlang.org/show_bug.cgi?id=20737

I think it's best to just don't store anything there until it's fixed, otherwise user get segfault that are hard to debug

I'd rather see a @tls for betterC

2023-05-02 04:06 UTC, maxhaton commented
As if you can't just write gshared?

2023-05-02 08:27 UTC, RazvanN7 commented
Could you provide a test case  so that we can understand what is the observable effect of this?

2023-05-02 09:09 UTC, dkorpel commented
> I think it's best to just don't store anything there until it's fixed, otherwise user get segfault that are hard to debug

I suggest making it an error to use TLS in betterC then, because this way you get hard to debug "why is my thread local variable being modified by other threads", and switching back once TLS with betterC is fixed will be a breaking change.

2023-05-02 11:44 UTC, Geod24 commented
1) Needs a test case;
2) Agreed that it should just result in an error rather than a silent change of semantic;

But going with 2 will make `betterC` even less usable.

2023-05-02 11:44 UTC, Geod24 requested changes
See above

2023-05-02 15:58 UTC, kinke commented
IIRC, this is a pure DMD backend bug for Windows MSVC targets only. So absolutely no need to change betterC semantics, or any other frontend change.

2023-05-02 19:49 UTC, maxhaton commented
> IIRC, this is a pure DMD backend bug for Windows MSVC targets only. So absolutely no need to change betterC semantics, or any other frontend change.

Exactly right.

2023-05-04 09:52 UTC, RazvanN7 commented
@ryuukk this is not the right approach at fixing the issue. As pointed out this is a backend bug. Are you willing to fix it?

2023-05-04 12:13 UTC, maxhaton commented
> @ryuukk this is not the right approach at fixing the issue. As pointed out this is a backend bug. Are you willing to fix it?

https://github.com/dlang/dmd/pull/15170

2023-05-04 12:16 UTC, closed without merging