fix Issue 18528 - dmd should deduplicate identical errors
dlang/dmd pull request #15306
Opened 2023-06-10 23:26 UTC by WalterBright

Reboot https://github.com/dlang/dmd/pull/15303 with different approach, hopefully much less disruptive.

2023-06-11 03:05 UTC, WalterBright commented
Still an amazing number of diffs.

2023-06-11 07:16 UTC, ibuclaw commented
I suppose you've already tried node-based suppression?

I _think_ the most common entrypoint for errors are the wrapper methods `e.error("I didn't pass semantic checks");`. Similarly, there's an `e.errors` boolean field that is set by many (but not all) nodes afte an error occurs.

Do we already refuse to emit errors/deprecation if the errors field is already set?

2023-06-12 00:35 UTC, WalterBright commented
The specific message for this bugzilla is:
```
/Users/timothee/git_clone/D/ggplotd/source/ggplotd/geom.d(117,24): Deprecation: module `ggplotd.aes` member hasAesField is not visible from module geom
/Users/timothee/git_clone/D/ggplotd/source/ggplotd/geom.d(117,24): Deprecation: module `ggplotd.aes` member hasAesField is not visible from module geom
```
is not so easy to deal with without adding complexity.

2023-06-12 06:12 UTC, ibuclaw commented
> > I suppose you've already tried node-based suppression?
> 
> A lot of that is done. The trouble is it is not a general solution, and I was looking for a general solution. But as this PR shows, I'm thinking I should look again at the node base solution, as this one is a bit too blunt.
> 
> Just adding the check to the `e.error` function won't work, as the supplemental messages also need to be suppressed.

Only supplemental messages relating to the same error? Other supplemental messages should be fine to emit. Back traces being one such example where it is desired to have the same line twice.

2023-06-12 09:15 UTC, ibuclaw commented
I don't see it scaling well to always wrap grouped errors up into an if statement - maybe a lambda?

2023-06-12 10:17 UTC, RazvanN7 requested changes
Thanks for taking care of this. A few notes:

- stop adding #line directives to test files.
- please delete the newly added extra lines in the test files.
- updating the failure tests can be done automatically by running ./AUTO_UPDATE = 1 ./run.d test (except for test files where there are multiple error sections)
- the current implementation is going to suppress some error messages when it shouldn't given that it takes only the location of the error message. This can already be observed in some of the modified test suite files. I assume there are other situations when we prune error messages when we shouldn't. Maybe a better way to do it is to the hash of the error message?

2023-06-12 10:17 UTC, RazvanN7 commented on compiler/test/compilable/depmsg.d
> +
Please delete these extra lines.

2023-06-12 10:17 UTC, RazvanN7 commented on compiler/test/compilable/ddoc10236b.d
> +
this change is unrelated to this PR

2023-06-12 10:17 UTC, RazvanN7 commented on compiler/test/compilable/ddoc10236.d
> +
this change is unrelated to this PR

2023-06-12 10:17 UTC, RazvanN7 commented on compiler/src/dmd/errors.d
> +            suppress = false;
The style guidelines dictate that if one of the branches has braces, the other one should too.

2023-06-12 10:17 UTC, RazvanN7 commented on compiler/test/compilable/sw_transition_complex.d
> +
undo

2023-06-12 10:17 UTC, RazvanN7 commented on compiler/test/compilable/test21514.d
> +
ditto

2023-06-12 10:17 UTC, RazvanN7 commented on compiler/test/compilable/test23097.d
> +
ditto

2023-06-12 10:17 UTC, RazvanN7 commented on compiler/test/fail_compilation/cpp_abi_tag.d
> -fail_compilation/cpp_abi_tag.d(114): Error: argument `3` to `@gnuAbiTag` cannot be empty
I don't think this message should be elided.

2023-06-12 10:17 UTC, RazvanN7 commented on compiler/test/fail_compilation/diag10319.d
> +#line 100
Please, stop adding #line directives. This makes reviewing the code much more difficult.

2023-07-03 02:51 UTC, WalterBright commented
Abandoning this as unworkable in favor of https://github.com/dlang/dmd/pull/15314 and https://github.com/dlang/dmd/pull/15312

2023-07-03 02:51 UTC, closed without merging