revert deprecation of body
dlang/dmd pull request #15379
Opened 2023-07-04 06:22 UTC by WalterBright

The code comment says it all:

"`body` was quite widely used"

And it doesn't actually hurt anything to leave it in.

2023-07-04 06:59 UTC, Herringway commented
It hurts the planned ability to free the body keyword for use as a name.

It also hurts trust in the language. It's been two years since the first release with the deprecation. People (myself included) have already made all the necessary changes. What else will be undone? Can we trust any of the other DIPs to remain implemented? I do not like this uncertainty.

2023-07-04 07:16 UTC, thewilsonator requested changes, later dismissed
as noted the whole point of removing `body` as a keyword is so that is can be used as a variable name, deprecation is the first step towards that and we shouldn't be undoing that.

2023-07-04 07:45 UTC, WalterBright commented
Using `body` as a regular identifier is already allowed. This reversion will not break that. `body` is a contextual keyword, not an actual keyword.

> Can we trust any of the other DIPs to remain implemented?

We don't want to break those, either. The whole point of this initiative is to stop breaking peoples' existing code.

2023-07-04 08:16 UTC, ibuclaw commented
> And it doesn't actually hurt anything to leave it in.

It hurts those who would like to have a variable named `body`?

For example, HTML content tends to have a body.

2023-07-04 08:34 UTC, WalterBright commented
> When did that happen?

I don't know, but the proof is here: https://github.com/dlang/dmd/pull/15379/files#diff-197670928b0e5ec0254c1edd8b3588469b86ac670c013a2d0d42426a6d36b47eR719

2023-07-04 13:34 UTC, adamdruppe commented
Yes, this is how it should have been done in the first place.

2023-07-05 11:11 UTC, dkorpel approved these changes

2023-07-06 02:09 UTC, merged