make toChars() nothrow
dlang/dmd pull request #15521
Opened 2023-08-08 21:48 UTC by WalterBright

Although nothing in DMD throws exceptions, the front end functions are all `may throw`. Since it also relies on RAII, this is costly. Converting it all to `nothrow` at once is a tremendous undertaking, so let's just do it bit by bit, starting with `toChars()`.

Note that changing `RootObject.toChars` to `nothrow` will cause every `toChars` to inherit the `nothrow`.

2023-08-08 22:11 UTC, Herringway commented
Why do these changes catch all `Throwable`s instead of just `Exception`?

2023-08-08 22:18 UTC, WalterBright commented
Dscanner prints:
```
/buildkite/builds/zaphod-6/dlang/dmd/dmd/compiler/src/dmd/init.d(66:16)[warn]: Catching Error or Throwable is almost always a bad idea.
```
This warning does not appear in the documentation https://code.dlang.org/packages/dscanner/0.4.0-beta.3 and does not appear in https://github.com/dlang/dmd/blob/master/compiler/src/.dscanner.ini

How do I disable this check?

2023-08-08 22:20 UTC, WalterBright commented
@Herringway The `Throwable` exceptions are the only ones that matter to RAII.

2023-08-08 22:30 UTC, Herringway commented
> @Herringway The `Throwable` exceptions are the only ones that matter to RAII.

I think I'm missing something here. Only `Exception` needs to be caught to satisfy `nothrow`, not other `Throwable`s...

2023-08-09 00:01 UTC, WalterBright commented
Throwable is enough for the compiler to let it pass `nothrow`.

2023-08-09 00:25 UTC, SixthDot commented
> How do I disable this check?

set it to disable [here](https://github.com/dlang/dmd/blob/master/compiler/src/.dscanner.ini#L9)

2023-08-09 00:35 UTC, SixthDot commented
Then if you still get warnings that would mean that someone forgot to update a path when druntime was merged and dmd sources put in a subfolder.

2023-08-09 01:08 UTC, WalterBright commented
@SixthDot thanks! I totally missed that reading the file. I fixed its description, too, to match the message.

2023-08-09 01:32 UTC, Herringway commented
> Throwable is enough for the compiler to let it pass `nothrow`.

I'm definitely missing something here. Catching `Exception` is enough to satisfy `nothrow`. Catching more than that is considered [unsafe](https://dlang.org/library/object/throwable.html). This would attempt to swallow assertions and other `Error`s as well.

2023-08-09 02:25 UTC, WalterBright commented
Throwable is derived from Exception. asserts can throw an Exception. Exceptions are fatal errors and do not participate in RAII. Nothrow means no RAII.

2023-08-09 02:44 UTC, Herringway commented
> Throwable is derived from Exception. asserts can throw an Exception. Exceptions are fatal errors and do not participate in RAII. Nothrow means no RAII.

[`Throwable`](https://dlang.org/library/object/throwable.html) is the base class. [`Exception`](https://dlang.org/library/object/exception.html) and [`Error`](https://dlang.org/library/object/error.html) are both derived from it. asserts and other unrecoverable problems throw `Error`, not `Exception`. `Exception` is used for things that are meant to be recoverable. Catching `Throwable` means you are catching everything that can possibly be thrown. This has been the case since `Throwable` was introduced by a big exception refactor almost 15 years ago.

2023-08-09 02:54 UTC, WalterBright commented
@Herringway you're right. I was wrong.

2023-08-09 16:17 UTC, ibuclaw requested changes
This approach isn't going to work when compiling with exceptions turned off globally - and indeed, when I tested the change, building the compiler fails.

https://github.com/dlang/dmd/blob/0ceaeb9219ee2c09cd8c39d31ed1b70d6e19dd59/compiler/src/dmd/statementsem.d#L3282-L3286

2023-08-09 17:04 UTC, WalterBright commented
@ibuclaw I don't follow. useExceptions is only set to false when compiling with -betterC, and dmd isn't built with -betterC. Also, the try-catch is only a temporary change so `nothrow` can be done incrementally, making for easier review.

2023-08-09 17:38 UTC, ibuclaw commented
> @ibuclaw I don't follow. useExceptions is only set to false when compiling with -betterC, and dmd isn't built with -betterC. Also, the try-catch is only a temporary change so `nothrow` can be done incrementally, making for easier review.

Why would it be only set when compiling with `-betterC`? It's a feature flag independent of betterC itself.

https://github.com/gcc-mirror/gcc/blob/63663e4e69527b308687c63bacb0cc038b386593/gcc/d/d-lang.cc#L505-L507

The front-end is built with exceptions turned off in gdc, so the big bang approach of marking everything as `nothrow` will work, but when incrementally done, we should look elsewhere to fine the leaves at the bottom, or functions with least number of cross dependencies so it can better bubble up without adding in exception handling.

2023-08-10 17:48 UTC, WalterBright commented
> we should look elsewhere to fine the leaves at the bottom, or functions with least number of cross dependencies so it can better bubble up without adding in exception handling.

I've done what I could with that. The trouble is the bulk is circular in their dependencies. The use of the Visitor class, for example.

2023-08-10 17:49 UTC, WalterBright commented
> Why would it be only set when compiling with -betterC? It's a feature flag independent of betterC itself.

In dmd it is not an independent feature flag. It's only set with -betterC.

2023-08-13 21:50 UTC, WalterBright commented
https://github.com/dlang/dmd/pull/15536

2023-08-18 04:39 UTC, WalterBright commented
I'm going to abandon this as the `-nothrow` switch was merged.

2023-08-18 04:39 UTC, closed without merging