Deprecate the DRT Windows-specific versions of ODBC.
dlang/dmd pull request #15560
Opened 2023-08-28 03:42 UTC by LightBender

ODBC is supported on all major OSes and should not be limited to Windows in D. Furthermore, Database access interfaces are never appropriate in the Runtime.

Related to and supersedes: https://github.com/dlang/phobos/pull/8748

2023-08-28 04:04 UTC, rikkimax commented
sqlext.h:

> // Contents:        This is the include for applications using the Microsoft SQL Extensions

So no, we can't get rid of it. It needs to be part of WinAPI.

2023-08-28 04:11 UTC, LightBender commented
@rikkimax I am working on a companion PR that puts this back in Phobos where it was before. I just need to clean up some of the references to other windows specific files that are pulled in simply for some type aliases first. There really is no need to import those files as all the types aliased can be recreated specifically for ODBC while maintaining ABI compatibility. ODBC is available on all major OSes and we need to support it on all major OSes. DConf week is my window to rectify this issue.
I'll link the PR when it's posted.

2023-08-29 09:54 UTC, LightBender commented
@rikkimax Here is the PR that adds this back to Phobos.

2023-08-29 11:08 UTC, CyberShadow requested changes, later dismissed
Sorry, I don't understand how this could be a good direction that we should go in.

Windows API bindings should stay in Druntime.

More generally, OS API bindings should be in Druntime (or maybe Deimos for the more specialized ones, but if Phobos needs them, then they should be in Druntime).

OS API bindings should definitely not be in Phobos.

2023-08-29 11:12 UTC, CyberShadow commented
If there are parts of the Windows API that are actually suitable for all platforms, then I think it would be OK to copy them. We could also selectively remove `version (Windows):` from these modules, and create modules with non-Windows-specific module names that alias to or selectively import from the Windows API headers.

There are some modules in the `core.sys.windows` package that are indeed not part of the Windows API, but are helper modules which implement some code needed for Druntime to interface with various aspects of the Windows API. However, I don't think the modules changed in this PR are ones of these; these are simply mechanical translations of the MinGW C headers. We should not move these around on a one-by-one basis; it is much more valuable for them to have the same predictable location as they are in the Windows API C header hierarchy.

In short, whatever the final goal is, I don't think this is a good way towards it.

2023-08-29 13:21 UTC, LightBender commented
@CyberShadow Ok, there are a few points to address here. 

The first appears to be an assumption that ODBC is Windows specific. It is not. ODBC is an open standard that is available on all major operating systems and ODBC drivers are provided by nearly all SQL based database vendors. This includes, but is not limited to: MariaDB, PostgreSQL, Redshift, etc. ODBC is categorically _not_ a Windows API that is suitable to non-Windows platforms and treating it as such is how we got here. The fact that the D bindings came from MinGW is likewise wholly irrelevant to the discussion. The MinGW header translations (ODBC 3.8) are presently out of date and ODBC 4.0 reference headers have since been supplied by Microsoft here: https://github.com/microsoft/ODBC-Specification/

Second. ODBC is _not_ an OS-level API and therefore has no business being in DRT. To my knowledge, no operating system ships with ODBC by default or as part of it's OS API surface. I have worked with ODBC on Windows and Linux and in both cases I had install a package prior to being able to access ODBC. 

I suspect that the ODBC headers were initially place in etc.c.odbc by somebody who knew the above and correctly placed them in Phobos. Then later somebody else came in and realized that these are *also* in the MinGW translations and decided that we should just use those. The problem is that the mechanical translations of MinGW (mostly correctly) assume that MinGW is Windows only. But because ODBC is *not* a Windows-only feature, using the mechanical translations introduced a bug for non-Windows platforms. That an API merely originates from the MinGW translation does not guarantee that the API is Windows-only and that is a faulty assumption on the part of the maintainers that forces an incorrect version constraint on the code as an unintended consequence.

If ODBC was a) Windows-only and/or b) even an OS level API at all, then I would agree with you, but as neither of those cases are true, then Phobos is the correct location and version(Windows) is incorrectly applied.

2023-08-29 13:28 UTC, CyberShadow commented
I do not (and did not intend to) disagree with everything you said except:

> then Phobos is the correct location

The correct location is the current location for the reasons that I've already explained. Moving things around will complicate updating to a newer version of the MinGW headers.

So, yes, feel free to selectively remove `version (Windows):` from select headers as needed.

If at a certain point the high-level Phobos implementation of ODBC will need things that are missing or inadequately specified in the MinGW headers, then a separate translation can be added (also to Druntime, IMO) from a better source.

2023-08-29 13:52 UTC, CyberShadow commented
As for the reason why Druntime and not Phobos... whether they are OS bindings or not is not relevant I think. Druntime is for things which are not opinionated, and that any standard library may use. So hypothetically if Tango still existed today and wanted to provide an opinionated high-level ODBC wrapper using its own approach, it would still be able to benefit from the same bindings as Druntime, because there isn't really more than one way to wrap a C API in D. It's also the motivation for having a centralized project for other bindings, [Deimos](https://wiki.dlang.org/Deimos).

2023-08-29 16:01 UTC, thewilsonator commented
So ro recap:
* ODBC version is out of date
* OBDC is based off of MinGW headers
* MinGW headers are (translated as?) Windows only.
* ODBC is not a Windows only thing, and will get reset as windows only by any reconversion from minGW headers 
* this module should be moved somewhere, `etc.c` or somewhere else in druntime

Decisions to be made: where should this be moved to?
it is already in `etc.c` albeit scheduled to be removed due to expiring deprecation (in favour of the module this PR seeks to deprecate). It shouldn't remain in `core.windows` as it is neither specific to windows nor an OS specific API.

2023-08-29 16:06 UTC, thewilsonator commented
(also @CyberShadow  i note that `ae` is broken on BuildKite, complaining that deprecated modules are deprecated)

2023-08-29 16:11 UTC, CyberShadow commented
> And every time the translations are updated we have to remember to remove the version specifier. No matter what, you're introducing a special case, either we special case removing the ODBC headers from translation, or we special case removing the version specifier from the translated files. Both cases result in a manual "checklist" item that has to be checked on a process that is run infrequently at best.

Well, ideally, we wouldn't have `version(Windows):` at all. The reason we have it is limitations of linkers and our own problems with ModuleInfo causing bloat for non-Windows platforms.

I vehemently disagree that adding/removing a `version(Windows):` line is anywhere close to being equivalent to moving the files to an entirely different Git repository!

> But interestingly, if we did that, ODBC would disappear because ODBC is not part of the Windows API surface.

But the Windows SDK includes `sql.h` etc.?

> ODBC's present location in core.sys.windows is an artifact of the MinGW translations,

I think most modules (the ones coming from MinGW) probably should have `mingw` in the name (and then have a `windows` package which publicly imports them). That way, if there was ever a need to use a header file that did not come to MinGW, it could be added without causing a mess in terms of what came from where and how one would update it.

> there is nowhere to actually put non-OS specific library interfaces in the current module structure

The `etc` package exists in Druntime too. We have not been paying much attention to having a consistent structure, but putting them in `etc.` or `etc.c.` would be fine, regardless of whether it's in Phobos or Druntime. As to whether it should be in Phobos or Druntime, we have also not been paying a lot of attention to that, because the goal of allowing multiple "standard" libraries was never fully realized. Anyway, that's a separate and relatively unimportant point compared to the argument at hand (moving MinGW translations out of the `core.sys.windows` package).

> And this makes sense because database access is always a Standard Library feature, it's never a Runtime feature.

OK, this is a fair argument.

> If you want to make the argument that the entire etc.* space in Phobos should be in DRT

I think that would also be fine, depending on how one would be inclined to define what Druntime is, and what would personally make the most sense to me (ignoring the cost of actually moving these).

> the most logical place for ODBC is in Phobos with the rest of the SQL interface libraries.

I think it would be perfectly fine for there to be modern ODBC bindings (based on Microsoft's GitHub repo) in Phobos (or Druntime) under the `etc.` package, alongside from the MinGW translations in the `core.sys.windows` package. These originate from different sources and the process of keeping them up to date is different. I think that, unless special attention was paid to maintain compatibility of the D bindings, a from-scratch translation of any C bindings will almost certainly introduce breaking changes compared to a different translation of an older version of the same bindings, so having the new ones in a new, separate namespace would then be a positive. In this case, it would be sufficient to discourage (in the documentation) the use of the older MinGW headers, instead of deprecating and outright removing them.

> Additionally, whether somebody has to import the bindings from Phobos or DRT is irrelevant because even they don't use Phobos, importing library interfaces does not mean they are pulling in Phobos itself.

If only that would be true in practice... unfortunately, we are very, very far from "pay for what you use" in D.

> Decisions to be made: where should this be moved to?

I say, go ahead and add the new bindings in Phobos (under `etc.c`); deprecating the MinGW ones doesn't immediately solve anything and I think it should not block anything.

> also @CyberShadow i note that `ae` is broken on BuildKite

Ah, thanks for the ping, I'll have a look! (Looks like a segfault in a unit test...)

2023-08-29 22:46 UTC, thewilsonator commented
Thanks for the update, will let Walter know tomorrow.

2023-08-31 10:57 UTC, LightBender commented
> I think it would be perfectly fine for there to be modern ODBC bindings (based on Microsoft's GitHub repo) in Phobos (or Druntime) under the `etc.` package, alongside from the MinGW translations in the `core.sys.windows` package. These originate from different sources and the process of keeping them up to date is different. I think that, unless special attention was paid to maintain compatibility of the D bindings, a from-scratch translation of any C bindings will almost certainly introduce breaking changes compared to a different translation of an older version of the same bindings, so having the new ones in a new, separate namespace would then be a positive. In this case, it would be sufficient to discourage (in the documentation) the use of the older MinGW headers, instead of deprecating and outright removing them.

This is a reasonable compromise and it makes practical sense. I've removed the deprecation labels and modified the documentation notes to reflect this.

I actually I have an ImportC based version of the ODBC 4.0 bindings ready to go, expect for this bug in ImportC: https://issues.dlang.org/show_bug.cgi?id=24121

2023-08-31 13:29 UTC, thewilsonator approved these changes
Phobos is now in.

2023-08-31 13:29 UTC, merged

2023-09-01 09:32 UTC, ibuclaw commented
> OS API bindings should definitely not be in Phobos.
> 

+100

The only good C bindings in Phobos are those behind `package(std)`.