fix Issue 24130 - ImportC: Windows headers use inline asm with differ…
dlang/dmd pull request #15595
Opened 2023-09-09 04:35 UTC by WalterBright

…ent syntax

Microsoft inline asm looks like this:
```
    __asm    {
        mov     ecx, ShiftCount
        mov     eax, dword ptr [Value]
        mov     edx, dword ptr [Value+4]
        shrd    eax, edx, cl
        shr     edx, cl
    }
```
Look ma, no semicolons. ImportC's inline asm wants semicolons. Microsoft uses generic C code instead when `_M_CEE_PURE` is set, so we set it, too. The other macros Microsoft uses for generic C code look rather more dangerous to use:
```
#if defined(MIDL_PASS) || defined(RC_INVOKED) || defined(_M_CEE_PURE) \
    || defined(_68K_) || defined(_MPPC_) \
    || defined(_M_IA64) || defined(_M_AMD64) || defined(_M_ARM) || defined(_M_ARM64) \
    || defined(_M_HYBRID_X86_ARM64)
```

2023-09-09 04:45 UTC, WalterBright commented
Now I get:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\vadefs.h(70): Error: no type-specifier for declarator
```
Of course, I don't have that particular vadefs.h so I don't know what is on line 70. Sigh. But evidently, _M_CEE_PURE is going down some nutburger path. Not sure what to do here.

2023-09-09 14:45 UTC, thewilsonator approved these changes

2023-09-10 06:05 UTC, WalterBright commented
Decided to try parsing Microsoft asm syntax.

2023-09-10 08:02 UTC, WalterBright commented
Hmm, how do I disable the omf platform from running?

2023-09-10 19:43 UTC, WalterBright commented
> how do I disable the omf platform from running?

The test runner apparently cannot do this. But I found another way...

2023-09-11 01:24 UTC, merged

2023-09-11 06:06 UTC, ibuclaw requested changes
See comments, I see regressions and breaking downstream compilers.

2023-09-11 06:06 UTC, ibuclaw commented on compiler/src/dmd/dmodule.d
> +            global.compileEnv.masm = target.os == Target.OS.Windows && !target.omfobj; // Microsoft inline assembler format
... platform-specific global variables that gdc (and ldc?) don't define or set.

2023-09-11 06:06 UTC, ibuclaw commented on compiler/src/dmd/parse.d
>              case TOK.semicolon:
This looks like it unintentionally bleeds into D code parser. Did you forget an `if (endOfLine) { ... }`?

2023-09-11 06:06 UTC, ibuclaw commented on compiler/src/dmd/parse.d
> +                    as.caseSensitive = !endOfLine;
These two variables mean different things, why is one setting the other?