Revert "[dtoh] append _ to C keywords in addition to C++ keywords"
dlang/dmd pull request #15672
Opened 2023-10-11 18:13 UTC by ibuclaw

Reverts dlang/dmd#15667

2023-10-11 23:13 UTC, thewilsonator requested changes
`clang` thinks otherwise:
```
/Users/nicholaswilson/d/ldc/ldc/./dmd/frontend.h:1805:5: error: expected identifier
    _Alignas = 205u,
    ^
/Users/nicholaswilson/d/ldc/ldc/./dmd/frontend.h:1806:5: error: expected identifier
    _Alignof = 206u,
    ^
/Users/nicholaswilson/d/ldc/ldc/./dmd/frontend.h:1807:5: error: expected identifier
    _Atomic = 207u,
    ^
/Users/nicholaswilson/d/ldc/ldc/./dmd/frontend.h:1810:5: error: expected identifier
    _Generic = 210u,
    ^
/Users/nicholaswilson/d/ldc/ldc/./dmd/frontend.h:1811:5: error: expected identifier
    _Imaginary = 211u,
    ^
/Users/nicholaswilson/d/ldc/ldc/./dmd/frontend.h:1812:5: error: expected identifier
    _Noreturn = 212u,
    ^
/Users/nicholaswilson/d/ldc/ldc/./dmd/frontend.h:1813:5: error: expected identifier
    _Static_assert = 213u,
    ^
/Users/nicholaswilson/d/ldc/ldc/./dmd/frontend.h:1814:5: error: expected identifier
    _Thread_local = 214u,
```
also change your godbolt compiler to clang and your example fails.

2023-10-12 06:32 UTC, ibuclaw commented
> clang thinks otherwise:

What a rubbish compiler clang is.

2023-10-12 12:58 UTC, thewilsonator commented
It is what it is.

2023-10-12 16:02 UTC, PetarKirov commented
So, @ibuclaw ok to close this PR?

2023-10-12 18:33 UTC, ibuclaw commented
Well, not everything added here is really problematic.

https://godbolt.org/z/ePfjGofYE

Also, someone should raise a bug against clang not being able to compile valid C++.

2023-10-19 04:27 UTC, closed without merging