split off expressionutil.d from expression.d
dlang/dmd pull request #15680
Opened 2023-10-14 01:47 UTC by WalterBright

This is a crude cut&paste job to move the non-AST code from expression.d to expressionutil.d. I'll save the finesse for a later PR. The code hasn't changed at all, it's just moved.

Moving this direction was a request from Luis, and it was already in my queue of things to do.

2023-10-14 23:33 UTC, thewilsonator requested changes
I don't love this (we need less files, or better organised files), but what concerns me is this file isn't either clearly AST nor is it semantic. It's _mostly_ semantic with a few misc function and other definitions:

As a start, could you please (preferably as a separate PR) move those functions that should obviously be private to their respective modules and delete the one used function.

2023-10-14 23:33 UTC, thewilsonator commented on compiler/src/dmd/expressionutil.d
> +bool RealIdentical(real_t x1, real_t x2) @safe
I feel this should be a final (private static) member of `RealExp` as it is only used by RealExp and ComplexExp

2023-10-14 23:33 UTC, thewilsonator commented on compiler/src/dmd/expressionutil.d
> +bool isDotOpDispatch(Expression e)
this function appears completely unused.

2023-10-14 23:33 UTC, thewilsonator commented on compiler/src/dmd/expressionutil.d
> +TupleDeclaration isAliasThisTuple(Expression e)
this has a single use in `dsymbolsem.d`, it should be a private function there

2023-10-14 23:33 UTC, thewilsonator commented on compiler/src/dmd/expressionutil.d
> +Expression valueNoDtor(Expression e)
this is only used in `statementsem.d` it should be private there

2023-10-14 23:33 UTC, thewilsonator commented on compiler/src/dmd/expressionutil.d
> +VarDeclaration expToVariable(Expression e)
this s only used in `escape.d` it should be a private function there

2023-10-15 04:11 UTC, WalterBright commented on compiler/src/dmd/dmodule.d
> -	auto loc = mod.getLoc();
`error` wants a ref argument, not a value.

2023-10-15 04:11 UTC, WalterBright commented on compiler/src/dmd/dtemplate.d
> +                    auto td = sc.tinst.tempdecl;
Before I check in, I convert tabs to spaces. Sometimes it catches stray tabs in other files.

2023-10-15 04:19 UTC, WalterBright commented
I was unclear about the purpose of this. It's not to move the free functions into other files. It's about moving the **AST** into another file. The confusing part is I wanted to name the file the AST was moved to "expression.d" to keep consistency with "statement.d", etc.

Putting it in its own file is a move towards combining the Expression AST with the one from astbase.d, which will make dmd-as-library a much more tractable problem.

While your suggestions are good, they are more suitable for follow-on. Since this PR is rather tectonic, to make it reviewable I restricted it to being a cut&paste job as much as possible.

2023-10-15 09:07 UTC, thewilsonator commented on compiler/src/dmd/expressionutil.d
> +bool isDotOpDispatch(Expression e)
#15685

2023-10-15 09:07 UTC, thewilsonator commented on compiler/src/dmd/expressionutil.d
> +TupleDeclaration isAliasThisTuple(Expression e)
#15686

2023-10-15 09:12 UTC, thewilsonator commented on compiler/src/dmd/expressionutil.d
> +Expression valueNoDtor(Expression e)
#15687

2023-10-15 09:16 UTC, thewilsonator commented
> While your suggestions are good, they are more suitable for follow-on.

On the contrary, given the large volume of stuff touched by this PR that should go elsewhere it is not (yet) obvious that a new file should be created. Until such a time as DMD is packaged, adding files willy-nilly is not something I approve of. Once all the other PRs I have created for this have been merged and if there is still suff left over that it is unclear where it should go, then we should consider adding a new file.

2023-10-15 09:20 UTC, thewilsonator commented on compiler/src/dmd/expressionutil.d
> +VarDeclaration expToVariable(Expression e)
#15688

2023-10-15 09:25 UTC, thewilsonator commented on compiler/src/dmd/expressionutil.d
> +bool isNeedThisScope(Scope* sc, Declaration d)
#15689

2023-10-15 09:29 UTC, thewilsonator commented on compiler/src/dmd/expressionutil.d
> +bool RealIdentical(real_t x1, real_t x2) @safe
#15690

2023-10-15 17:36 UTC, WalterBright commented
Putting the Expression AST in its own module is central to merging it with astbase's implementation, and moving forward to D as a library. I don't see another way forward.

2023-10-17 11:32 UTC, RazvanN7 commented on compiler/src/dmd/expressionutil.d
> +extern(D) Modifiable checkModifiable(Expression exp, Scope* sc, ModifyFlags flag = ModifyFlags.none)
With this one I agree that its place is in `expressionsem.d`

2023-10-17 11:35 UTC, RazvanN7 commented
> Putting the Expression AST in its own module is central to merging it with astbase's implementation, and moving forward to D as a library. I don't see another way forward.

Yes, to that end we have `expression.d` which should be trimmed to have only the Expression AST and some helper methods that are usable at parse time and everything that requires semantic information (e.g. functions that requires `import expressionsem;` or `import *sem;`) should be moved to their corresponding semantic file. I don't see the point in creating another file called `expressionutil.d`

2023-10-17 11:36 UTC, RazvanN7 commented
To be clear, at the end of the process, `expression.d` should only contain imports to other AST files and should not contain anything that directly or indirectly imports semantic files.

2023-11-13 05:58 UTC, thewilsonator commented
Closing as much of this has been done to move to `expressionsem.d` and other files by PRs from Razvan and myself and this has a large set of merge conflicts.

2023-11-13 05:58 UTC, closed without merging