expression.Expression : delete implicitConvTo shell function + modify usage site + update C++ headers
dlang/dmd pull request #15763
Opened 2023-10-31 12:43 UTC by RazvanN7

This is part of the effort of pulling out semantic out of expression. After this PR, a follow up will be to move the Expression.toUTF8  member function and we can get rid of importing module dcast.

cc @ibuclaw + @kinke is this function really used by GDC and LDC or could we leave it extern(D)?

2023-10-31 12:47 UTC, thewilsonator commented
`implicitConvTo` is unused by LDC

2023-10-31 12:51 UTC, dkorpel approved these changes

2023-10-31 13:41 UTC, ibuclaw requested changes, later dismissed
Used by gdc
1. Let middle end know if two types are compatible according to D language rules.
2. Issue errors with invalid use of va_list (eg: `this(va_list v) { this.ap = v; }`
3. Issue warnings about mismatched intrinsics (eg: `extern(C) double tan();`

2023-10-31 14:00 UTC, thewilsonator commented
> Used by gdc

It is not removed by this PR, just moved to a free function

2023-10-31 14:34 UTC, RazvanN7 commented
@ibuclaw currently the function is still in the headers, but it calls the underlying one from dcast.d

2023-11-01 09:50 UTC, RazvanN7 commented
Rebased and updated `expression.d

2023-11-01 10:05 UTC, RazvanN7 commented
@thewilsonator Note that gdc code still needs to be update as C++ does not have UFCS.

2023-11-01 10:40 UTC, merged