Pull toLvalue out of expression.d
dlang/dmd pull request #15770
Opened 2023-11-01 18:50 UTC by RazvanN7

The idea is to break the dependency on dscope. Follow-up PRs are in the pipeline, but this one is probably the largest.

2023-11-01 19:16 UTC, ibuclaw requested changes, later dismissed
Please wait for stable->master merge (#15637).

2023-11-02 12:40 UTC, RazvanN7 commented
Rebased and fixed conflicts. I think this is ready to go.

2023-11-02 13:59 UTC, thewilsonator approved these changes

2023-11-02 14:01 UTC, thewilsonator commented
small diff in frontend.h needed
```diff
diff --git a/home/circleci/dmd/compiler/src/dmd/frontend.h b/home/circleci/dmd/generated/linux/release/64/frontend.h
index a9731c3cfa..484ae1e3e0 100644
--- a/home/circleci/dmd/compiler/src/dmd/frontend.h
+++ b/home/circleci/dmd/generated/linux/release/64/frontend.h
@@ -7115,14 +7115,13 @@ public:
     ThisExp(const Loc& loc, const EXP tok);
     ThisExp* syntaxCopy() override;
     Optional<bool > toBool() override;
-    bool isLvalue() override;
+    bool isLvalue() final override;
     void accept(Visitor* v) override;
 };
 
 class SuperExp final : public ThisExp
 {
 public:
-    bool isLvalue() override;
     void accept(Visitor* v) override;
 };
```

2023-11-02 16:44 UTC, merged