Revert "Pull out check* from expression.Expression + move them to expressionsem + make most of them private (#15775)"
dlang/dmd pull request #15853
Opened 2023-11-22 19:43 UTC by ibuclaw

This reverts commit 9266f92fe5d3499c9f7345978aacd3775c1a21a3.

2023-11-22 21:30 UTC, thewilsonator submitted a review, later dismissed
You've put a GDC tag on it this time, which is better than nothing, but I'd still like an explanation as to why this is necessary, considering that this undies progress of moving stuff out of AST and into sema. Again I suspect that the appropriate course of action here is to make this work not to  revert it.

_Please do not merge this without a satisfactory explanation_.

2023-11-23 06:51 UTC, ibuclaw commented
```
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable4growMFNaNbZv':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:310: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toStringMxFNaNbNiNjZAxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable10allocValueMFNaNbMAxaC3dmd5mtype4TypeZk':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:268: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue7lstringMFNaNbNiNjZPa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:269: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue7lstringMFNaNbNiNjZPa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable4growMFNaNbZv':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:310: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toStringMxFNaNbNiNjZAxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable10allocValueMFNaNbMAxaC3dmd5mtype4TypeZk':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:268: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue7lstringMFNaNbNiNjZPa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:269: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue7lstringMFNaNbNiNjZPa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable4growMFNaNbZv':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:310: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toStringMxFNaNbNiNjZAxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable10allocValueMFNaNbMAxaC3dmd5mtype4TypeZk':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:268: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue7lstringMFNaNbNiNjZPa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:269: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue7lstringMFNaNbNiNjZPa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable4growMFNaNbZv':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:310: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toStringMxFNaNbNiNjZAxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable10allocValueMFNaNbMAxaC3dmd5mtype4TypeZk':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:268: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue7lstringMFNaNbNiNjZPa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:269: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue7lstringMFNaNbNiNjZPa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable4growMFNaNbZv':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:310: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toStringMxFNaNbNiNjZAxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable8findSlotMxFNaNbNimMAxaZm':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: /build/gcc-trunk/gcc/d/dmd/root/stringtable.d:292: undefined reference to `_D3dmd4root11stringtable34__T11StringValueTC3dmd5mtype4TypeZ11StringValue8toDcharsMxFNaNbNiNjZPxa'
/usr/bin/ld: d/func.o: in function `_D3dmd4root11stringtable34__T11StringTableTC3dmd5mtype4TypeZ11StringTable10allocValueMFNaNbMAxaC3dmd5mtype4TypeZk':
/build/gcc-trunk/gcc/d/dmd/root/stringtable.d:268: undefined reference to `_D3dmd4root11s [...]

2023-11-23 06:56 UTC, ibuclaw commented
1. Don't move huge swaths of functions and their dependencies around. Move them one at a time so these can be easily bisected and reverted as-needed.
2. Don't add new global imports, use selective imports at function level.

2023-11-23 09:34 UTC, RazvanN7 commented
If we are going to ever pull out semantic routines from AST nodes then most likely this will require some collaboration from your side. Simply reverting this and posting the linker errors that have nothing to do with the functions that are being moved is not enabling me to fix this in any way.

I don't see how moving some extern(D) functions affects gdc compilation.

2023-11-23 10:00 UTC, ibuclaw commented
> If we are going to ever pull out semantic routines from AST nodes then most likely this will require some collaboration from your side. Simply reverting this and posting the linker errors that have nothing to do with the functions that are being moved is not enabling me to fix this in any way.
> 
> I don't see how moving some extern(D) functions affects gdc compilation. 

You're doing more than moving functions though, you are changing the module dependencies.

2023-11-23 10:04 UTC, RazvanN7 commented
> You're doing more than moving functions though, you are changing the module dependencies.

Indeed, that is expected when one function is moved from one module to another. Some modules used to depend indirectly on other modules and after the refactoring the dependency becomes more clear.

2023-11-23 11:41 UTC, ibuclaw commented
> > You're doing more than moving functions though, you are changing the module dependencies.
> 
> Indeed, that is expected when one function is moved from one module to another. Some modules used to depend indirectly on other modules and after the refactoring the dependency becomes more clear.

My earlier comment still stands though.

https://github.com/dlang/dmd/pull/15853#issuecomment-1823891157

I'd err on reverting, then move these individually, any change of imports should be kept function local.

These weird template errors arise from changing the global module dependencies.

2023-11-23 11:47 UTC, RazvanN7 commented on compiler/src/dmd/canthrow.d
> -import dmd.expressionsem;
This seems to be the only import that is added in the PR that introduced the regression. You could just put this as a local (potentially, selective) import at line 83.

2023-11-24 13:05 UTC, RazvanN7 requested changes
Suggested fix.

2023-11-29 11:46 UTC, ibuclaw commented
Blocked for a week, and there's [yet another pr](https://github.com/dlang/dmd/pull/15870) that pushes the diff with upstream over the 400kb limit.

2023-11-30 12:16 UTC, RazvanN7 commented
https://github.com/dlang/dmd/pull/15873 - attempt at fixing this regression.

2023-12-14 06:36 UTC, ibuclaw commented
> @ibuclaw ok to close this?

Mainline is green again.

https://github.com/D-Programming-GDC/gcc/actions/workflows/main.yml

2023-12-14 06:36 UTC, closed without merging