Extract dmd.mtype.Type.isBaseOf and move it to dmd.typesem
dlang/dmd pull request #15993
Opened 2024-01-03 16:04 UTC by RazvanN7

2024-01-03 16:05 UTC, RazvanN7 commented
@ibuclaw @kinke I made this function `extern(D)` as the cxx tester does not use it. Please confirm that that is indeed the case on the GDC/LDC side.

2024-01-03 21:08 UTC, thewilsonator commented on compiler/src/dmd/typesem.d
> +bool isBaseOf(Type tthis, Type t, int* poffset)
this is used from C++

2024-01-04 10:14 UTC, thewilsonator requested changes
see above comment

2024-01-05 11:23 UTC, RazvanN7 commented
@thewilsonator done.

2024-01-05 12:22 UTC, thewilsonator approved these changes

2024-01-05 12:30 UTC, merged