Alpine-musl: fix `mmap64` error
dlang/dmd pull request #16361
Opened 2024-04-07 12:40 UTC by kassane

```bash
$ /opt/bin/ldmd2 --version | head -n 8
LDC - the LLVM D compiler (1.38.0-git-bc00d4b):
  based on DMD v2.108.0 and LLVM 17.0.5
  built with LDC - the LLVM D compiler (1.33.0)
  Default target: x86_64-alpine-linux-musl
  Host CPU: znver3
  http://dlang.org - http://wiki.dlang.org/LDC

$ /opt/bin/ldmd2 -run hellod-sample.d 
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /opt/lib/libdruntime-ldc.a(fiber.o): in function `_D4core6thread5fiber5Fiber10allocStackMFNbmmZv':
fiber.d:(.text._D4core6thread5fiber5Fiber10allocStackMFNbmmZv+0x7d): undefined reference to `mmap64'
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /opt/lib/libdruntime-ldc.a(os.o): in function `_D4core8internal2gc2os10os_mem_mapFNbNimbZPv':
os.d:(.text._D4core8internal2gc2os10os_mem_mapFNbNimbZPv+0x21): undefined reference to `mmap64'
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /opt/lib/libdruntime-ldc.a(io.o): in function `_D4core8internal3elf2io__T5ElfIOTSQBg3sysQz10Elf64_EhdrTSQCdQxQBu10Elf64_ShdrVhi2Z7ElfFile4openFNbNiPxaJSQDzQDxQDrQDq__TQDqTQDnTQCuVhi2ZQCcZb':
io.d:(.text._D4core8internal3elf2io__T5ElfIOTSQBg3sysQz10Elf64_EhdrTSQCdQxQBu10Elf64_ShdrVhi2Z7ElfFile4openFNbNiPxaJSQDzQDxQDrQDq__TQDqTQDnTQCuVhi2ZQCcZb+0xa6): undefined reference to `mmap64'
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /opt/lib/libdruntime-ldc.a(io.o): in function `_D4core8internal3elf2io__T5ElfIOTSQBg3sysQz10Elf64_EhdrTSQCdQxQBu10Elf64_ShdrVhi2Z13NamedSections7opApplyMFNbNiMDFNbNimAxaSQErQEpQEjQEi__TQEiTQEfTQDmVhi2Z16ElfSectionHeaderZiZi':
io.d:(.text._D4core8internal3elf2io__T5ElfIOTSQBg3sysQz10Elf64_EhdrTSQCdQxQBu10Elf64_ShdrVhi2Z13NamedSections7opApplyMFNbNiMDFNbNimAxaSQErQEpQEjQEi__TQEiTQEfTQDmVhi2Z16ElfSectionHeaderZiZi+0xaf): undefined reference to `mmap64'
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: io.d:(.text._D4core8internal3elf2io__T5ElfIOTSQBg3sysQz10Elf64_EhdrTSQCdQxQBu10Elf64_ShdrVhi2Z13NamedSections7opApplyMFNbNiMDFNbNimAxaSQErQEpQEjQEi__TQEiTQEfTQDmVhi2Z16ElfSectionHeaderZiZi+0x16a): undefined reference to `mmap64'
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /opt/lib/libdruntime-ldc.a(io.o):io.d:(.text._D4core8internal3elf2io__T5ElfIOTSQBg3sysQz10Elf64_EhdrTSQCdQxQBu10Elf64_ShdrVhi2Z13NamedSections7opApplyMFNbNiMDFNbNimAxaSQErQEpQEjQEi__TQEiTQEfTQDmVhi2Z16ElfSectionHeaderZiZi+0x2a5): more undefined references to `mmap64' follow
collect2: error: ld returned 1 exit status
Error: /usr/bin/cc failed with status: 1
```

cc: @kinke

2024-04-07 16:25 UTC, JohanEngelen commented
To me this does not look like the correct / complete fix. 

https://github.com/gperftools/gperftools/issues/693#issuecomment-174434214
> On musl libc there are no such symbol (`mmap64`) exported. Instead there is a #define mmap64 mmap, meaning that on musl libc, mmap64 is the same thing as mmap.

So this needs a fix here: https://github.com/dlang/dmd/blob/e9c6884046b1b20d2fc21c16d9ec743ba4250858/druntime/src/core/sys/posix/sys/mman.d#L294-L300

2024-04-07 21:11 UTC, JohanEngelen commented on druntime/src/core/sys/posix/config.d
> +    enum __USE_FILE_OFFSET64 = false;
based on the comment of line 90, this should be `true` or be completely removed.

2024-04-07 21:12 UTC, JohanEngelen commented on druntime/src/core/sys/posix/sys/mman.d
> -        alias mmap = mmap64;
based on the linked comment, this should be kept as `alias mmap64 = mmap;`

2024-04-08 14:59 UTC, JohanEngelen commented
I looked a little bit further into the musl druntime code, and I think this needs fixing in several places.
Basically, this has to be removed completely:
```d
    enum __USE_FILE_OFFSET64 = true;
    enum __USE_LARGEFILE     = __USE_FILE_OFFSET64 && !__REDIRECT;
    enum __USE_LARGEFILE64   = __USE_FILE_OFFSET64 && !__REDIRECT;
```

And everywhere where these are used, druntime needs adjustment.  For example also here: https://github.com/dlang/dmd/blob/d3db2e7cb3ba38df597f669d7aa4939690202fca/druntime/src/core/sys/posix/dirent.d#L388-L396
I have fixed the code for `mmap` (see commit e48132b7df8da49b92422b66c0698d72dfcdaaca).

DMD CI does not test Musl, so please do that manually offline :)

Thanks for the work.

2024-04-08 15:00 UTC, JohanEngelen requested changes
Needs changes as mentioned in this comment: https://github.com/dlang/dmd/pull/16361#issuecomment-2042991403

2024-04-08 15:16 UTC, kassane commented
latest commit: 

broken ARM64: https://github.com/kassane/alpine-ldc2-docker/actions/runs/8602260162/job/23571418685#step:6:1791
```bash
ldc.a(file.o): in function `_D3std4file15DirIteratorImpl4nextMFNeZb':
#14 173.1 file.d:(.text._D3std4file15DirIteratorImpl4nextMFNeZb+0x54): undefined reference to `readdir64'
#14 173.1 /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /opt/lib/libphobos2-ldc.a(stdio.o): in function `_D3std5stdio4File6__ctorMFNcNfAyaMAxaZSQBlQBkQBh':
#14 173.1 stdio.d:(.text._D3std5stdio4File6__ctorMFNcNfAyaMAxaZSQBlQBkQBh+0x69): undefined reference to `fopen64'
```

2024-04-08 19:01 UTC, JohanEngelen commented on druntime/src/core/sys/posix/sys/types.d
> -    alias int       pid_t;
better to keep the whitespacing for these items (line 102-110), no change = better :)

2024-04-08 19:03 UTC, JohanEngelen commented on druntime/src/core/sys/posix/sys/types.d
> +  version(CRuntime_Musl){
I think the style-checker will not like this (spaces and newline before `{`)

2024-04-08 19:04 UTC, JohanEngelen commented
Thanks for the work, looks good now (some minor tweaks to whitespace needed)

2024-04-08 19:09 UTC, kassane commented
> Thanks for the work, looks good now (some minor tweaks to whitespace needed)

Thanks, for help-me.

2024-04-08 20:21 UTC, JohanEngelen approved these changes
lgtm

2024-04-09 20:04 UTC, JohanEngelen requested changes
I'm changing my approval, because of the large amount of code duplication seen in the extended PR for LDC druntime... Very sorry that my advice lead you down this path...

2024-04-15 16:59 UTC, dkorpel commented
@JohanEngelen Is this good again?

2024-04-15 17:23 UTC, JohanEngelen approved these changes

2024-04-15 17:24 UTC, JohanEngelen commented
> @JohanEngelen Is this good again?

yes

2024-04-15 17:39 UTC, merged

2025-04-16 19:43 UTC, sertonix commented
This change caused `off_t` to be 32-bit on 32-bit arches but it needs to be 64-bit on all arches for musl. That causes memory corruptions all over the place. The more complicated approach looks more correct to me.

My knowledge of dlang is very limited (0 to be honest) so I hope someone could help me with fixing this.

2025-04-16 21:26 UTC, JohanEngelen commented
> This change caused `off_t` to be 32-bit on 32-bit arches but it needs to be 64-bit on all arches for musl. That causes memory corruptions all over the place. The more complicated approach looks more correct to me.
> 
> My knowledge of dlang is very limited (0 to be honest) so I hope someone could help me with fixing this.
> 
> Edit: 32-bit musl support seems to be broken in multiple places so I will probably need to create a larger patchset.

Can you submit a new bug report about this? Then you can discuss the correct fix for it there.  Thanks!

2025-04-16 22:14 UTC, sertonix commented
I hope a draft is fine as well: https://github.com/dlang/dmd/pull/21249