enable `preview=rvaluerefparam` by default
dlang/dmd pull request #16778
Opened 2024-08-13 09:10 UTC by thewilsonator

https://forum.dlang.org/thread/mailman.2339.1723523028.3719.digitalmars-d@puremagic.com

Will add changelog soon

2024-08-13 09:24 UTC, thewilsonator commented
Lolwot? I didn't close this.

2024-08-13 09:25 UTC, Geod24 commented
The gods of Github don't want this ;)

Wasn't it broken for most of its lifetime ? Quite curious what the CI will say.

2024-08-13 09:28 UTC, thewilsonator commented
> Wasn't it broken for most of its lifetime ?

Wasn't that `noSharedAccess`.

2024-08-13 09:57 UTC, tgehr requested changes
I think this PR accidentally disables the feature for everyone.

2024-08-13 09:57 UTC, tgehr commented on compiler/src/dmd/templatesem.d
> +                        else if (global.params.rvalueRefParam == FeatureState.enabled && !prmtype.ty == Tvoid)
`!prmtype.ty == Tvoid` looks wrong.

2025-01-22 09:55 UTC, dkorpel commented
Superseded by https://github.com/dlang/dmd/pull/17068

2025-01-22 09:55 UTC, closed without merging