Revert "[target.d] refactor 64bit logic"
dlang/dmd pull request #16815
Opened 2024-08-26 17:32 UTC by WalterBright

Reverts dlang/dmd#16669

I object to this because nobody knows what isLP64 actually means. I know it's supposed to mean 64 bit pointers. But, in usage, it gets conflated with "are registers 64 bits". When starting the AArch64 support, I noticed a fair amount of confused use of it in the source code.

So, I switched it to x86_64 and AArch64, and tried to use them completely consistently in the source code. Those both have very specific meanings - 64 bit registers and 64 bit pointers. They are industry standard terms. I refactored all use of them to be consistent with this.

isLP64 is like strcpy to me. Always I have to stop and check if it is used properly. I have to always check if it is set properly. It sucks up time again and again. When I see `isX86_64 || isAArch64` I don't have to check.

A refactoring that would help would be to change target.isAArch64 to target.AArch64 so that it exactly matches the predefined version for it (I've already made this change in the backend). I'd prefer to rename X86_64 usage to x86_64 as well, as that capitalization is the industry standard casing. (Unfortunately, X86_64 is the version condition.)

It's better to not have to mentally do these translations all the time.

I also have long experience with the tangle of overlapping and constantly misused architecture #defines in the C DOS/Windows/Linux world, and really do not want to relive it.

2024-08-26 18:00 UTC, Herringway commented
These would have been good points to raise at any time during the nearly two month period the PR was open.

2024-08-26 23:46 UTC, thewilsonator requested changes, later dismissed
in which case the correct course of action is to go back to https://github.com/dlang/dmd/pull/16669#discussion_r1667619621 not to revert

2024-08-27 03:45 UTC, WalterBright commented
@thewilsonator I don't understand what you mean.

2024-08-27 05:13 UTC, WalterBright commented
This is impacting my ability to keep https://github.com/dlang/dmd/pull/16554 in sync with master.

2024-08-28 00:52 UTC, thewilsonator commented
>  I don't understand what you mean.

use `is64() { return isX86_64 /* ||  is Aarch64*/ ; }`, see the diff in the link.

> This is impacting my ability to keep https://github.com/dlang/dmd/pull/16554 in sync with master.

This is false. I know that you know how to rebase.

2024-08-28 01:53 UTC, WalterBright commented
> This is false.

What I meant is I have to rebase it to the PR, then rebase it again to the reversion.

> see the diff in the link.

Then there's the memory model with 64 bit registers and 32 bit pointers. I don't know if that is I64 or not. I've struggled with these overlapping definitions of architectures for too many years, and don't care to do it any more. When I started the AArch64 project, I carefully refactored the code to use x86_64 and AArch64 in a consistent and unambiguous manner. So far it's been working, I haven't confused myself. Let's keep it that way :-)

2024-08-28 03:56 UTC, Herringway commented
> > This is false.
> 
> What I meant is I have to rebase it to the PR, then rebase it again to the reversion.
> 
> > see the diff in the link.
> 
> Then there's the memory model with 64 bit registers and 32 bit pointers. I don't know if that is I64 or not. I've struggled with these overlapping definitions of architectures for too many years, and don't care to do it any more. When I started the AArch64 project, I carefully refactored the code to use x86_64 and AArch64 in a consistent and unambiguous manner. So far it's been working, I haven't confused myself. Let's keep it that way :-)

I'm glad at least one person doesn't find the backend code completely incomprehensible. Every time I wade into that alphabet soup of D code it just gives me a headache. And that's coming from someone who ports assembly code that doesn't even have named symbols as a hobby...

2024-08-28 04:26 UTC, WalterBright commented
> backend code completely incomprehensible

It's trivially obvious to the most casual observer.

2024-08-28 05:07 UTC, Herringway commented
> > backend code completely incomprehensible
> 
> It's trivially obvious to the most casual observer.

I guess I'm just hopelessly stupid, then

2024-08-28 06:06 UTC, WalterBright commented
Don't despair, my talk at DConf will be about it.

2024-08-29 07:10 UTC, RazvanN7 approved these changes
@thewilsonator Walter has a point that isLP64 is not very clear (I couldn't tell just by looking at it that it means 64 bit pointer). Also, overall this really doesn't look like something very significant, so I think that Walter should have his way.

There is no point in endlessly arguing about low impact cosmetic changes.

2024-08-29 07:10 UTC, merged