fix 24745 - improve associative array syntax error message
dlang/dmd pull request #16832
Opened 2024-09-09 10:57 UTC by royalpinto007

2024-09-09 14:20 UTC, ntrel requested changes
1. I think the new message should only be shown when detecting a colon after a non-identifier expression. E.g. it looks like the message would show for `{expr expr}`, which is unlikely to be intended as an array initializer.
2. The message could say `(associative) array`, because array literals can have indexes too.

Edit: And (1) is why fail_compilation/fix350a.d and fail_compilation/fix350b.d are failing.

2024-11-15 08:31 UTC, thewilsonator approved these changes

2024-11-15 08:38 UTC, dkorpel requested changes, later dismissed

2024-11-15 08:38 UTC, dkorpel commented on compiler/test/fail_compilation/fix350a.d
> +fail_compilation/fix350a.d(12): Error: incorrect syntax for associative array, expected `[]`, found `{}`
This is the wrong message here, this test case has nothing to do with associative arrays.

2024-11-16 23:47 UTC, royalpinto007 commented
I think this can be merged as well? @thewilsonator

2024-11-17 00:08 UTC, merged