fix Issue 13727 - std.stdio.File not thread-safe
dlang/dmd pull request #5747
Opened 2016-05-09 07:54 UTC by WalterBright

The fix is actually here https://github.com/DigitalMars/dmc/pull/2 (access required) and needs a new DMC runtime library snn.lib

https://issues.dlang.org/show_bug.cgi?id=13727

2016-05-09 13:29 UTC, WalterBright commented
This will fail on Win32 until the autotester starts using the new snn.lib

2016-05-09 16:26 UTC, MetaLang commented on test/runnable/test13727.d
> +	version (Windows)
What's with the weird indentation?

2016-05-09 16:26 UTC, MetaLang commented on test/runnable/test13727.d
> +	else
Ditto

2016-05-09 19:56 UTC, yebblies commented on test/runnable/test13727.d
> +import std.array;
No

2016-05-09 19:56 UTC, yebblies commented on test/runnable/test13727.d
> +import std.parallelism;
No

2016-05-09 19:56 UTC, yebblies commented on test/runnable/test13727.d
> +import std.stdio;
No!

2016-05-09 19:58 UTC, yebblies commented
Can't this be done trivially without depending on phobos?

2016-05-09 21:37 UTC, braddr commented
Since there's been a demonstrated failure of the test without the fixed snn.lib now, I've updated the two windows auto-tester hosts.  I agree that depending on phobos in a dmd test is less than ideal, but even less ideal than that is no test.  Since there's disagreement about the implementation of the test, I won't trigger the auto-merge, but we definitely want _a_ test for this bug fix.

2016-05-09 21:58 UTC, yebblies commented
Since druntime contains portable threading,  it should be straightforward to implement without the phobos dependency.

2016-05-16 23:15 UTC, wilzbach commented
> Can't this be done trivially without depending on phobos?

What's so bad about depending on Phobos? I heard a lot of stories from people complaining about not being able to use Phobos and that you want to depend on Phobos for dmd in the future...

2016-05-18 11:14 UTC, yebblies commented
> What's so bad about depending on Phobos? I heard a lot of stories from people complaining about not being able to use Phobos and that you want to depend on Phobos for dmd in the future...

It makes debugging and reducing regressions much more difficult, and the test cases much more fragile.  This has nothing to do with dmd not using phobos internally.

2016-07-14 15:48 UTC, andralex commented
@WalterBright yah let's move this to Phobos. Thx!

2016-09-27 12:11 UTC, schveiguy commented
Can we install this test in the right place? Apologies if it already has, but I don't know how to look for it. I realized the D bug referenced above is still not closed, even though the fix was pulled in dmc, that should probably be closed, but the test should be there first.

2017-06-26 00:39 UTC, CyberShadow commented
Or simply translate [the C example](https://issues.dlang.org/show_bug.cgi?id=13727#c5) to D instead of using the D/Phobos one.

2018-03-12 09:39 UTC, WalterBright commented
Reopened because the test still isn't anywhere. Closing it without creating another PR with the test in it just causes it to be forgotten, not fixed.

2018-03-15 15:41 UTC, schveiguy commented
It seems like the problem hasn't really been fixed, there are sporadic errors on Win32 clients.

2018-03-16 08:23 UTC, ibuclaw commented
Have you tried raising a PR in phobos?

2018-03-16 08:34 UTC, ibuclaw commented
To use a true story as an anecdote,  druntime found a malloc bug in glibc, but the regression test for the glibc bug fix was not added to the D compiler testsuite.  And why would it?

2018-03-16 11:30 UTC, schveiguy commented
Yes, we technically should depend on DMC adding the regression test. But is DMC being CI tested? Is it being actively developed? And is it fun to write C tests when you can write D ones? ;)

glibc is probably a much different story.

I'd much rather the test be here (or at least somewhere in a dlang repository), but more importantly, it seems the fix hasn't worked.

2018-03-20 12:46 UTC, wilzbach commented
> I'd much rather the test be here (or at least somewhere in a dlang repository), but more importantly, it seems the fix hasn't worked.

FYI the auto-tester hosts use a three year old host compiler:

```
DMD64 D Compiler v2.068.2 Copyright (c) 1999-2015 
```

So the buggy `dmc` and `snn.lib` are very likely still on the auto-tester.

2018-03-20 12:55 UTC, schveiguy commented
@wilzbach but that doesn't matter, what only matters is the snn.lib that is being linked against Phobos/druntime. The host compiler is just used to build dmd itself.

Is there a way to check which version phobos is being linked against?

2018-03-20 13:43 UTC, wilzbach commented
> @wilzbach but that doesn't matter, what only matters is the snn.lib that is being linked against Phobos/druntime.

Isn't `snn.lib` shipped with DMD on Windows, so I assume that if an old DMD is still there than the similarly old snn.lib will be there too.

> Is there a way to check which version phobos is being linked against?

DMD is built without Phobos. Most other commands (except for the dmd build tools in `test` use the freshly built version of Phobos)
I'm not sure what you are referring to?

2018-03-20 15:40 UTC, schveiguy commented
> I assume that if an old DMD is still there than the similarly old snn.lib will be there too.

Not necessarily. We want to ensure we can build DMD with specific versions of DMD for bootstrapping, especially since you would a C++-based version of DMD to build DMD from scratch, so we aren't updating the compiler. That doesn't mean we can't update the snn.lib that is used to link Phobos.

2018-03-20 15:45 UTC, schveiguy commented
> DMD is built without Phobos.

Right, but this test DOES use phobos. And is using the built compiler to test it. But it could be done without Phobos, see @CyberShadow's example in the bug report.

Whether it's built with or without phobos, it's LINKED against phobos, which is linked against snn.lib. Based on [@braddr's comment](https://github.com/dlang/dmd/pull/5747#issuecomment-217997757), I think the snn.lib has already been updated. And this is still failing.

2018-06-26 00:50 UTC, wilzbach commented
Rebased to master to see whether this is still failing.

2021-01-23 07:27 UTC, WalterBright commented
rebased

2021-12-16 13:50 UTC, RazvanN7 submitted a review, later dismissed

2021-12-17 01:14 UTC, thewilsonator commented
Removing auto merge - this still fails tests

2021-12-17 07:15 UTC, ibuclaw requested changes
No Phobos tests in the compiler testsuite.

2021-12-17 08:08 UTC, closed without merging