fix Issue 15989 - Initializing manifest constants with CTFE allocated…
dlang/dmd pull request #6164
Opened 2016-10-01 00:37 UTC by WalterBright

… data

2016-10-01 11:09 UTC, DmitryOlshansky commented
This still doesn't answer the question of why did it work in Linux but not on Windows

2016-10-01 14:54 UTC, UplinkCoder approved these changes
LGTM

2016-10-01 14:58 UTC, UplinkCoder commented
@DmitryOlshansky It does not work on either. 
Because the pointer of the object is invalid at runtime,
The virtual opCall will call into a random memory location.
depending on what data is where the vtbl is expected.
Sometimes it does not produce a segfault on windows either.

2016-10-01 22:24 UTC, WalterBright commented
The existing compiler explicitly disallowed CTFE class objects being used to initialized enums. But the compiler neglected to check aggregate initializers for those objects. This PR fixes that, and that's all it does.

It's possible a future compiler could make those work, but that is beyond the scope of this PR.

2016-10-02 12:39 UTC, andralex requested changes

2016-10-02 12:39 UTC, andralex commented on src/declaration.d
> +                    return false;
"When all branches of an if/else chain return, switch to a simpler pattern that removes all `else`s thus eliminating the redundant control flow and making the code easier to follow by reviewers, readers, and maintainers".

```d
                    if (e.op == TOKclassreference)
                        return true;
                    if (e.op == TOKaddress && (cast(AddrExp)e).e1.op == TOKstructliteral)
                        return true;
                    if (e.op == TOKarrayliteral)
                        return arrayHasInvalidEnumInitializer((cast(ArrayLiteralExp)e).elements);
                    if (e.op == TOKstructliteral)
                        return arrayHasInvalidEnumInitializer((cast(StructLiteralExp)e).elements);
                    if (e.op == TOKassocarrayliteral)
                    {
                        AssocArrayLiteralExp ae = cast(AssocArrayLiteralExp)e;
                        return arrayHasInvalidEnumInitializer(ae.values) ||
                               arrayHasInvalidEnumInitializer(ae.keys);
                    }
                    return false;
```

2016-10-02 12:39 UTC, andralex commented on src/declaration.d
> -            version (none)
yay

2016-10-02 20:03 UTC, WalterBright commented on src/declaration.d
> +                    return false;
I don't understand what you're asking for.

2016-10-02 20:21 UTC, andralex commented on src/declaration.d
> +                    return false;
Your code has several redundant `else`s. I'm suggesting their removal.

2016-10-02 20:33 UTC, WalterBright commented on src/declaration.d
> +                    return false;
done

2016-10-02 20:40 UTC, andralex commented on src/declaration.d
> +                    return false;
gracias

2016-10-02 20:40 UTC, andralex approved these changes

2016-10-02 20:43 UTC, andralex commented
Auto-merge toggled on

2016-10-02 21:09 UTC, merged