add more declarations to backend/code.d
dlang/dmd pull request #6181
Opened 2016-10-08 00:50 UTC by WalterBright

2016-10-08 01:04 UTC, WalterBright commented
Pulling this will reduce the size/complexity of https://github.com/dlang/dmd/pull/6177

2016-10-10 05:12 UTC, WalterBright commented
Blocking https://github.com/dlang/dmd/pull/6177

2016-10-12 15:09 UTC, andralex requested changes
Travis also seems to fail. cc @MartinNowak

2016-10-12 15:09 UTC, andralex commented on src/backend/code.d
> +    static if (1) //ELFOBJ || MACHOBJ
So... 1 or a condition? Just delete this for now and insert later if needed. We need to clean such petrified lava.

2016-10-12 20:03 UTC, WalterBright commented on src/backend/code.d
> +    static if (1) //ELFOBJ || MACHOBJ
done

2016-10-12 20:24 UTC, andralex commented
Auto-merge toggled on

2016-10-12 20:54 UTC, merged