Selective unittests
dlang/dmd pull request #6375
Opened 2016-12-27 22:43 UTC by nordlow

Add selective unittests parameter to -unittest flag.

This will incremental testing in cases such as:

https://github.com/nordlow/elisp/blob/master/mine/flycheck-d-all.el

2016-12-28 00:20 UTC, schveiguy commented
cant this all be done via runtime parameters? I think unit threaded does this

2016-12-29 11:58 UTC, nordlow commented
@schveiguy do you mean a global variable somewhere in druntime?

2016-12-29 12:10 UTC, schveiguy commented
No I mean you can change the way unit tests are run via core.runtime. All the unit tests are available as function pointers in their respective ModuleInfo instances. So I think you can already accomplish selective running of module unit tests this way. We could even make this a standard --DRT option. If that's not what you're trying to do then can you explain further?

2016-12-30 00:08 UTC, nordlow commented
This is a tooling feature which must work without chaning any source code.

1. Change a module X.
2. Recompile X together with its transitive deps but include unittests only for X (`-main -unittest=X -cov=100`), run the resulting binary, measure coverage, and check how well the unittest cover the algorithms defined in the module.

2016-12-30 00:30 UTC, schveiguy commented
This can be made to work without changing the compiler, or any user code (just druntime): `myProgram --DRT-unittestmod=X`

Of course, you can change source code to do it too. But my point is that the structure is all there already.

2016-12-30 00:32 UTC, schveiguy commented
In fact, you could unit test different individual modules without recompiling with that mechanism (if implemented).

2016-12-30 11:14 UTC, nordlow commented
What about performance? My solution skips syntactic and semantic analysis of the ignored unittests.

2016-12-30 15:56 UTC, schveiguy commented
You can avoid compiling unit tests for a module by not passing `-unittest` on the command line. That already works.

2016-12-30 16:15 UTC, schveiguy commented
I will note, generally the solution to "I want to compile this module in a different way" is to use separate compilation. Having a switch like you are proposing is a drastically different approach, moving a build system mechanism into the compiler.

2016-12-30 16:38 UTC, nordlow commented
I'm aware of that solution. But separate compilation results in redundant semantic analysis.

2016-12-30 16:48 UTC, schveiguy commented
You can use one compile line to build the entire project except the unit test module, and one to build just the unit test module.

I just see something like this being accepted leading to requests for only optimizing certain modules, or allowing specifying version identifiers for certain modules, etc.

2016-12-31 00:58 UTC, UplinkCoder requested changes
I do not see the utility of this.

2016-12-31 00:58 UTC, UplinkCoder commented on src/root/array.d
> +    static if (is(T == const(char)*))
Array does not provide canFind for other types.
Adding it only for char* is very confusing.

2016-12-31 00:58 UTC, UplinkCoder commented on src/mars.d
> +            else if (memcmp(p + 1, cast(char*)"unittest", 8) == 0) // selective unittest
that cast is unneeded also this should be folded into the above!

2016-12-31 14:25 UTC, nordlow commented on src/root/array.d
> +    static if (is(T == const(char)*))
So where should I put this logic instead?

2016-12-31 14:34 UTC, UplinkCoder commented on src/root/array.d
> +    static if (is(T == const(char)*))
since it is only used in one place, write it inline.

2017-01-07 23:57 UTC, andralex commented
>You can use one compile line to build the entire project except the unit test module, and one to build just the unit test module.

This seems to be the closest workaround. @nordlow could you please experiment with it and report back?

Generally we're getting increasingly conservative with adding compilation flags.

2017-01-08 05:06 UTC, timotheecour commented
> This seems to be the closest workaround. @nordlow could you please experiment with it and report back?
> Generally we're getting increasingly conservative with adding compilation flags.

compare:

`rdmd $dflags $lflags -unittest=foo bar.d`

vs:

```
rdmd -od/tmp/ -c $dflags --exclude=foo bar.d
dmd -unittest $dflags $lflags /tmp/bar.o -run bar.d
rm /tmp/bar.o
```
(there are problably more corner cases, when mixing in rdmd specific flags, using -op etc)

adding `-unittest=foo` is self-descriptive, has been requested many times before.


what about also allowing to specify which unittest to compile?

would be very useful during development, avoid ugly workarounds (or waiting to compile unrelated maybe broken other unittests)

dmd -unittest=A:703 A.d B.d
=> compiles only unittestL703 (ie unittest at line 703)
also would be forward compatible with named unittests, eg:
dmd -unittest=A:my_named_unittest A.d B.d

2017-01-11 23:28 UTC, nordlow commented
I very much agree, @timotheecour. I've already implemented this as an automation but it will still be slower, for instance because of unnecessary io.

2017-04-20 20:10 UTC, andralex commented
Looks like this won't make it - sorry. If new viewpoints come about, don't hesitate to reopen. Thanks!

2017-04-20 20:10 UTC, closed without merging

2018-03-15 18:19 UTC, quickfur commented
@andralex What I would like, which is currently *not* possible even with separate compilation, is a way to exclude unittests that are instantiated by `-unittest` on imported modules from external libraries (including Phobos).  As an example of this problem:

````
$ cat /tmp/test.d
import std.format : format;
void main() {
        string s = format("%s", "Hello world");
}
$ time dmd /tmp/test.d

real    0m0.787s
user    0m0.706s
sys     0m0.078s
$ time dmd -unittest /tmp/test.d

real    0m1.210s
user    0m1.074s
sys     0m0.135s
````

Compiling the code with `-unittest` causes almost a 2x slowdown in compilation time, even though none of the code being compiled contains any unittests.  I can only conclude that this slowdown comes from Phobos unittests being instantiated by `-unittest`.  Therefore, it is not possible to eliminate the cost of said unittests just by separate compilation alone.  If module A imports on module B, then based on the above test it would appear that B's unittests will also be compiled, regardless of whether I separately compile A with `-unittest` and B without `-unittest`.  The very act of importing B from A means that it's impossible *not* to compile B's unittests when I need to run A's unittests.

Therefore, the proposed solution of separate compilation does not fully address the problem. A solution like the one proposed here is needed.

2018-03-15 18:21 UTC, timotheecour commented
@andralex  can we reopen? 

see also this thread: https://forum.dlang.org/post/mailman.1033.1521062556.3374.digitalmars-d@puremagic.com dmd -unittest=<pattern> (same syntax as -i)
which drew support from: Adam D. Ruppe, Jonathan Marler, H. S. Teoh, Nordlöw + others in other threads and slack

support for patterns (same syntax as -i) as I suggested in that thread could be added in subsequent PR's as it would not be incompatible with -unittest=foo.bar as in this PR

This is a common use case and you haven't provided any argument against it ( besides "Generally we're getting increasingly conservative with adding compilation flags.")

2018-03-15 18:33 UTC, schveiguy commented
@quickfur I would like that too, even without any special flags. I can't think of any reason to parse unit tests in imported modules, as long as they are not being instantiated in a template.

I still stand by my original comments, we have ways via build systems (and separate compilation) or via runtime parameters to select which module unit tests are actually run.

2018-03-15 18:59 UTC, andralex commented
Generally:

* If there are acceptable workarounds, we don't think adding command-line options is the way to go. New command-line options are a last-resort measure, not a convenience feature.

* @WalterBright and I suggest exploration of the possibility that `-unittest` only applies to the module(s) being built, not the ones imported. This creates the problem whereby an importing module instantiates a template with unittests inside. As has been argued (by @schveiguy if I remember correctly), unittests inside templates are of very little use as generic test for the instantiation, so that's not a large loss.

2018-03-15 19:04 UTC, wilzbach commented
> This creates the problem whereby an importing module instantiates a template with unittests inside. As has been argued (by @schveiguy if I remember correctly), unittests inside templates are of very little use as generic test for the instantiation, so that's not a large loss.

That's not a problem, but a bug fix. That's exactly why [DIP82](https://wiki.dlang.org/DIP82) has been created.

2018-03-15 19:12 UTC, schveiguy commented
Instantiating unittests inside templates *can be* useful, but it's loss would be no major headache I agree. I've used it to great success to instantiate unit tests for dcollections for a whole slew of types. But the same thing could easily be achieved with separate templates in an external unit test, and the machinery needed to make unit tests that work with a whole bunch of types, and NOT instantiate unittests for the types I didn't want to test was annoying. I wouldn't miss it TBH.

However, where we would lose is if you wanted to run an imported module's unit tests inside a template with a locally defined type. I'm not sure how much something like this is used, but I would hazard to guess it' extremely rare. Something like this might be triggerable with additional syntax, or by encapsulating the test into a specialized function that you only instantiate for unit tests.

> That's exactly why DIP82 has been created.

DIP82 solves a different problem -- allowing unit tests inside templates without having to deal with the instantiation of tests everywhere. Having unit tests next to documentation is the major benefit for this, but I also think it's good practice to stick your tests right next to the functions they are testing, even if they are members of templated types. It helps locate the tests for said functions.

2018-03-15 19:46 UTC, quickfur commented
@andralex  Having `-unittest` apply only to the modules being compiled is an acceptable workaround for me.  (In fact it is a solution I have proposed in the past.)

I also agree that not having template unittests instantiate per user instantiation is not a big loss.  It is of limited use anyway -- it's very hard to write a unittest that *both* (1) works for all possible template arguments, and (2) provides meaningful test coverage beyond what can already be accomplished by tests for specific template arguments.  Should such unittests exist, they would be so rare that it would be acceptable to need a more verbose syntax for them, and to reserve the simplest syntax for the more common use case, i.e., the unittest is only compiled if the containing module is being compiled.

2018-03-15 19:48 UTC, jacob-carlborg commented
I'm hoping we can solve this problem without any extra flags or modifying existing flags.

2018-03-15 22:02 UTC, andralex commented
>@andralex Having -unittest apply only to the modules being compiled is an acceptable workaround for me. (In fact it is a solution I have proposed in the past.)

This is a ripe time to resume that initiative. Thanks!

2018-03-26 13:30 UTC, atilaneves commented
@andralex Having `-unittest` not apply to imported modules completely breaks `__traits(getUnitTests)`. Unless an exception is made for it, of course.

2018-03-26 14:00 UTC, andralex commented
@atilaneves maybe we need to rethink that then

2018-03-27 13:22 UTC, schveiguy commented
> maybe we need to rethink that then

What is it we need to rethink, not applying `-unittest` to imported modules or `__traits(getUnitTests)`?

@atilaneves I think if you are calling __traits(getUnitTests) on a module, that you import, then the compiler can go ahead and semantic those sections. But I'm not a compiler developer, so I don't know what this entails.

Alternatively, we could provide a mechanism to import a module with unittests enabled (if -unittest is passed).

Something like:
```D
import unittest mymodule;
```

Would then treat mymodule's import like it does today (where unit tests are determined by the flag).

I think we need a DIP for better discussion.

2018-03-28 21:41 UTC, andralex commented
It seems more important to do unittesting modularly, so `-unittest` should not apply to imports even if it affects the trait negatively.

2018-03-28 21:54 UTC, quickfur commented
@andralex I don't know dmd internals well enough, but is it possible for `__traits(getUnitTests)` to retroactively run semantic (or lex/parse or whatever it takes to make it work) when it's invoked?  If so, the trait would not be negatively affected.

2019-05-19 16:24 UTC, WalterBright commented
Phantom zoned because this issue comes up repeatedly.