refactor: split off blockExit into separate module blockexit.d
dlang/dmd pull request #6377
Opened 2016-12-28 00:15 UTC by WalterBright

This was always awkward having a Visitor nested inside another Visitor. There's no reason for it to be there - it doesn't rely on anything in the uplevel scopes. Making a new module out of it does a much better job of encapsulating it.

2016-12-28 01:30 UTC, UplinkCoder requested changes
Define the BE-enum in `blockexit.d` as well please

2016-12-28 01:49 UTC, UplinkCoder commented
Otherwise I really like this change.

2016-12-28 10:20 UTC, WalterBright commented
I plan on doing more than that in the future. The first step is just separating it to make it more tractable.

2016-12-28 10:48 UTC, UplinkCoder commented on src/statement.d
> -    /** Only valid after semantic analysis
Please add the second * back in.
So the IDE shows it.

2016-12-28 10:55 UTC, wilzbach commented on src/statement.d
> -    /** Only valid after semantic analysis
FWIW at some point there was also the movement to expose `dmd` as library and there only `**` comments would be publicly documented.

2016-12-28 10:57 UTC, UplinkCoder commented on src/blockexit.d
> +/* ============================================== */
add a * here

2016-12-28 21:00 UTC, WalterBright commented on src/statement.d
> -    /** Only valid after semantic analysis
Ah, that's why it disappeared.

2016-12-29 13:56 UTC, UplinkCoder approved these changes

2016-12-29 14:18 UTC, merged