Make json output more informative for functions.
dlang/dmd pull request #6380
Opened 2016-12-28 16:52 UTC by dhasenan

It now includes the attributes I was able to find as well as the return type, linkage, and purity.

This explicitly includes the return type because a function might be declared without an explicit
return type (eg `int i; auto ref foo() { return i; }`) and that results in a type in the json of
`ref ()`.

2017-03-04 09:38 UTC, wilzbach reviewed
This looks useful to me. Maybe two minor points:
- I think it's worthwhile to use sth. like `attrs` or `attributes` to keep the JSON object clean and adjustable for future attributes.
- Is it possible to output UDAs as well?

2017-03-04 09:38 UTC, wilzbach commented on src/json.d
> +            propertyBool("nogc", tf.isnogc);
It might be worthwhile to put these under `attributes`, especially considering that UDAs should also be part of the output.

2018-01-08 10:25 UTC, JinShil commented
@dhasenan Are you still interested in pursuing this?

2018-02-09 02:26 UTC, WalterBright requested changes
To reduce the size of the json output, I suggest outputting the boolean attributes only if they are `true`. The reader can infer if they are not present that they are `false`.

2018-02-09 02:55 UTC, timotheecour commented
> To reduce the size of the json output, I suggest outputting the boolean attributes only if they are true. The reader can infer if they are not present that they are false.

Using protocol buffers (eg https://github.com/msoucy/dproto) would reduce need for such hacks, and have many other advantages, primarily type/schema safety

2018-02-09 03:03 UTC, closed without merging

2018-02-09 04:36 UTC, WalterBright commented
@dhasenan why did you close this?

2018-02-09 04:46 UTC, dhasenan commented
Because I am not currently able to spend any time on it. It's over a year old and probably has merge errors.

2018-02-09 04:50 UTC, WalterBright commented
No problem. I'll see if someone else wants to pick it up.