Fix issue 16355 - Don't emit a __xpostblit when it's not needed.
dlang/dmd pull request #6400
Opened 2017-01-04 21:53 UTC by LemonBoy

Seems the usual tiny oversight, the `CompoundStatement` generated contains nothing so the generated `__xpostblit` amounts to a noop.

2017-01-05 12:57 UTC, LemonBoy commented
An empty `__xpostblit` is also generated when a `@disable`d postblit is found and that could be elided too since that's a no-op.

2017-01-09 02:16 UTC, MartinNowak requested changes
Please add the issue code as regression test, e.g. test/compilable/test16355.d.

2017-01-09 02:16 UTC, MartinNowak commented on src/clone.d
> +    if ((a && a.dim) || (stc & STCdisable))
Would be nicer with a comment, or even better a cleaner control flow. From the code above it takes a while to see how this can be empty.

2017-01-09 13:19 UTC, LemonBoy commented on src/clone.d
> +    if ((a && a.dim) || (stc & STCdisable))
Indeed, I tried to make the patch as small as possible to ease the review but the logic was a bit hard to understand. The question about the generation of `__xpostblit` even when the postblit is disabled is still unanswered though.

2017-01-09 20:14 UTC, MartinNowak approved these changes

2017-01-09 20:15 UTC, merged