Fix Issue 7016 - local import does not create -deps dependency
dlang/dmd pull request #6468
Opened 2017-01-18 10:53 UTC by RazvanN7

The issue was that inline scan wasn't performed on the dependencies so I added an or at the if which tested if the -inline flag was set so that inline scan is performed in both cases

2017-01-18 10:54 UTC, RazvanN7 commented
..also, I wasn't able to create a test for the example filed in the issue. I may need some help with that.

2017-01-19 02:57 UTC, timotheecour commented
Awesome, been waiting for this for a long time.

* Could you add a flag (off by default) to control this? (so no breaking change ; it is a breaking change because suddenly (because of recursion), it can lead to much longer compile time or broken compiles (say if a dependent import which previously wasn't going to be compiled has to be compiled)
* rdmd has --exclude=package and --include=package to control which dependency gets recursively compiled; i think the same logic can be used here for same reasons as 1st argument (maybe in a 2nd commit though, no point in delaying this)

2017-01-25 10:21 UTC, RazvanN7 commented
This commit solves the problem of infinite recursion caused by cyclic imports. I am not sure if this feature should be activated by another flag since by definition the "-deps" flag should list all dependencies (either local or global). A problem which I noticed is that if a module imports the same module N times in different scopes, the import is printed 5 times (this was true for the older version also). I am not sure if this is the de facto standard or it should be fixed, but either way that is a different problem.

A different question is : should std.* core.* and etc.* imports be ignored? Or should an --include/--exclude flag be added? 

Any suggestions are welcome.

2017-01-25 12:09 UTC, UplinkCoder requested changes

2017-01-25 12:09 UTC, UplinkCoder commented on src/mars.d
> +    import std.conv : to;
calling phobos inside dmd is a nono.
Since you are already using AA's you might as well use the dmd internal hash-table for strings.
it's in root.

2017-01-25 12:09 UTC, UplinkCoder commented on src/mars.d
> +private void semantic3OnDependencies(Module m, bool[string] importArray)
Oh noes,
this is going to slow.

2017-01-25 13:31 UTC, RazvanN7 commented on src/mars.d
> +private void semantic3OnDependencies(Module m, bool[string] importArray)
I replaced the AA with the string-key hashtable in root.springtable. Hope it's ok now. Thanks for the tip

2017-01-25 13:33 UTC, RazvanN7 commented
I made a separate pool request that erases all ddmd. prefixes. For this PR I needed to import ddmd.root.stringtable, so I'm guessing there's gonna be some conflicts.  I think that the faster #6489 is merged, the better.

2017-01-30 09:17 UTC, RazvanN7 commented
@MartinNowak I have no idea why the tests are failing. Locally, I don't have any problems when running the tests.

2017-02-03 11:49 UTC, RazvanN7 commented
@timotheecour do you think that if -deps is used in conjunction with -unittest, should the dependencies of unittests be printed too?

2017-02-08 08:57 UTC, timotheecour commented
> @timotheecour do you think that if -deps is used in conjunction with -unittest, should the dependencies of unittests be printed too?

unittest blocks should be treated as normal functions in that regard, so yes. That way, when rdmd uses `-rdeps`, `rdmd -unittest foo.d` will work as well as `rdmd foo.d` without giving link errors.

* `dmd -deps` behavior should *not* change for reasons given here: https://github.com/dlang/dmd/pull/6468#issuecomment-273668834
* how about calling it: `dmd -rdeps` (and also `-rdeps=<filename>`) for recursive deps
* as said here (https://github.com/dlang/dmd/pull/6468#issuecomment-273668834) we could have:
```
dmd -rdeps-include=package
dmd -rdeps-exclude=package
```

2017-05-07 14:26 UTC, closed without merging