DStruct for loops upgraded to foreachs
dlang/dmd pull request #6604
Opened 2017-03-08 22:07 UTC by dukc

My first pull request for the compiler itself. I refactored dstruct.d loops, kind of a practice pull request.

2017-03-08 22:21 UTC, dukc commented
Something went wrong, yet I think it compiled when I tried myself. What's the correct way to test one's changes locally?

2017-03-09 10:41 UTC, yebblies requested changes

2017-03-09 10:41 UTC, yebblies commented on src/ddmd/dstruct.d
> +        foreach(s; (*members)[])
The `[]` shouldn't be necessary.

2017-03-09 10:41 UTC, yebblies commented on src/ddmd/dstruct.d
> -            Expression e = (*elements)[i];
The segfault might be because `e` is reassigned below.  Try it without this part.

2017-03-09 10:45 UTC, dukc commented
Ah, it was a runtime error, not a compilation error. That explains why I did not notice an error locally.

2017-03-09 11:16 UTC, yebblies commented on src/ddmd/dstruct.d
> +        foreach(s; (*members))
The `()` shouldn't be necessary either now.

2017-03-09 16:32 UTC, dukc commented
True, but above all I have to hunt that segfault out. Is there any better way to test the freshly-made compiler than setting it up for command-line use? That would get slow and error-prone.

2017-03-09 16:42 UTC, yebblies commented
I suggest enabling these changes one by one until you find which loop is failing, then sticking in thousands of asserts etc to see if the 'this' pointer is null, the struct pointer is null, the struct is corrupt, the array from opSlice is corrupt etc.

2017-03-10 18:53 UTC, dukc commented
That's what I'm gonna do, but what I'm wondering is that how do test a compiler I've made locally? If an autotester can do it, I suppose there's a better way than replacing the "system" dmd with it and testing manually?

2017-03-10 19:03 UTC, JackStouffer commented
You can run `make -f posix.mak test`

2017-03-11 08:22 UTC, dukc commented
Thanks, that helped. `make -fwin32.mak auto-tester-build` appears to do what i want. But the tests do not compile because phobos templates do not yet work with -dip1000. Should I try to tweak it to compile the test build without that flag? No quarantees about success, I'm not used to makefiles.

2017-03-11 10:30 UTC, WalterBright commented
Unfortunately, making this change is not reliable, because sometimes down in the bowels of the code members can be added to `members[]` inside the loop. The `foreach` assumes that `members[]` does not change.

2017-03-11 11:34 UTC, dukc commented
What about defining opApply template for Array!T so that it behaves just like the for loop?

2017-03-12 20:52 UTC, UplinkCoder commented
churn ...

2017-03-13 18:58 UTC, dukc commented
I added a function to the Array!T which should solve that concern of Bright. Unfortunately I still do not know how to run the auto-test locally, so we're lucky if this passes.

2017-03-13 19:32 UTC, UplinkCoder commented
This is useless bloat.

2017-03-13 20:06 UTC, dukc commented
I wouldn't say useless, because it lets us to do those foreachs instead of fencepost-bug-prone for loops. But whether it's useful enough to justify the weight... you decide.

Do you want it closed, or just simplified somehow? Other opinions welcome too.

2017-03-14 05:14 UTC, dukc commented
Plausible opinion. If others agree we don't want it, I will close.

2017-03-14 09:33 UTC, WalterBright commented
Pulling this is likely to cause strange bugs in the future, because as I said, because of lazy evaluation of things, sometimes members can be added while executing the loop. The foreach assumes that no members are added, hence strange bugs. We've had these problems several times before with foreach over members, which is why it is not done anymore.

2017-03-14 09:33 UTC, closed without merging