[WIP] Move parser imports to another file
dlang/dmd pull request #6625
Opened 2017-03-14 11:57 UTC by RazvanN7

The parse.d file creates AST nodes which are passed to the semantic analysis. In the current form, the parser imports 95% of the total compiler code, including semantic analysis code which it doesn't use. In order to break the import cycle and to take a step further into transforming the compiler into a library, it is necessary to offer the possibility of separation between parsing and semantic analysis. This PR is a first step in that direction, by moving the creation of AST nodes (more explicitly the "new" expressions) to a different file and transforming the Parser class into a templated class which receives its AST nodes types through a template. This way anyone can define their own AST nodes and instantiate the parser with them.

This is a work in progress. I only moved the creation of Union and Struct declaration nodes to a file called codegenASTFamily which contains a struct that implements the creation methods.

When this PR will be finished, the CodegenASTFamily struct will contain the creation expressions for all AST nodes and parse.d will have a lot less imports.

2017-03-14 13:15 UTC, RazvanN7 commented
CC yebblies

2017-03-14 13:16 UTC, RazvanN7 commented
CC @yebblies

2017-03-14 13:22 UTC, andralex reviewed
Great start! A few course corrections within.

BTW thanks @WalterBright for the great idea with swapping entire AST families.

2017-03-14 13:22 UTC, andralex commented on src/ddmd/attrib.d
> +import ddmd.codegenASTFamily;
Our convention would suggest `codegen_ast_family`

2017-03-14 13:22 UTC, andralex commented on src/ddmd/attrib.d
> +        scope Parser!CodegenASTFamily p = new Parser!CodegenASTFamily(loc, sc._module, se.toStringz(), false);
`scope p = ...` to avoid stuttering

2017-03-14 13:22 UTC, andralex commented on src/ddmd/codegenASTFamily.d
> +}
Great, but no need to tie types with the allocation method. Just this should suffice:

```d
alias StructDeclaration = ddmd.dstruct.StructDeclaration;
alias UnionDeclaration = ddmd.dstruct.UnionDeclaration;
alias BaseClass = ddmd.dclass.BaseClass;
...
```

Then the rest of the code could continue using `new ASTFamily.StructDeclaration;` etc.

If there's a need, we may factor out the allocation and construction mechanisms as well in a later pass.

2017-03-14 13:22 UTC, andralex commented on src/ddmd/dmodule.d
> +            scope Parser!CodegenASTFamily p = new Parser!CodegenASTFamily(this, buf[0 .. buflen], docfile !is null);
as above, no need to specify the type twice

2017-03-14 13:22 UTC, andralex commented on src/ddmd/dmodule.d
> +            scope Parser!CodegenASTFamily p = new Parser!CodegenASTFamily(this, buf[0 .. buflen], docfile !is null);
(throughout)

2017-03-14 13:22 UTC, andralex commented on src/ddmd/parse.d
> +import ddmd.codegenASTFamily;
We should not need this import here. This is important - with the import it still means the parser depends on some specific AST family.

2017-03-14 13:22 UTC, andralex commented on src/ddmd/parse.d
> +    ASTFamily astFam;
No need for a member - just use the static types. If methods are needed in some ASTFamily, they can be defined static.

In the future if we have an AST family keeping its own state (unlikely), we may go with a member.

2017-03-14 13:22 UTC, andralex commented on src/ddmd/parse.d
> +            a = astFam.iInterfaceDeclaration(loc, id, baseclasses);
So this would become `a = new ASTFamily.InterfaceDeclaration(loc, id, baseclasses);`.

2017-03-14 13:22 UTC, andralex commented on src/ddmd/codegenASTFamily.d
> +    alias EnumDeclaration = .EnumDeclaration;
I see you updated this as I was reviewing. Taking this one step further: move all imports inside this struct.

2017-03-14 13:22 UTC, andralex commented on src/ddmd/codegenASTFamily.d
> +    }
These forwarding constructors quickly become a lot of boilerplate so we definitely should avoid them.

2017-03-14 16:57 UTC, UplinkCoder commented
This creates the illusion of independence.
In reality the interface for something to be considered an AST-Family is large and narrow, making it impractical to implement it differently from dmd's ast.

2017-03-14 18:04 UTC, andralex commented
>This creates the illusion of independence.

It creates independence.

>In reality the interface for something to be considered an AST-Family is large and narrow, making it impractical to implement it differently from dmd's ast.

The next step of the project is to create a family of simple AST nodes, devoid of any extra information and analysis. I predict that will be a rather easy undertaking.

2017-03-14 18:23 UTC, UplinkCoder commented
> The next step of the project is to create a family of simple AST nodes, devoid of any extra information and analysis. I predict that will be a rather easy undertaking.

Fair enough.

2017-03-14 21:26 UTC, andralex requested changes
@WalterBright and I just had a pow-wow and agreed with the following:

* acceptance of this hinges on the presence of the ASTNull family that defines minimal AST nodes. The idea being that we want to make sure we don't access fields/methods in AST types that we're not supposed to.
* no underscores in file names :)

2017-03-14 21:26 UTC, andralex commented on src/ddmd/attrib.d
> +import ddmd.codegen_ast_family;
s/codegen_ast_family/astcodegen/g

2017-03-14 21:26 UTC, andralex commented on src/ddmd/attrib.d
> +        scope p = new Parser!CodegenASTFamily(loc, sc._module, se.toStringz(), false);
s/CodegenASTFamily/ASTCodegen/g

2017-03-14 21:26 UTC, andralex commented on src/ddmd/codegen_ast_family.d
> +    import ddmd.aggregate;
Good point. @RazvanN7 this is clever but let's create a unittest build with a separate AST family called e.g. `ASTNull` that has the ABSOLUTE MINIMAL types that make the parser build.

Then we need to parse a few files using `Parser!ASTNull` and place that in a unittest.

2017-03-15 16:22 UTC, andralex commented on src/ddmd/parse.d
> +struct PrefixAttributes(ASTFamily)
@RazvanN7 don't forget to s/ASTFamily/AST/g at some point, thx!

2017-04-03 16:50 UTC, andralex approved these changes

2017-04-03 17:24 UTC, UplinkCoder commented
@RazvanN7 I am not too happy with the naming.
ASTCodegen suggests that this is part of cg.
what About DMDAST and NullAST

2017-04-03 17:32 UTC, RazvanN7 commented
@UplinkCoder Well, actually the it is part of the codegen since it holds useful information for the correct code generation. On the other hand, ASTNull is Walter's choice. I have nothing against the NullAST name

2017-04-03 17:38 UTC, UplinkCoder commented
@RazvanN7 it is a dependency for cg, but does not do any cg on it's own.
hence it should not be in last part of the name.

The last part is always the more significat one in english.
A Baskelball is a ball.
and not a basket.

2017-04-03 17:39 UTC, UplinkCoder commented
@RazvanN7 also astnull is missing in win32 makefile while it is in the posix one

2017-04-03 17:41 UTC, andralex commented
@UplinkCoder @WalterBright  wanted ASTCodegen which I'm also unhappy with but it's his prerogative.

2017-04-03 17:46 UTC, RazvanN7 commented
@UplinkCoder You are right, I updated now the win32.mak file

2017-04-04 11:15 UTC, merged

2017-04-06 08:03 UTC, jacob-carlborg commented
@RazvanN7 the unit test in `ddmd.parse` segfaults on macOS:

This unit test segfaults on macOS:

```
0   dmd                                 0x000000010d713f54 _D4core7runtime18runModuleUnitTestsUZ19unittestSegvHandlerUNbNiiPS4core3sys5posix6signal9siginfo_tPvZv + 56
1   libsystem_platform.dylib            0x00007fffaf8acb3a _sigtramp + 26
2   dmd                                 0x000000010d97bd05 D2rt19sections_osx_x86_6412SectionGroup6__initZ + 742181
3   dmd                                 0x000000010d5bf30a D4ddmd5parse34__T6ParserTS4ddmd7astnull7ASTNullZ6Parser6__ctorMFC4ddmd7astnull7ASTNull6ModuleAxabZC4ddmd5parse34__T6ParserTS4ddmd7astnull7ASTNullZ6Parser + 90
4   dmd                                 0x000000010d5a94d8 D4ddmd5parse18__unittestL8426_10FZv + 56
5   dmd                                 0x000000010d49bf2d _D4ddmd5parse9__modtestFZv + 9
6   dmd                                 0x000000010d713fa1 D4core7runtime18runModuleUnitTestsUZ14__foreachbody2MFPS6object10ModuleInfoZi + 45
7   dmd                                 0x000000010d70c58f D6object10ModuleInfo7opApplyFMDFPS6object10ModuleInfoZiZ9__lambda2MFyPS6object10ModuleInfoZi + 35
8   dmd                                 0x000000010d72a0f2 D2rt5minfo17moduleinfos_applyFMDFyPS6object10ModuleInfoZiZ14__foreachbody2MFKS2rt19sections_osx_x86_6412SectionGroupZi + 86
9   dmd                                 0x000000010d72a07d D2rt5minfo17moduleinfos_applyFMDFyPS6object10ModuleInfoZiZi + 33
10  dmd                                 0x000000010d70c566 D6object10ModuleInfo7opApplyFMDFPS6object10ModuleInfoZiZi + 34
11  dmd                                 0x000000010d713e8b runModuleUnitTests + 127
12  dmd                                 0x000000010d724893 D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZv + 23
13  dmd                                 0x000000010d724830 D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ7tryExecMFMDFZvZv + 36
14  dmd                                 0x000000010d724796 _d_run_main + 498
15  dmd                                 0x000000010d49bc4e main + 34
16  dmd                                 0x000000010d49a0d4 start + 52
Segmentation fault: 11
```

The DMD unit tests are automatically run when building with `DEBUG=1`.

2017-05-08 21:18 UTC, yebblies commented
After reviewing this in more detail I've come to the conclusion that the `ASTNull` is not at all useful, and needs to be deleted.

> acceptance of this hinges on the presence of the ASTNull family that defines minimal AST nodes. The idea being that we want to make sure we don't access fields/methods in AST types that we're not supposed to.

I do agree that such a family is useful, but the minimal AST is ASTBase, not this.  For it to be a minimal AST it must by definite have some kind of use, which this does not.  Making sure that no non-semantic fields are accessed is covered by ASTBase.

I suspect this may have come from a mis-communication of the idea of an AST factory interface that does not actually build an AST, which is the minimal interface required for some parser tasks (syntax verification) - but this is approach is still unacceptable for that as it will unavoidably allocate memory.

The minimal AST set that does involve a class hierarchy must be capable (at the very least) of representing the tree structure of parsed nodes.  After all, the 'T' in AST stands for tree, and if you don't build a tree you have just allocated a bunch of useless classes.  More realistically the minimal AST will contain all of the information necessary to run semantic analysis - ie everything that the parser currently generates.

2017-05-09 05:16 UTC, andralex commented
Is `/dev/null/` unnecessary and should it be deleted? :)

2017-05-09 07:24 UTC, yebblies commented
If `/dev/null/` wrote its contents to disk then yeah it would be hopelessly broken.  This doesn't avoid building an ast, or build a minimally useful ast.

2017-05-09 09:26 UTC, yebblies commented
Compare the [implementation of `/dev/null`](http://elixir.free-electrons.com/linux/v3.2/source/drivers/char/mem.c#L622) vs this PR:
```c
static ssize_t write_null(struct file *file, const char __user *buf,
			  size_t count, loff_t *ppos)
{
	return count;
}
```

Typically a null implementation doesn't take thousands of lines, allocate a bunch of memory, and add a maintenance burden in the form of massive duplication.

Please let me know if I've missed any uses of this that aren't covered better by the base ast or ast construction interface.

2017-05-09 09:30 UTC, jacob-carlborg commented
The AST that just sets the instance variables that was shown in the talk would be a nice start.

2017-05-09 12:27 UTC, andralex commented
@yebblies "I want a parser that simply gives a yes/no on whether the code is syntactically correct, without any additional processing". Generally I'm fine with removing this if it has no use, but give it a little more time before we make that decision.

2017-05-09 12:35 UTC, yebblies commented
This this fails that use case because it allocates a huge amount of memory. This is an easily solved problem but allocating a broken ast is not the answer.

2017-05-09 12:37 UTC, andralex commented
@yebblies OK. Let's give this a couple of months and then remove if not necessary. Thanks!

2017-05-09 17:43 UTC, yebblies commented
How about instead we remove it and if it turns out it's necessary we can add it back in.  That we will fix it now instead of waiting two months to revert a pull you should never have merged in the first place.

Re-adding it would have very little cost, while maintaining it for two months would be a different story.

2017-05-09 18:21 UTC, RazvanN7 commented
I think that ASTNull serves as a good of example of what functions and variables you need to define to have a working parser. ASTBase has a lot of methods and fields which may be dropped if someone wants to implement its own AST family.

I do agree that there is no situation in which ASTNull can be used per se, but it's easier to read than the enriched ASTBase.

2017-05-09 18:39 UTC, yebblies commented
But why would anyone ever define an ast family from scratch instead of deriving from astbase?  Astbase effectively is part of the api of the parser. Any fields in astbase should be required to get a valid ast out of the parser - other fields should not be in there.

I'm happy to talk about improving the readability but not at the cost of this much duplication.