WIP: Fix CPP mangling substitution #1
dlang/dmd pull request #6658
Opened 2017-03-28 21:33 UTC by Darredevil

While trying to interface D with C++ I noticed that most cases will not work due to bugs in the name mangling which causes linking errors. One big problem was the symbol substitution, first of all the way the dmd checked if a symbol was already present in the substitution table was broken for certain cases. The second problem was the way the table was created (order of insertion is relevant here).

For example `std::pair<void*, void*>::swap(std::pair<void*, void*>&)` was mangle as:

- _ZNSt4pairIPvS0_E4swapERS1_ (gcc)

- _ZNSt4pairIPvS1_E4swapERStS0_IS1_S1_E (dmd)

Now dmd mangles these cases the same way as gcc. Further tests and fixes are required because currently 

> No attempt is made to support mangling of templates, operator overloading, or special functions

Will add future patches as I stumble upon the issues and fix them.

2017-03-28 21:58 UTC, WalterBright commented
This is good but it must have a test case. Add one to `test/runnable/cppa.d`. Please ensure that all the changed lines are covered by the test.

2017-03-29 06:01 UTC, ibuclaw commented
Storing should be after the symbol has been written to buffer, there should be no problem there.

Not so sure about the strcmp however.  There's probably a very good reason why they don't match.

2017-03-29 06:07 UTC, ibuclaw commented
> No attempt is made to support mangling of templates, operator overloading, or special functions

And I'm not so sure any attempt should be made to either.  With exception to operators which gets a long, drawn out maybe.

2017-03-30 17:51 UTC, andralex commented
I'm okay with this with @WalterBright's amendment and of course pending pass of tests that currently all fail.

2017-03-30 17:52 UTC, andralex approved these changes
Please add a test (can be only D code using `extern(C++)`) and make sure all tests pass.

2017-03-30 19:43 UTC, ibuclaw commented
> can be only D code using extern(C++)

No, anything marked extern(C++) should be calling a function implemented in C++, otherwise what's the point?

2017-03-31 12:32 UTC, andralex commented
@Darredevil ping

2017-03-31 22:51 UTC, Darredevil commented
So far, when I fix a test or particular case it seems another breaks.
Will tackle them as they pop up until all the tests pass, including the new ones.

2017-04-01 09:54 UTC, andralex requested changes
Tests are still failing. In order to improve development speed, you may want to run tests locally before pushing code.

2017-04-01 09:54 UTC, andralex commented on src/ddmd/cppmangle.d
> +                    if (p.ident == Id.std && is_initial_qualifier(p)) {
no Egyptian bracing please - put brace on its own line

2017-04-01 09:54 UTC, andralex commented on src/ddmd/cppmangle.d
> +                    else {
ditto

2017-04-01 09:54 UTC, andralex commented on src/ddmd/cppmangle.d
> +                if (d.type.isConst()) {
throughout

2017-04-01 09:57 UTC, Darredevil commented on src/ddmd/cppmangle.d
> +                    if (p.ident == Id.std && is_initial_qualifier(p)) {
Ignore this for now please, it will be squashed and fixed in future commit

2017-04-13 12:03 UTC, RazvanN7 commented on src/ddmd/cppmangle.d
> +
No need for this empty line

2017-10-28 13:44 UTC, closed without merging