remove .array / .reverse properties and ajust tests
dlang/dmd pull request #6827
Opened 2017-05-24 11:44 UTC by UplinkCoder

as per title
This is a revamp of #6554

2017-05-24 12:42 UTC, mathias-lang-sociomantic commented
Doesn't `idgen` need an update as well ?

2017-05-24 12:57 UTC, UplinkCoder commented
@mathias-lang-sociomantic I originally intended for the idgen change to be in a separate PR
but it might as well happen now.

2017-05-24 13:01 UTC, UplinkCoder commented
@andralex ready for merge.

2017-05-24 15:29 UTC, andralex approved these changes
thx!

2017-05-24 15:29 UTC, andralex commented
cc @MartinNowak for deployment as he sees fit

2017-05-24 21:09 UTC, UplinkCoder commented
There are still a few tests to fix up..
Should be ready soon though.

2017-05-26 15:11 UTC, UplinkCoder commented
@MartinNowak this passes now.

2017-05-28 12:30 UTC, yebblies commented on test/runnable/foreach4.d
> -
??

2017-05-28 12:30 UTC, yebblies commented on test/runnable/test12.d
> +    import std.range;
??

2017-05-28 12:30 UTC, yebblies commented on test/runnable/test4.d
> -        copy.sort;
Just delete this line?

2017-05-28 12:30 UTC, yebblies commented on test/runnable/wc2.d
> +    import std.algorithm.sorting : sort;
Nooooo

2017-05-29 14:17 UTC, UplinkCoder commented
@yebblies addressed your comments

2017-06-06 19:55 UTC, MartinNowak requested changes
Short changelog notice, otherwise good to go from my side.
https://github.com/dlang/dmd/tree/master/changelog

2017-06-06 21:46 UTC, andralex commented
thx you guys - @UplinkCoder changelog and we should be good to go

2017-06-06 21:53 UTC, UplinkCoder commented
@andralex Martin amended the changelog entry already
You can dis-spell his request for changes.

2017-06-06 22:06 UTC, MartinNowak approved these changes

2017-06-06 22:20 UTC, wilzbach commented
PR for dlang.org: https://github.com/dlang/dlang.org/pull/1672

2017-06-06 22:27 UTC, merged