fix Issue 17275 - [REG 2.072.0] AssertError@declaration.d(2121): Asse…
dlang/dmd pull request #6845
Opened 2017-05-30 03:26 UTC by WalterBright

…rtion failure

2017-05-30 06:38 UTC, ZombineDev commented on test/fail_compilation/test17275.d
> +fail_compilation/test17275.d(12): Error: inout on return means inout must be on a parameter as well for inout(ModuleGroup)()
There's already test/fail_compilation/fail17275.d (https://github.com/dlang/dmd/pull/6690/files#diff-278b7365e40009be458ef32b7f8d85a3). Why don't you put the test output in there?

2017-05-30 13:30 UTC, ibuclaw requested changes
As per comment (I actually made such a commit in #6746 here https://github.com/ibuclaw/dmd/commit/407d2a5c3d068243c2899ef95f079170baa91178)

2017-05-31 19:17 UTC, WalterBright commented
@ibuclaw I don't understand what you're asking for.

2017-06-09 00:07 UTC, ibuclaw commented
@WalterBright - you don't need a new test case, you just need to copy the `TEST_OUTPUT` to  test/fail_compilation/fail17275.d

2017-06-09 08:56 UTC, WalterBright commented
> @WalterBright - you don't need a new test case, you just need to copy the TEST_OUTPUT to test/fail_compilation/fail17275.d

Well, fail17275 was in another branch, and now I've fouled it up completely trying to merge the two.

2017-06-09 08:56 UTC, closed without merging

2017-06-09 20:48 UTC, ibuclaw commented
How did it end up in another branch?