fix Issue 17468 - Internal Assertion fails during CTFE
dlang/dmd pull request #6856
Opened 2017-06-04 18:35 UTC by UplinkCoder

This error happened when because a slice of a pointer is given.
The code used to go into the pointer specific branch based on the type.
However the slice specific branch is the right choice.

I changed the order of the query
I doubt this will break anything

2017-06-04 18:57 UTC, UplinkCoder commented
@WalterBright @MartinNowak @andralex 
quick-merge please :)

2017-06-04 19:35 UTC, jacob-carlborg commented
Do we need a new test?

2017-06-04 19:41 UTC, andralex commented
Code is not covered, please add a test. Thanks!

2017-06-04 19:48 UTC, dnadlinger requested changes
Yes, please add a test.

2017-06-04 20:11 UTC, UplinkCoder commented
@klickverbot done

2017-06-04 20:12 UTC, UplinkCoder commented
Although ... coverage should not have changed by a code move ....

2017-06-04 20:15 UTC, dnadlinger approved these changes

2017-06-04 20:26 UTC, UplinkCoder commented on test/compilable/test17468.d
> +struct S
what does it do ?

2017-06-04 21:26 UTC, wilzbach commented
> @wilzbach @MartinNowak: Do squash-merges need to be performed manually again, or has the whole "too dangerous" argument been refuted?

@MartinNowak removed the "auto-merge-squash" label after @andralex tried to squash a PR, which wasn't supposed to be merged.
See also this discussion:

https://github.com/dlang-bots/dlang-bot/issues/64#issuecomment-284160756

FWIW
- it could be simply re-enabled by just adding the label "auto-merge-squash"
- I'm of the opinion that we all are adults and can reasonably judge when to use "auto-merge-squash" and when not to use ...

2017-06-04 21:27 UTC, wilzbach commented
Btw @UplinkCoder I thought that all bug fixes should be targeted at `stable`?

2017-06-04 21:35 UTC, UplinkCoder commented
closed for similar version targeting stable.

2017-06-04 21:35 UTC, closed without merging

2017-06-05 09:37 UTC, jacob-carlborg commented
> Although ... coverage should not have changed by a code move ....

@UplinkCoder  Since a bug was discovered it means that that part of the code had not enough coverage. The coverage might not change when moving code but that doesn't mean that there was enough coverage from the beginning.

2017-06-06 18:10 UTC, MartinNowak commented
> @wilzbach @MartinNowak: Do squash-merges need to be performed manually again, or has the whole "too dangerous" argument been refuted?

The bot currently does not support (technically) squash merge commits. It will simply dismiss any commit messages at all, see https://github.com/dlang-bots/dlang-bot/issues/64#issuecomment-289068950.
Let's please try to keep such OT discussions out of PR reviews.

2017-06-06 18:11 UTC, MartinNowak commented
> closed for similar version targeting stable.

You can change the base branch of a PR @UplinkCoder, much better than reopening a new PR.