Disallow empty statements made by semicolons
dlang/dmd pull request #6886
Opened 2017-06-10 21:34 UTC by Burgos

This turns the previous warning when using a semicolon
for an empty statement to a compilation error.

2017-06-10 21:35 UTC, Burgos commented on src/ddmd/parse.d
> +            f.fbody = parseStatement(0);
I was going to make a new enum value `PSdefault` or so, but I saw `parseStatement` called with `0` in other places as well, so I left it like this.

2017-06-10 22:12 UTC, ghost requested changes

2017-06-10 22:12 UTC, BBasile commented on src/ddmd/parse.d
> +                error("use '{ }' for an empty statement, not a ';'");
You cant pass from warning to error. There must be a  deprecation period before.

2017-06-11 00:39 UTC, WalterBright commented
This must go through a period of time where it is deprecated first.

2017-06-11 06:12 UTC, Burgos commented
Ah, true. I got mislead by the compiler's source, which states this is deprecated (See the `PSsemi`'s ddoc). Will fix, thanks!

2017-06-11 08:03 UTC, Burgos commented
Changed to a deprecation.

2017-06-11 08:12 UTC, WalterBright approved these changes
Nice work!

2017-06-12 07:39 UTC, Burgos commented
I'm not sure what's up with Jenkins, but he also failed in the trivial #6891 PR

2017-06-12 07:43 UTC, wilzbach commented
> I'm not sure what's up with Jenkins, but he also failed in the trivial #6891 PR

Yes, the Jenkins server was down for a week and now we are playing goose hunting for the introduced regressions in downstream projects, see e.g. https://github.com/dlang/phobos/pull/5469
tl;dr: don't worry about it, the errors should be fixed soon.

2017-06-12 07:49 UTC, nemanja-boric-sociomantic commented
All clear, thanks!

2017-06-13 22:48 UTC, merged