betterC on Win32: execute shared static ctors+dtors
dlang/dmd pull request #6956
Opened 2017-07-01 06:24 UTC by WalterBright

This uses the mechanism Digital Mars C++ uses to call C++ static constructors and destructors to call D shared static constructors and destructors in `-betterC` mode.

Each C compiler does it differently, so some research is necessary to figure it out for other platforms.

2017-07-01 08:25 UTC, CyberShadow submitted a review, later dismissed

2017-07-01 08:25 UTC, CyberShadow commented on test/runnable/betterCsharedctor.d
> + */
Can `TEST_OUTPUT` be used here? Currently nothing tests that the ctors/dtors are actually executed.

2017-07-01 09:11 UTC, jpf91 commented
For linux it's usually just placing a function pointer into a specific section.

👍 to the idea and more betterC work. One thing I was wondering though is that the  betterC constructors then have slightly different runtime semantics (construction order is not guaranteed and cyclic module contructor dependencies therefore will be supported in betterC mode). I'm not sure if it is a good idea to change semantics with a compiler switch.

An alternative is to use an `@CContructor` UDA and normal module level functions, I think LDC already does that. Another benefit of the UDA approach is that you now can easily implement multiple named betterC constructors per module.

Ping @andralex as this is some kind of language change / discussion.

2017-07-01 10:43 UTC, WalterBright commented
Don't pull this yet, I have a better idea.

2017-07-01 10:45 UTC, WalterBright commented on test/runnable/betterCsharedctor.d
> + */
Testing the output will come when the other platforms are supported.

2017-07-01 20:23 UTC, WalterBright commented
Ok, better idea done.

2017-07-01 21:06 UTC, andralex requested changes
Cool beans. This should come with a changelog entry and documentation. Please fix the bug and perhaps add more test (only ctor/dtor).

2017-07-01 21:06 UTC, andralex commented on src/ddmd/glue.d
> +            if (m.ssharedctor)
BUG should be `if (m.sshareddtor)`

2017-07-01 21:10 UTC, WalterBright commented on src/ddmd/glue.d
> +            if (m.ssharedctor)
danged copy/pasta errors!

2017-07-01 21:26 UTC, WalterBright commented
@andralex done

2017-07-02 04:52 UTC, WalterBright commented
While this is waiting, there's https://github.com/dlang/dmd/pull/6957 for the non-controversial bits.

2017-07-27 18:11 UTC, ibuclaw commented
Perhaps `-betterC` should become a meta-flag for other features.  Same as what is done for `-release`.

2017-08-13 12:51 UTC, jacob-carlborg commented
Is this the same as `__attribute__((constructor))` on GCC/Clang? In that case I agree with @jpf91 that it should be a separate functionality, like a UDA or `pragma` on a regular function. This is a useful feature to have even when `betterC` is not used.

We also already have this for ELF targets (Linux and FreeBSD). It was added for the implementation of dynamic libraries.

2017-10-03 23:54 UTC, schveiguy reviewed
I'm against such a change, since D users expect to have proper ordering of D static ctor/dtors regardless of link order. I would recommend instead to simply use the C compiler's feature with that compiler. I can't imagine chasing a bug due to linker order is going to be fun when you switch to `-betterC` mode.

Just giving my opinion for what it's worth, not expecting a response or acceptance.

2017-10-03 23:54 UTC, schveiguy commented on changelog/betterC-STI-STD.dd
> +matches the order in which object files are presente to the linker.
presented?

2017-10-04 00:05 UTC, CyberShadow commented
> I'm against such a change, since D users expect to have proper ordering of D static ctor/dtors regardless of link order.

Not having switches that subtly change language semantics is probably a good idea.

How about allowing the use of this feature through `extern(C) static this() { ... }` regardless of `-betterC`?

2017-10-04 00:12 UTC, schveiguy commented
> How about allowing the use of this feature through extern(C) static this() { ... } regardless of -betterC?

I don't like that either, because I guarantee there is some poor soul who put `extern(C):` at the top of their module, without putting `extern(D)` in front of their static ctor/dtor, and now you will drastically change the behavior.

2017-10-04 09:05 UTC, jacob-carlborg commented
It can be implemented using a UDA or pragma, like for GDC and LDC.

2017-10-06 01:00 UTC, MartinNowak commented
> Each C compiler does it differently, so some research is necessary to figure it out for other platforms.

See #7182

2017-10-06 10:49 UTC, MartinNowak commented
We might close this in favor of https://github.com/dlang/dmd/pull/7182

For the unlikely need of a codebase to support both, `D` and `D -betterC`, `version (D_betterC)` could be used to switch between `shared static this()` and `pragma(crt_constructor)`.

2017-12-12 20:07 UTC, andralex commented
Let's go with https://github.com/dlang/dmd/pull/7182. Further improvements will come on top of it.

2017-12-12 20:07 UTC, closed without merging

2017-12-20 04:28 UTC, changloong commented
Hi, @andralex @WalterBright 

please check on https://issues.dlang.org/show_bug.cgi?id=18100 

crt_constructor need to allow set immutable(which mean it only should be call once, and can not been call from main function).   If we simple use extern(C) shared static this will fix all problem.