fix Issue 17582 - Applying const to struct declaration should make th…
dlang/dmd pull request #6958
Opened 2017-07-02 06:53 UTC by WalterBright

…e struct type const

2017-07-02 06:56 UTC, UplinkCoder commented
do we really need this ?
I supposed it does no harm though.

2017-07-02 07:03 UTC, WalterBright commented
See also https://github.com/dlang/dmd/pull/783 where this bug was introduced.

2017-07-02 16:11 UTC, UplinkCoder commented
@WalterBright I think you can merge this.
There is no harm here.

2017-07-03 00:10 UTC, andralex requested changes

2017-07-03 00:10 UTC, andralex commented on test/runnable/testconst.d
Just to really nail it down, could you please write this:
```d
static assert(is(S7038 == const S7038)));
```

There should be tests for the other qualifiers as well, notably shared.

2017-07-03 00:12 UTC, andralex commented
This is a change in language semantics so it needs a changelog.

I also realized the following problem. Consider:

```d
immutable struct S
{
    void fun() {}
    void fun() immutable {}
}
```

This should not compile because fun is the same function defined twice. Similarly:

```d
immutable struct S {}
void fun(S) {}
void fun(immutable S) {}
```

should not work because fun is defined twice.

2017-07-03 01:52 UTC, WalterBright commented
> This should not compile

It's actually an old issue.
```
void foo() { }
void foo() { }
```
compiles but does not link, as does your example. I.e. it is a separate issue from this PR.

2017-07-03 01:53 UTC, WalterBright commented on test/runnable/testconst.d
Since the code to implement this is generic for all qualifiers, that is unnecessary. But I'll add one for shared.

2017-07-03 03:11 UTC, andralex approved these changes
Thx! Can you please add to the changelog before merging?

2017-07-03 03:12 UTC, andralex commented
The next big step is classes and interfaces.

2017-07-03 03:14 UTC, UplinkCoder commented
is `inout struct` something that even makes sense ?

2017-07-03 20:53 UTC, WalterBright commented
> Can you please add to the changelog before merging?

Since it's a regression fix it will anyway.

2017-07-03 21:09 UTC, wilzbach commented
> Since it's a regression fix it will anyway.

Yup, but as you have already recognized this as regression - why didn't you base it onto stable?
Imho one needs to try really hard to overlook this warning:

![image](https://user-images.githubusercontent.com/4370550/27807881-2864287c-6044-11e7-9958-7b83d6c05ce1.png)

CC @CyberShadow - I am running out of ideas here:
- should we call it "Errors"?
- should we block auto-merge?

2017-07-03 21:12 UTC, CyberShadow commented
The PR was created before the new warning notice was added, so let's give it a bit more time.

2017-07-03 21:35 UTC, merged

2017-07-04 17:13 UTC, ZombineDev commented
@wilzbach the regression is from 2.059. It would be too risky to include this fix in stable, IMO.