fix Issue 17568 - [scope] addresses to fields can be escaped from sco…
dlang/dmd pull request #7022
Opened 2017-07-25 20:47 UTC by WalterBright

…pe method

2017-07-25 21:17 UTC, UplinkCoder approved these changes
lgtm

2017-07-26 12:12 UTC, mathias-lang-sociomantic commented on test/fail_compilation/retscope2.d
> +}
Could you add a test case with a struct nested inside a function, and the pointer being at function scope ?

2017-08-06 09:57 UTC, rainers commented on src/ddmd/escape.d
> +    if (log) printf("checkAssignEscape(e: %s)\n", e.toChars());
Better use `static if(log)` here?

2017-08-06 10:30 UTC, rainers commented on test/fail_compilation/retscope2.d
> +}
Here's a test as suggested by Mathias that still fails to fail to compile:
```
void test17568() @safe
{
	int* p;
	struct T
	{
		int a;
	}
	void escape(ref T t) @safe
	{
		p = &t.a;
	}
    {
        T t;
        escape(t);
    }
    auto bug = *p;
}
```

2017-08-06 10:36 UTC, rainers commented on src/ddmd/escape.d
> +             va.isDataseg()) &&
This looks like a special case very much tuned towards the test case. Shouldn't the check for global data be part of enclosesLifetimeOf?

2017-08-06 14:57 UTC, WalterBright commented on src/ddmd/escape.d
> +    if (log) printf("checkAssignEscape(e: %s)\n", e.toChars());
It doesn't make any difference there.

2017-08-06 22:37 UTC, WalterBright commented on test/fail_compilation/retscope2.d
> +}
It does compile, but should not. Filed as https://issues.dlang.org/show_bug.cgi?id=17725

2017-08-07 07:20 UTC, rainers commented on src/ddmd/escape.d
> +             va.isDataseg()) &&
BTW: should all the changes to this condition also apply to the similar one at line 245?

2017-08-08 07:34 UTC, MartinNowak requested changes

2017-08-08 07:34 UTC, MartinNowak commented on src/ddmd/escape.d
> +             va.isDataseg()) &&
Indeed global data has infinite lifetime, thus an `if (isDataseg()) return true;` in `enclosesLifetimeOf` seems more appropriate.

2017-08-08 09:12 UTC, WalterBright commented on src/ddmd/escape.d
> +             va.isDataseg()) &&
enclosesLifetimeOf presupposes an ordering that does not exist for statics. I.e. all statics have infinite lifetime, so there is no ordering. Locals, on the other hand, have an ordering.

2017-08-08 09:16 UTC, WalterBright commented on src/ddmd/escape.d
> +             va.isDataseg()) &&
Aside from that, this PR is meant to solve a specific issue. Redoing enclosesLifetimeOf would involve redoing all the rest of the logic. Something of that scope should be done as a separate refactoring.

2017-08-10 09:06 UTC, WalterBright commented on src/ddmd/escape.d
> +             va.isDataseg()) &&
> should all the changes to this condition also apply to the similar one at line 245?

The `va.isDataseg()` check is done a few lines down from that.

2017-08-17 13:03 UTC, mathias-lang-sociomantic commented
Ping @WalterBright (Martin's feedback)

BTW I created a `#scope` channel on slack if you ever want to join us :)

2017-08-17 18:40 UTC, WalterBright commented
I replied to @MartinNowak 's feedback. Please take a look at my comments.

2017-08-22 14:57 UTC, ZombineDev commented
Ping @MartinNowak @rainers can we move forward with this?

2017-08-22 17:57 UTC, rainers commented
> enclosesLifetimeOf presupposes an ordering that does not exist for statics

enclosesLifetimeOf pretends to do more than it does (by name and documentation). Maybe it should just be a local function inside checkAssignExp.

Currently, you shouldn't be calling enclosesLifetimeOf on statics at all, so check isDataSeg() before would be cleaner. Otherwise it returns random results.

I'm ok with merging, but maybe the bugzilla title should be narrowed down to this case (for the changelog), https://issues.dlang.org/show_bug.cgi?id=17725 is another example of the same issue. Not sure, if there are more.

2017-08-23 04:16 UTC, WalterBright commented
It works correctly regardless of the order, because those functions are pure and they're OR'd together.

You can change the title if you like. But I want to get this pulled, so I can work on the next [scope] issue. I tried working on several in parallel, but it wound up being a lot of confusing rebase extra work.

Because there are more scope issues in bugzilla, I don't care if any of these fixes are not models of clarity. I want to get it working, and have a test suite to cover the cases. Afterwards is the right time to take a step back and refactor it. Constantly refactoring before knowing what the end result needs to look like is a lot of churn.

Taking a month to pull one fix that is **one line** of code, when there are many in the queue, is a disaster. I have other PRs that consist merely of adding comments that sit around for weeks at a time, too.

2017-08-24 13:00 UTC, MartinNowak commented
> You can change the title if you like. But I want to get this pulled, so I can work on the next [scope] issue. I tried working on several in parallel, but it wound up being a lot of confusing rebase extra work.
> 
> Because there are more scope issues in bugzilla, I don't care if any of these fixes are not models of clarity. I want to get it working, and have a test suite to cover the cases. Afterwards is the right time to take a step back and refactor it. Constantly refactoring before knowing what the end result needs to look like is a lot of churn.
> 
> Taking a month to pull one fix that is one line of code, when there are many in the queue, is a disaster. I have other PRs that consist merely of adding comments that sit around for weeks at a time, too.

IMHO an indication that you shouldn't submit each commit as individual PR ;), but I don't want to open that discussion again.

We've just asked for the `isDataseg()` check to be moved into `enclosesLifetimeOf`, as any static variable has infinite lifetime and thus outlives anything else, it's the infimum of the partially ordered sequenceNumbers.
It smells like there could be more manifestation of the missing `isDataseg()` check, hence the request, which seems both trivial and reasonable.
https://github.com/dlang/dmd/blob/4d86fcba2fd2ef86cc85738cd2ac2b059dbb5800/src/ddmd/declaration.d#L2450
If you have a more strict understanding of the term `encloses`, that's fine, and indeed rewriting all the exisiting code that checks `enclosesLifetimeOf` and `isDataSeg` separately is out of scope here.

2017-08-24 13:01 UTC, MartinNowak approved these changes

2017-08-24 13:54 UTC, merged