merge AndAndExp and OrOrExp into LogLogExp
dlang/dmd pull request #7069
Opened 2017-08-07 08:50 UTC by WalterBright

The two are very nearly identical, so merge them and eliminate code.

2017-08-07 18:08 UTC, ibuclaw commented
What is a LogLog expression?

2017-08-07 19:21 UTC, WalterBright commented
Logical Logical operators

2017-08-07 21:24 UTC, ibuclaw commented
Maybe it should just be called either one of LogExp (logical expression), LogicalExp, or BinLogExp (binary logical expression).

Reading out aloud the name logical-logical operator gives me the same feeling of incorrectness that that-that or had-had would. You have to read it twice to make sure you understand it.

2017-08-07 21:52 UTC, JinShil commented on src/ddmd/astbase.d
> +    extern (C++) final class LogLogExp : BinExp
Could use a comment explaining that `LogLogExp` (or whatever name is ultimately decided on) is for `&&` _and_ `||` expressions so contributors aren't left guessing.

2017-08-07 23:22 UTC, JinShil commented
As a new spelunker of DMD source code, I have to say I'm not crazy about this change; it hides something that was previously quite obvious behind something more obscure.  

If the `AndAndExp` and `OrOrExp` share common functionality, then to whatever extent it is possible, create an `abstract LogExp` class and concrete `AndAndExp` and `OrOrExp` classes, and try to refactor the common code to the base `LogExp`.  `visit(LogExp)` can contain the common functionality with `visit(AndAndExp)` and `visit(OrOrExp)` forwarding to it.

2017-08-07 23:51 UTC, JinShil commented
> As a new spelunker of DMD source code, I have to say I'm not crazy about this change

...but the elimination of redundant code is nice.

2017-08-08 00:33 UTC, WalterBright commented
I've used `loglog` for the andand/oror expressions for a very long time:
https://github.com/dlang/dmd/blob/master/src/ddmd/backend/cod2.c?utf8=%E2%9C%93#L2223

2017-08-08 06:37 UTC, ibuclaw commented
Well this being shared code across potentially many apps, there is a need for it to be understood by anyone reading the api docs (if/when they get published).

2017-08-09 09:51 UTC, WalterBright commented on src/ddmd/astbase.d
> +    extern (C++) final class LogLogExp : BinExp
That's https://github.com/dlang/dmd/pull/7061

2017-08-10 01:10 UTC, UplinkCoder commented
@WalterBright I agree with @JinShil here.
LogLogExp is a headscratcher.
couldln't you introduce it as a superclass of AndAndExp and OrOrExp ?

2017-08-10 07:20 UTC, ibuclaw commented
> couldln't you introduce it as a superclass of AndAndExp and OrOrExp ?

Hmm, right, I've just noticed that this removes AndAnd and OrOrExp declarations, this breaks downstream projects that use these.

At the very least keep the original classes around, update c++ headers, then this is OK for inclusion.

2017-08-10 08:26 UTC, WalterBright commented
> couldln't you introduce it as a superclass of AndAndExp and OrOrExp ?

That wouldn't eliminated near as much code. What I did here is hardly different from IdentityExp and CmpExp, to name just two.

> this breaks downstream projects that use these.

Indeed it does. The fix is generally to delete code (most of this PR is just deleting code).

> At the very least keep the original classes around

Why?

> update c++ headers

expression.h is already updated in this PR

2017-08-12 12:29 UTC, jacob-carlborg commented
> Maybe it should just be called either one of LogExp (logical expression), LogicalExp, or BinLogExp (binary logical expression).

Yes, please. Ideally it should be called `LogicalExpression`, but to be consistent with the rest of the code, `LogicalExp` would be acceptable as well.

Keep in mind that we want to expose DMD as a library, then we need to think about the names we pick and avoid abbreviations.

2017-08-15 20:46 UTC, ibuclaw commented
> Why?

There's no cost keeping them around, and downstream can choose to update independently in their own time, if they even choose to.

2017-09-10 03:04 UTC, WalterBright commented
renamed LogLogExp to LogicalExp

2017-09-10 03:36 UTC, wilzbach approved these changes
> +57 / -300

This is amazing!

2017-09-10 03:46 UTC, wilzbach commented
> There's no cost keeping them around

There is always a hidden cost - especially when it's about maintaining deprecations.

> and downstream can choose to update independently in their own time, if they even choose to.

AFAICT DMD has never issued deprecations before and as DaaL (DMD as a library) isn't really used yet or rarely used, I don't see why this should start with this PR.
Besides the change itself here is really trivial from two classes into one.

2017-09-10 06:42 UTC, JinShil commented
This change is fine.  The reduction in code is nice, and as I spend more time with the DMD code, I realize it is idiomatic DMD.  However, it may be worth remembering that DMD was translated from C++ (whose idioms were more C-ish than C++-ish), and this change seems to favor the C-ish idioms over the modeling power of D.

That being said, the `LogicalExp` name is better and the reduction in code is probably worth it, but those benefits are being traded for a less intuitive API, IMO.

2017-09-10 07:47 UTC, JinShil requested changes

2017-09-10 07:47 UTC, JinShil commented on src/ddmd/sideeffect.d
> +            LogicalExp aae = cast(LogicalExp)e;
Nit: `aae` probably isn't such a good name anymore.

2017-09-10 07:47 UTC, JinShil commented on src/ddmd/e2ir.d
> +        override void visit(LogicalExp aae)
Nit: `aae` probably isn't such a good name anymore.

2017-09-10 07:47 UTC, JinShil commented on src/ddmd/staticcond.d
> +        LogicalExp aae = cast(LogicalExp)e;
Nit: `aae` probably isn't such a good name anymore.

2017-09-10 13:08 UTC, jacob-carlborg commented
> renamed LogLogExp to LogicalExp

Thanks.

2017-09-11 17:08 UTC, andralex commented
@WalterBright thanks very much for compromising on the naming, it certainly threw me off as much as some of the folks who chimed in in here.

2017-09-11 17:08 UTC, andralex approved these changes

2017-09-11 17:09 UTC, merged