fix Issue 17761 - don't leave behind empty section groups
dlang/dmd pull request #7093
Opened 2017-08-21 21:28 UTC by MartinNowak

- check for existing .text.<mangling> section before opening new
  group section, reuse existing sections in case of colliding mangling

2017-08-23 23:37 UTC, WalterBright commented on src/ddmd/backend/elfobj.c
> +static IDXSEC elf_addsectionname(const char *name, const char *suffix = NULL, bool *padded = NULL)
Should return `IDXSTR`

2017-08-23 23:40 UTC, WalterBright requested changes
Replace IDXSEC on line 623 with IDXSTR.

2017-08-24 10:08 UTC, MartinNowak commented
Done @WalterBright

2017-08-24 19:26 UTC, WalterBright approved these changes

2017-08-25 09:14 UTC, merged