Fix Issue 17586 - Overriding a deprecated base class function gives no warning
dlang/dmd pull request #7311
Opened 2017-11-13 13:46 UTC by RazvanN7

2017-11-13 15:58 UTC, PetarKirov approved these changes

2017-11-14 09:29 UTC, JinShil requested changes

2017-11-14 09:29 UTC, JinShil commented on src/ddmd/dsymbolsem.d
> +                        deprecation(funcdecl.loc, "%s is overriding the deprecated method %s",
Please add tick marks (`) around the %s

2017-11-14 12:14 UTC, RazvanN7 commented on src/ddmd/dsymbolsem.d
> +                        deprecation(funcdecl.loc, "%s is overriding the deprecated method %s",
done, thanks!

2017-11-15 13:00 UTC, wilzbach approved these changes
Thanks!

2017-11-15 17:18 UTC, merged

2017-11-15 23:01 UTC, wilzbach commented
The linked issue will automatically appear in the changelog (with title). Do you think this should be explained in a more detailed message?

2017-11-16 11:45 UTC, mathias-lang-sociomantic commented
I think it wouldn't hurt to add a small explanation on every language change. I thought it was more common, but apparently we're not doing it, but we have a large audience, and communicating those changes properly (and their motivation) should be done upfront IMO. But we can just go with the status quo for now :)