VRP Fixes and Tests
dlang/dmd pull request #7556
Opened 2017-12-30 23:23 UTC by somzzz

Added missing tests for https://github.com/dlang/dmd/pull/7355 and made a couple of adjustments. There were some issues with the sign of a number.

2017-12-31 00:05 UTC, ibuclaw commented
Maybe this is one module that could benefit from having unittests to verify the internal implementation as well.

2018-01-09 03:44 UTC, JinShil commented
I can't find any particular problem with this PR, but it is lacking an explanation describing what problem it solves, making it difficult to review.  Is there a bug in the current implementation, or is this just making the implementation more robust?

2018-01-09 12:20 UTC, somzzz commented
@JinShil When https://github.com/dlang/dmd/pull/7355 was pulled, it was missing a couple of tests to ensure coverage for the new code. @andralex told me to add them in a different PR. That's the reason for this one.

2018-01-12 08:13 UTC, ibuclaw requested changes
Needs rebasing

2018-01-12 08:13 UTC, ibuclaw commented on src/dmd/intrange.d
> +                if (!rhsc.imin.negative) rhsc.imin.value = 0;
Condition and branch on separate lines

2018-01-12 08:13 UTC, ibuclaw commented on src/dmd/intrange.d
> +        else if (lhsc.imin.negative & rhsc.imin.negative) sign = true;
Same here

2018-01-12 08:13 UTC, ibuclaw commented on src/dmd/intrange.d
> +        if (lhsc.imax.negative & rhsc.imax.negative) sign = true;
And here

2018-01-12 08:13 UTC, ibuclaw commented on src/dmd/intrange.d
> +            if ((l.imin.negative ^ l.imax.negative) == 1) swap(l, r); // r spans [-1,0]
And here

2018-01-19 17:36 UTC, andralex commented
@somzzz can you please look into the autotester errors?

2018-01-22 09:59 UTC, somzzz commented
@andralex when I click on ```Details``` it says build->passing. I don't see anything on the job logs.
@ibuclaw Do you have other comments about this PR?

2018-01-22 10:08 UTC, wilzbach commented
Yeah auto-tester is full of random failures, see also: https://github.com/braddr/d-tester/issues/66

I closed and re-opened to let SemaphoreCI know about this PR. If the failing Travis is bothering you, simply rebase as we removed Travis completely.

2018-01-22 14:16 UTC, andralex commented
I'll force merge this as the error seems unrelated. We should make it a top priority to have tests reliably pass or fail (hope these aren't the famous last words...).

2018-01-22 14:16 UTC, merged