Enable automatic compiling of imports (DMD ONLY)
dlang/dmd pull request #7676
Opened 2018-01-10 18:30 UTC by marler8997

Based on concerns from @ibuclaw this is a refactor of #7099 which keeps the features out of the front end and moves it to the driver by using a callback function.

2018-01-10 18:50 UTC, marler8997 commented on src/dmd/dmodule.d
> +    // then it will be set to $(D this).  This is used to determine
ok

2018-01-10 18:52 UTC, marler8997 commented on src/dmd/dmodule.d
> +    extern (C++) static __gshared bool function(Module mod) onImport; // callback function when module is loaded
how about `// callback function once the module is parsed` ?

2018-01-10 18:53 UTC, marler8997 commented on src/dmd/dmodule.d
> +        if(onImport !is null)
ugh, I always forget that one

2018-01-10 19:55 UTC, jacob-carlborg requested changes

2018-01-10 19:55 UTC, jacob-carlborg commented on src/dmd/dmodule.d
> +    extern (C++) static __gshared bool function(Module mod) onImport; // callback function called once an imported module is
All new public symbols should have Ddoc comments.

2018-01-10 19:55 UTC, jacob-carlborg commented on src/dmd/dmodule.d
> +    // ownership of template instantiation.
Why not turn this into a Ddoc comment while modifying it.

2018-01-10 20:13 UTC, marler8997 commented
I've decided to select this version of the PR in favor of the current state of #7099.  I'm going to close this PR and push the branch to that one.

2018-01-10 20:13 UTC, closed without merging

2018-01-10 22:38 UTC, timotheecour commented
* That comment is confusing since you seem to have done the opposite (close 7676 and keep 7099 open)
* with the path you choose, will all compilers (including ldc) benefit from `-i` or just dmd ?

2018-01-10 22:41 UTC, marler8997 commented
I figured it would be better to keep the old PR open so it keeps the whole history of the PR that actually gets merged.

As for LDC/GDC, it's up to them if they want to support the feature or not.  If they do, the pattern matching code can be moved into a shared module and they can set the callback function accordingly.  However, currently only DMD will be using it so it makes sense to keep it in the DMD specific module for now.  If an LDC or GDC maintainer indicates they's like to use it, I can put the code in a shared module now.

2018-01-10 22:52 UTC, marler8997 commented
Also note that the way the solution is now designed, the interface is just a callback function.  So the drivers for LDC and GDC could compile imports using whatever mechanism they choose. Like DMD they could supply a list of patterns to include/exclude modules, or they could use another mechanism.  Or they could just leave the callback function set to null which means no imports will be included in the compilation.

2018-01-11 05:41 UTC, timotheecour commented
> As for LDC/GDC, it's up to them if they want to support the feature or not. If they do, the pattern matching code can be moved into a shared module and they can set the callback function accordingly. However, currently only DMD will be using it so it makes sense to keep it in the DMD specific module for now. If an LDC or GDC maintainer indicates they would like to use it, I can put the code in a shared module now.

@klickverbot I see no reason to restrict this feature to dmd and not ldc; should we move the code in a shared module? which one do you suggest?