-color=on should overwrite the default detection
dlang/dmd pull request #7823
Opened 2018-02-01 10:50 UTC by wilzbach

Imho if I as a user tell DMD that it should do colorized output, I expect it to obey my command.
This would avoid the faketty hack in https://github.com/dlang/dmd/pull/7822 and run.dlang.io (https://github.com/dlang-tour/core-exec/blob/master/entrypoint.sh)

2018-02-01 11:16 UTC, timotheecour commented
moved from https://github.com/dlang/dmd/pull/7822#issuecomment-362234898

could we just do the way many tools do? -color=[on|off|auto]
auto would switch on/off depending on isatty
```
eg: git help diff

--color[=<when>]
           Show colored diff.  --color (i.e. without =<when>) is the same as --color=always.  <when> can be one of always, never, or auto. It can be changed by the color.ui and
           color.diff configuration settings.
```
ie, could we make `bool color` be a 3 valued enun insetead

2018-02-10 00:30 UTC, marler8997 commented on test/compilable/testcolor.sh
> +set -eu pipefail
`set -euo pipefail` ?

2018-02-10 00:32 UTC, marler8997 commented on src/dmd/console.d
> +            auto h = GetStdHandle(nStdHandle);
```D
auto h = GetStdHandle(STD_OUTPUT_HANDLE);
```

2018-02-10 00:34 UTC, marler8997 commented on src/dmd/console.d
> +                return false;
This is probably just my personal style, but I like to include a comment for raw boolean return statements,
```D
    return false; // no terminal detected

return true; // terminal detected
```

2018-02-10 00:42 UTC, marler8997 approved these changes

2018-02-10 00:42 UTC, marler8997 commented on src/dmd/console.d
> +            auto h = GetStdHandle(nStdHandle);
Or even
```D
if (GetConsoleScreenBufferInfo(GetStdHandle(STD_OUTPUT_HANDLE), &sbi) == 0)
```

2018-02-10 01:16 UTC, wilzbach commented
BTW I still have the Windows failure to deal with:

```
Expected: [1m__stdin.d(2): [1;31mError: [mno identifier for declarator [0;36m[1mtest[0;36m
Actual:   __stdin.d(2): Error: no identifier for declarator `test`
Makefile:223: recipe for target 'test_results/compilable/testcolor.sh.out' failed
gmake[1]: *** [test_results/compilable/testcolor.sh.out] Error 1
Makefile:258: recipe for target 'start_compilable_tests' failed
gmake: *** [start_compilable_tests] Error 2
gmake: *** Waiting for unfinished jobs....
```

I assume this is due to the Windows `console.d` logic being different, but my Windows Foo is almost non-existent. I added `set +x` :/

2018-06-25 23:51 UTC, wilzbach commented
Finally got around rebasing/reworking this. Let's hope that Windows finally passes this time (I replaced the `strings` command with a crude `sed` call.

2018-06-26 06:31 UTC, rainers commented on src/dmd/console.d
> +        Returns: `true` if a terminal has been detect, `false` otherwise
s/detect/detected/

2018-06-26 06:32 UTC, rainers commented on src/dmd/console.d
> +        static bool detectedTerminal()
`detectTerminal` seems to fit better, as there is no cached result involved.

2018-06-26 06:32 UTC, rainers commented on src/dmd/globals.d
> +        if (Console.detectedTerminal)
dmd code does not omit `()` in unction calls AFAICT.

2018-06-26 06:35 UTC, rainers commented on src/dmd/mars.d
> +                        params.color = false;
This assumes the default to be `true`. You should check `on` here instead and error out if not `auto` below.

2018-06-26 06:38 UTC, rainers requested changes
Nits + logic in cli parsing slightly off.

2018-08-27 01:15 UTC, GoaLitiuM commented
Any updates on this? Before I saw this PR, I wanted to do a similar change for `-color` to add a new option 'always' which would work like the option 'on' in this PR, but I think this change makes more sense.

2018-08-27 07:13 UTC, ZombineDev commented
Yes, this PR is definitely a step in the right direction. I think @wilzbach said that he's going to be busy this week, so hopefully next week he will be able to rebase his PR, so we can go ahead with merging it.

2018-11-14 07:29 UTC, closed without merging