Fix Issue 18367 - dmd should not segfault on -X with libraries, but no source files
dlang/dmd pull request #7839
Opened 2018-02-04 18:20 UTC by wilzbach

2018-02-04 19:17 UTC, UplinkCoder requested changes

2018-02-04 19:17 UTC, UplinkCoder commented on src/dmd/mars.d
> +                if (global.params.objfiles.dim == 0)
@wilzbach indentation seems to suggest you missed braces.

2018-02-04 19:30 UTC, UplinkCoder approved these changes
LGTM

2018-02-04 21:17 UTC, wilzbach commented
Argh this is failing on Windows :/

2018-02-04 23:16 UTC, timotheecour commented
https://github.com/dlang/dmd/pull/7838 will supersede this behavior right? (but still good to submit in meantime)

2018-02-04 23:27 UTC, wilzbach commented
I thought you don't want `-X` to emit JSON, but just `-Xf=-`?

2018-02-04 23:32 UTC, timotheecour commented
ya, sorry ignore my comment

2018-02-05 21:35 UTC, marler8997 commented
PR https://github.com/dlang/dmd/pull/7838 addresses this.  I defaulted to writing to `info.json`, however, your approach of asserting an error works as well.  Let me know what you want to do.

2018-02-06 00:57 UTC, wilzbach commented
I think producing an error is saner then writing to a default info.json file. This would just need extra documentation and the case isn't very popular anyways.

2018-02-06 03:35 UTC, marler8997 commented
Ok I changed my PR to issue an error in this case:
```
Error: cannot determine JSON filename, specify using -Xf=<file> or provide at least one source file
```

2018-02-06 03:39 UTC, marler8997 commented on test/compilable/test18367.sh
> +#!/usr/bin/env bash
bash wizadry

2018-02-06 03:44 UTC, marler8997 commented on test/compilable/test18367.sh
> +#!/usr/bin/env bash
I copied this test to my PR, and added another case to it

2018-02-06 03:53 UTC, timotheecour commented
> I defaulted to writing to info.json, however, your approach of asserting an error works as well. Let me know what you want to do.

indeed, IMO as a general rule it's always better to be explicit (let user choose file name or give error); it reduces bugs (eg what if a user already had an info.json and didn't intend it to be deleted)

2018-02-09 10:13 UTC, wilzbach commented
Closing this in favor of #7838 then. Thanks @marler8997 !

2018-02-09 10:13 UTC, closed without merging