Fix Issue 18584 - Undefined identifier when not specifying 'this'
dlang/dmd pull request #8159
Opened 2018-04-10 13:22 UTC by RazvanN7

Alternate fix to : #7991

2018-04-10 13:32 UTC, andralex commented
Cool! cc @JinShil @WalterBright

2018-04-10 14:52 UTC, RazvanN7 commented
Auto-tester failure seems unrelated

2018-04-10 15:26 UTC, RazvanN7 commented on src/dmd/dscope.d
> +                printf("%.*s  %s.%s, kind = '%s'\n", cast(int)txt.length, txt.ptr,
I assume that `msg` was renamed to `txt` and it was forgotten to update the printf. I stumbled upon it while solving the issue and I made the modification.

2018-04-11 14:50 UTC, JinShil commented
For the test case:
```D
struct S
{
    int n;
    auto fun()
    {
        return tmp!(a => n)();
    }
}

struct tmp(alias fns)
{
    alias fun = fns!int;
}
```

Scope search before:
```
Scope.search(0x7fbd9d6316c0, 'n' flags=x0)
	scope __anonymous
	scope __anonymous
	scope tmp
	scope tmp!((a) => n)
	scope __anonymous
	scope main
	scope __anonymous
```
Scope search after:
```
Scope.search(0x7f2259fbb790, 'n' flags=x0)
	scope __anonymous
	scope __anonymous
	scope fns!int
	scope __anonymous
	scope __anonymous
	scope __anonymous
	scope S                          <---- GOOD
	scope main
	scope __anonymous
```

Seeing `scope S` in the scope search is good, but I'm afraid I don't have enough understanding of the semantics well enough to certify if the rest is correct or not (hence why I was unable to fix this issue myself).  I defer judgement to those more senior than I.

2018-04-16 14:00 UTC, andralex approved these changes

2018-04-16 14:06 UTC, stefan-koch-sociomantic commented on src/dmd/dsymbolsem.d
> +            fd = tempinst.aliasdecl.toAlias().isFuncDeclaration();
use toAlias2

2018-04-16 14:06 UTC, stefan-koch-sociomantic requested changes
Please use toAlias2

2018-04-17 13:16 UTC, merged