Fix Issue 18472 - [Reg 2.078] betterC: cannot use format at compile time
dlang/dmd pull request #8173
Opened 2018-04-16 08:49 UTC by JinShil

When compiling with `-betterC`, `TypeInfo` is not usable at runtime, but it should still be usable at compile-time.

2018-04-16 10:08 UTC, RazvanN7 approved these changes

2018-04-16 10:17 UTC, JinShil commented
While this fixes the test case `enum b = typeid(size_t) is typeid(uint);`, unfortunately it still fails for...

```D
import std.format;
import std.stdio;
void main()
{
    enum s = "%1$s,%2$s".format("foo","bar");
    writeln(s);
}

// phobos/std/array.d(2850): Error: TypeInfo cannot be used with -betterC
```

2018-04-17 06:15 UTC, WalterBright commented on src/dmd/typinf.d
> +    // Even when compiling without `useTypeInfo` (a.k.a. `-betterC`) we should
Code should appear in backticks, not 'betterC' which is not code.

2018-04-17 06:16 UTC, WalterBright commented on src/dmd/typinf.d
> +    // See https://issues.dlang.org/show_bug.cgi?id=18472
The 'See ' is redundant.

2018-04-17 06:17 UTC, WalterBright approved these changes
Please fix my suggestions, then I approve.

2018-04-19 06:36 UTC, jacob-carlborg commented
Does this fix the whole issue?

2018-04-19 06:38 UTC, JinShil commented
> Does this fix the whole issue?

No, it only fixes...

```D
enum b = typeid(size_t) is typeid(uint);
```

The following will still fail to compile...

```D
import std.format;
import std.stdio;
void main()
{
    enum s = "%1$s,%2$s".format("foo","bar");
    writeln(s);
}

// phobos/std/array.d(2850): Error: TypeInfo cannot be used with -betterC
```

2018-04-19 06:40 UTC, jacob-carlborg commented
So, if we merge this, won't that close the issue and show up in the next changelog?

2018-04-19 06:42 UTC, JinShil commented
> So, if we merge this, won't that close the issue and show up in the next changelog?

Yes, but I plan to reopen the issue when that happens (I don't know how else to deal with it unless I change the title and commit messages). The `enum` test case was a test added to that issue, so the issue is partially addressed by this PR.

2018-04-19 06:45 UTC, jacob-carlborg commented
I think you should change the title. Even if the issue is reopened and there's no changelog entry the commit message would still be misleading from someone reading the git log.

2018-04-19 06:46 UTC, jacob-carlborg requested changes
Please change the commit message since it the PR doesn't fix the whole issue and the commit message would be misleading as is.

2018-04-19 12:00 UTC, jacob-carlborg approved these changes

2018-04-19 12:01 UTC, merged