Fix Issue 11742 - cannot inizialize void initialized static variable in static constructor
dlang/dmd pull request #8198
Opened 2018-04-20 09:12 UTC by RazvanN7

If a non-mutable variable is initialized at module level, it cannot be modified in the module static constructor because that would invalidate the initial initialization. However, if the non-mutable variable is initialized with `void` this should not count as an initialization and the static constructor should be able to initialize it.

2018-04-20 09:21 UTC, jacob-carlborg approved these changes

2018-04-21 07:09 UTC, WalterBright commented on test/runnable/test11742.d
> +// https://issues.dlang.org/show_bug.cgi?id=11742
Can this be merged into one of the "lots of test cases" files, like test42.d? The reason is then the autotester runs faster.

2018-04-21 07:09 UTC, WalterBright requested changes
See comment. Otherwise, looks good!

2018-04-22 10:33 UTC, RazvanN7 commented
@WalterBright done. thanks!

2018-04-23 02:43 UTC, WalterBright approved these changes

2018-04-23 06:15 UTC, merged