don't infer scope for locals with scoped destructor
dlang/dmd pull request #8369
Opened 2018-06-18 08:48 UTC by WalterBright

Need to find out why this inference was done.

2018-06-18 09:10 UTC, WalterBright commented
Looks like I did it https://github.com/dlang/dmd/pull/7284

2018-06-18 11:02 UTC, ZombineDev commented
> don't infer scope for locals with scoped destructor

Can you clarify why you think we shouldn't do inference?

2018-06-18 20:20 UTC, WalterBright commented
It turns out that `scope` on a destructor means it isn't leaking the data, which has nothing to do with implying the instance itself should be `scope`.

2018-06-25 02:10 UTC, Geod24 commented on test/fail_compilation/retscope3.d
> +scope struct List
Not to mention `scope` in the case of `class` makes sense. `scope struct`, I've absolutely no idea what it does.

2018-06-28 00:00 UTC, WalterBright commented on test/fail_compilation/retscope3.d
> +scope struct List
> I've absolutely no idea what it does.

It means any local assigned a `scope struct` value is inferred to be `scope` as well.

2018-06-28 00:01 UTC, WalterBright commented on test/fail_compilation/retscope3.d
> +scope struct List
@jinshil this is about scope for structs, not for classes.

2018-06-28 00:34 UTC, JinShil commented on test/fail_compilation/retscope3.d
> +scope struct List
@WalterBright if this is a legitimate use of `scope` then it needs to be documented somewhere describing what it does, preferable with a few examples illustrating the semantics.  I think this is the first use of `scope` on a struct in our entire D ecosystem, and prior to this PR, I don't know if attributing a struct with `scope` ever did anything.

2018-06-28 00:42 UTC, JinShil commented on test/fail_compilation/retscope3.d
> +scope struct List
Also, I don't like the inconsistency where using `scope class` has no meaning, but using `scope struct` does.  I would prefer better uniformity in the language.  I get the impression that we're designing by the seat of our pants here.  Why can't users just attribute `scope` at the usage site?  What's the compelling use case for making it a type constraint?

2018-06-28 00:49 UTC, Geod24 commented on test/fail_compilation/retscope3.d
> +scope struct List
Also, how does this fixes thing ? If one leaves `scope` out of the definition, the code compiles.

2018-09-19 08:39 UTC, Geod24 commented
Where are we on this ?

2018-10-07 06:00 UTC, WalterBright commented
@Geod24 Waiting for someone to approve it.

2019-02-07 21:01 UTC, 12345swordy commented
This PR needs rebasing.

2019-09-05 04:25 UTC, Geod24 commented
> recognize a `scope struct` as being a struct that locals declared as instances of the struct will be inferred as scope.

And that's where the failure of the design is. Instead of having transitive `scope`, we're going to have to make the *type definition* include `scope`. This is very obviously not composable.

2021-01-23 15:45 UTC, 12345swordy commented
cc @RazvanN7

2021-01-25 07:52 UTC, RazvanN7 commented
This requires a changelog entry and a spec PR.

2021-05-31 09:05 UTC, RazvanN7 requested changes
There are a few issues with this PR:

- Does this actually fix Issue 17934? If yes, this should be linked to the associated issue in bugzilla.
- It requires a changelog entry and a spec PR since there is no mention in the docs about scope structs.
- Why do we need to have `scope struct` definitions? Can't we just use scope as a type qualifier whenever we want that?

2021-12-16 13:34 UTC, RazvanN7 commented
ping @WalterBright

2022-03-30 08:53 UTC, dkorpel commented
Superseded by https://github.com/dlang/dmd/pull/13926
Since `scope struct` is deprecated (as discussed in the March 2022 foundation meeting), fixing issue 17934 will require a different approach.

2022-03-30 08:53 UTC, closed without merging