Const add
dlang/dmd pull request #8489
Opened 2018-07-12 12:51 UTC by gapdan

2018-07-12 13:17 UTC, jacob-carlborg approved these changes

2018-07-12 14:38 UTC, wilzbach commented on src/dmd/link.d
>                  sprintf(q, "_CMDLINE=%s", args);
```
dmd\link.d(749): Error: function `core.stdc.stdio.sprintf(scope char* s, scope const(char*) format, ...)` is not callable using argument types `(const(char*), string, const(char)*)`
dmd\link.d(749):        cannot pass argument `q` of type `const(char*)` to parameter `scope char* s`
```

We probably should change the declaration in druntime to reflect this, but I guess for now it looks you can't easily do this here.

2018-07-12 17:41 UTC, Geod24 commented on src/dmd/lexer.d
> +    const TOK tok;
This won't work, it gets modified afterwards

2018-07-12 17:42 UTC, Geod24 commented on src/dmd/link.d
> +                const char* q = cast(char*)alloca(8 + len + 1);
This cannot work because we need to mutate it later

2018-07-12 17:44 UTC, Geod24 requested changes
I commented on changes which cannot work.
I think adding `const` to parameters which are value type is not useful. It doesn't add anything to the interface.
Adding `const` inside body is good though.

2018-07-12 18:48 UTC, jacob-carlborg commented
> I think adding const to parameters which are value type is not useful. It doesn't add anything to the interface.

No, but it won't be possible to modify the parameter inside the function.

> Adding const inside body is good though.

Why shouldn't it apply to parameters as well? They are basically like local variables.

2018-07-13 13:45 UTC, RazvanN7 approved these changes

2018-07-13 14:50 UTC, jacob-carlborg commented
Please squash the commits.

2018-07-15 05:43 UTC, Geod24 commented
@jacob-carlborg : Except that local variables are not part of the function's interface.
It's not a big deal to have those, certainly not something to block a merge over, but it is just at odds with the rest of the codebase, not only dmd, but druntime and Phobos as well (there was a similar discussion on `scope` on value type recently in Phobos).

2018-07-15 08:53 UTC, jacob-carlborg commented
> Except that local variables are not part of the function's interface.

Yes. But why should you be allowed to modify the parameters inside a function but not the local variables?

2018-07-27 02:17 UTC, Geod24 commented
@gapdan : I don't necessarily agree, but not enough to block this PR :)
I'll close/reopen to re-trigger the CI.

2018-07-29 17:07 UTC, wilzbach commented
>  I don't necessarily agree, but not enough to block this PR

Same here.

> I'll close/reopen to re-trigger the CI.

Jenkins has now finally been replaced by Buildkite, Force-merging this one ;-)

2018-07-29 17:08 UTC, merged