[WIP] Activate -dip1008 (@nogc exception handling) by default
dlang/dmd pull request #8508
Opened 2018-07-19 16:40 UTC by wilzbach

Just to see what would break if `-dip1008` is activated by default.

2018-07-19 16:54 UTC, wilzbach commented
So this pattern will cause breakage:

```d
Exception collectException(void delegate() dg)
{
    try
        dg();
    catch (Exception e)
        return e.;
    return null;
}
```

According to DIP1008:

> Catch objects being scope will cause problems in that everything done with those objects will also have to be scope. The most likely problem will be printing the objects, which relies on Object.toString(), which is not scope. One possible solution is to force Throwable.toString() to be scope, which will likely cause minimal disruption. Of course, compiling with -dip1000 will disable such checking and can work in the interim. Code that needs to leak the thrown exception object can clone the object.

https://github.com/dlang/DIPs/blob/master/DIPs/DIP1008.md

1) So I guess we should add a deprecation warning to clone the object for such cases?
2) Should we support `.dup` for the Exception class?

2018-07-19 17:59 UTC, jacob-carlborg commented
> Should we support .dup for the Exception class?

Ideally we should have a generic (deep) copy function that works for all types.

2018-07-21 06:37 UTC, WalterBright commented
Adding a warning wouldn't be helpful, as running the code will corrupt memory. Better to just leave it as an error. Need to fix the errors as they crop up.

2018-07-23 12:46 UTC, wilzbach commented
What should we do about:

```d
catch (shared(Abc) b)
```

Add an overload to `_d_delThrowable` or deprecate this?

> Better to just leave it as an error.

This would imply breaking changes for a few projects, no?

2018-07-23 13:44 UTC, jacob-carlborg commented
> This would imply breaking changes for a few projects, no?

As far as I understand, yes.

2019-10-04 08:30 UTC, WalterBright commented
> Add an overload to _d_delThrowable or deprecate this?

I think we should deprecated it. Throwing shared objects seems like it would be fraught with problems.

> This would imply breaking changes for a few projects, no?

Yes. That's why this should add `revert=dip1008` for those projects that need more time.

2019-10-04 08:31 UTC, WalterBright requested changes
Need to add `-revert=dip1008` switch.

2019-10-04 08:50 UTC, rainers commented
Please note that the current implementation still allocates from the GC:

```d

int foo(int) @nogc
{
    throw new Exception("huhu");
}

void test() @nogc
{
    try
    {
        foo(1);
    }
    catch(Exception e)
    {
    }
}

void main()
{
    import std.stdio;
    import core.memory;
    auto stats1 = GC.stats();
    test();
    auto stats2 = GC.stats();
    writeln(stats1);
    writeln(stats2);
}
```
https://run.dlang.io/is/qP2hZg

2019-10-04 09:09 UTC, AndrejMitrovic commented on src/dmd/cli.d
> -            "implement https://github.com/dlang/DIPs/blob/master/DIPs/DIP1008.md",
Btw, this link was a 404. I don't know why there need to be 4 different DIP folders and the DIPs constantly being moved back and forth, it just keeps breaking links everywhere..

2019-10-04 12:01 UTC, wilzbach commented
(in case it wasn't clear from the "Orphaned" label: I unfortunately don't have any time in the forseeable future to invest time in this effort. I encourage anyone, however, to help out with this effort.)

2019-10-04 14:58 UTC, JohanEngelen commented on test/compilable/testdip1008.d
> -// REQUIRED_ARGS: -dip1008
Not future-proof to remove this flag!

2019-11-12 15:08 UTC, RazvanN7 commented
I have adopted this PR. Check: https://github.com/dlang/dmd/pull/10561

2019-11-12 15:08 UTC, closed without merging