Add predefined version identifier `D_BoundsChecks`
dlang/dmd pull request #8532
Opened 2018-08-02 08:43 UTC by Geod24

```
One stylistic rule that is strictly enforced in D is that
version identifier and CLI switch should be positive.
`D_NoBoundsChecks` stands out as an exception in this regard.
This PR just adds `D_BoundsChecks` so that code have at least
one release to transition to it, before `D_NoBoundsChecks` is deprecated.
```

2018-08-02 11:38 UTC, JinShil commented on changelog/d_boundscheck.dd
> +This version adds the opposite `D_BoundsChecks` so that code have at least
I think we might be subject to the deprecation policy being proposed at https://github.com/dlang/DIPs/blob/master/DIPs/DIP1013.md

2018-08-02 11:39 UTC, JinShil commented on src/dmd/mars.d
> +    else // Introduced in 2.082.0 - Deprecate `D_NoBoundsChecks` later
Use the deprecation comment syntax proposed in https://github.com/dlang/DIPs/blob/master/DIPs/DIP1013.md for easy grepping, and remain consistence with other deprecations in the code base.

2018-08-02 11:40 UTC, JinShil commented
Fine with me after we have a spec update and we get deprecation policy sorted out.

2018-08-02 21:50 UTC, WalterBright approved these changes
It's not "strictly" enforced, just a strong bias that direction. Also, it should be removed from the documentation (and this added).

2018-08-03 01:26 UTC, Geod24 commented
@JinShil : Thanks for the link, didn't knew about it.
I wanted to introduce the version identifier for at least one release before deprecating the other identifier, so that transition is smoother. What do you think ?

2018-08-03 01:48 UTC, Geod24 commented
https://github.com/dlang/dlang.org/pull/2438

2018-08-03 03:31 UTC, JinShil approved these changes

2018-08-03 04:32 UTC, Geod24 commented
Also found https://issues.dlang.org/show_bug.cgi?id=19137 out

2018-08-03 11:28 UTC, wilzbach commented on changelog/d_boundscheck.dd
> +This version adds the opposite `D_BoundsChecks` so that code have at least
I think it should be either code bases or projects (code can't transition itself, can it?)

2018-08-04 00:00 UTC, WalterBright commented
> Also found https://issues.dlang.org/show_bug.cgi?id=19137 out

Good catch. I withdraw my approval until this is sorted out.

2018-08-04 00:01 UTC, WalterBright requested changes
Need to resolve bug 19137

2018-08-06 02:43 UTC, Geod24 commented
@WalterBright : Could you give your opinion on said bug ? My original thought was that we could apply `D_BoundsChecks` when the scope is `@safe` but I'm afraid it will introduce a bad precedent. E.g. what about a template specialization which is `@safe` and has invalid code in its `D_BoundsChecks` versioned code ?

On the other hand @JinShil proposed to introduce `D_SafeBoundsChecks`, which is a much simpler approach but makes it more difficult for the user. One has to know which one to use, and it might not be possible (e.g. when templates are used).

Do you have an alternative idea, or do you prefer one of those ?

2020-08-03 11:23 UTC, ghost requested changes
This not worth starting a deprecation. New version identifiers however should follow the rule of being "positive". Also even if unlikey, the new reserved version could exist somewhere in some code, so a deprecation would also be required, making this (even if simple) change a long process.

I suggest @Geod24 to close.

2020-08-03 11:25 UTC, Geod24 commented
Yes the benefit of this is very low, hence why I haven't pursued it. However, one note: version identifiers starting with `D_` are reserved so there wouldn't be a need for a deprecation.

2020-08-03 11:25 UTC, closed without merging

2020-08-03 11:27 UTC, NilsLankila commented
ok, note taked.