Re-add extern(C++) back to the entrypoints of cppmangle
dlang/dmd pull request #8535
Opened 2018-08-04 10:19 UTC by ibuclaw

Partially reverts the refactoring in #8425, as it did not consider the scenario where the Target interface is implemented in C++ itself.

2018-08-04 10:43 UTC, jacob-carlborg approved these changes

2018-08-04 20:53 UTC, ibuclaw commented
```
Test runnable/betterc.d failed.  The logged output:
../generated/linux/release/64/dmd -conf= -m64 -Irunnable -betterC  -fPIC  -odtest_results/runnable -oftest_results/runnable/betterc_0  runnable/betterc.d 
test_results/runnable/betterc_0.o:runnable/betterc.d:function _D6object__T5__cmpThZQjFNaNbNiNexAhxQdZi: error: undefined reference to '_D4core8internal6string7dstrcmpFNaNbNiNeMxAaMxQeZi'
test_results/runnable/betterc_0.o:runnable/betterc.d:function _D6object__T5__cmpTaZQjFNaNbNiNexAaxQdZi: error: undefined reference to '_D4core8internal6string7dstrcmpFNaNbNiNeMxAaMxQeZi'
test_results/runnable/betterc_0.o:runnable/betterc.d:function _D6object__T5__cmpTbZQjFNaNbNiNexAbxQdZi: error: undefined reference to '_D4core8internal6string7dstrcmpFNaNbNiNeMxAaMxQeZi'
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
```

Who broke the testsuite?

2018-08-04 20:57 UTC, ibuclaw commented
@JinShil - could https://github.com/dlang/druntime/pull/2255 be related?

2018-08-04 23:46 UTC, JinShil commented
Yes, that error is the error that  https://github.com/dlang/druntime/pull/2255 fixed.  I've seem this before, where the CI, for some reason, doesn't appear to grab the latest code from druntime.

2018-08-05 09:25 UTC, wilzbach commented
The buildkite failure s related to the recent dub outage, DAutotest is completely/permanently broken for stable though.

2018-08-05 13:00 UTC, ibuclaw commented
@wilzbach - Can it be temp disabled until it is green again then?

2018-08-05 23:40 UTC, Geod24 approved these changes
Sorry!

2018-08-06 04:14 UTC, Geod24 requested changes
Actually, can you add them to the C++ headers ? I didn't see it there, which is why I thought it was unused.

2018-08-06 16:01 UTC, wilzbach commented
>  Can it be temp disabled until it is green again then?

Removed the "Required" status for DAutoTest (CC @CyberShadow) for now.

2018-08-06 16:49 UTC, CyberShadow commented
I don't think it's a problem with the CI.

I think a lot of PRs were force-merged recently because of temporary Dub / code.dlang.org failures. Perhaps one of those introduced a regression that would have otherwise been caught?

2018-08-06 18:22 UTC, merged

2018-08-06 18:33 UTC, ibuclaw commented
Oops, @Geod24 looks like you have no authority.

Not putting things in headers is a problem in dmd.  For instance:
https://github.com/D-Programming-GDC/GDC/blob/stable/gcc/d/dfrontend/expressionsem.c#L41-L80

I maintain the list of functions used by gdc but not found anywhere in headers here:
https://github.com/D-Programming-GDC/GDC/blob/master/gcc/d/d-frontend.h#L35-L48

Really, the C++ header should be generated by some D scanner, rather than hand maintained.

2018-08-06 19:02 UTC, jacob-carlborg commented
> Really, the C++ header should be generated by some D scanner, rather than hand maintained.

Definitely. Ideally by using DMD as a library.