build.d: Add proper DDoc for all functions
dlang/dmd pull request #8629
Opened 2018-08-28 09:51 UTC by JinShil

2018-08-28 10:09 UTC, jacob-carlborg requested changes

2018-08-28 10:09 UTC, jacob-carlborg commented on src/build.d
> +    filename = the source file to build, generating the object file
The parameter name has a capital `N`.

2018-08-28 10:09 UTC, jacob-carlborg commented on src/build.d
> +*/
Not sure what the style guide says but I would recommend three slashes instead.

2018-08-31 00:47 UTC, Geod24 commented on src/build.d
> +Returns: the depedency that builds the lexer
Usually for such trivial doc we only document the `Returns`.

2018-08-31 05:30 UTC, PetarKirov approved these changes
Nice work overall. With a few minor nits fixed, feel free to auto-merge:

2018-08-31 05:30 UTC, ZombineDev commented on src/build.d
> +/// eturns: the command for querying or invoking the host C++ compiler
Typo on "Returns".

2018-08-31 05:30 UTC, ZombineDev commented on src/build.d
> +e.g. ./build.d ARGS=foo -> sets ARGS to 'foo'
`sets the "ARGS" environment variable to "foo"`

2018-08-31 05:30 UTC, ZombineDev commented on src/build.d
> +    args = the assignments to add to the environment
The command-line arguments from which the assignments will be parsed.

2018-08-31 07:07 UTC, merged