refactor setTargetCPU()
dlang/dmd pull request #8664
Opened 2018-09-05 10:52 UTC by WalterBright

There is a simpler function lurking within it.

2018-09-05 10:53 UTC, WalterBright commented
This relies on https://github.com/dlang/dmd/pull/8663

2018-09-05 11:37 UTC, jacob-carlborg commented
#8663 has been merged, please rebase.

2018-09-05 23:34 UTC, WalterBright commented
rebased

2018-09-06 00:28 UTC, Geod24 requested changes
Personally I don't find this to be much of an enhancement. Instead of passing `CPU` to `setTargetCPU` we are passing the whole `Param` struct, which contains just about everything passed on the command line.

So as an external person reads the code, it is not clear what this function does at call site. It **could** do about anything: change any value in `Param`, or read any value in `Param`.

On the other hand, when looking at the call site, the current code clearly shows that only `params.cpu` is read, and `params.cpu` is written, and the `setTargetCPU` does not have to know about `Params`.

2018-09-06 07:57 UTC, WalterBright commented
> does not have to know about Params

This is incorrect, .cpu, .is64bit and .isOSX fields are read:
```
if (params.is64bit || params.isOSX)
```
Another problem with the original is its use of TARGET.OSX instead of params.isOSX, which is a bit schizophrenic because of the params.is64bit.

A close read of the original shows it takes four parameters:

1. cpu
2. params.is64bit
3. TARGET.OSX
4. cpuid

There is no indication of the latter three in the parameter list for the function. A case could be made for passing cpuid in as an argument, too.

Ideally, params should be passed in as `const ref`, but there's a problem with the design that there should be a globals.cpu to set instead of params.cpu, but that's a refactoring for another day.

It took me several reads of the original tangled logic to figure it all out. I like the new layout much better.

2018-09-06 08:03 UTC, Geod24 commented on src/dmd/mars.d
> -    if (global.params.is64bit)
Right, I missed this

2018-09-06 08:03 UTC, Geod24 approved these changes

2018-09-06 08:04 UTC, Geod24 commented
Thanks for the breakdown, it does make sense

2018-09-06 08:34 UTC, jacob-carlborg commented
Isn't better to have the function return the value instead of setting it inside the function?

2018-09-06 14:52 UTC, merged