Mars: Refactor some code in its own function, remove dead switch
dlang/dmd pull request #8691
Opened 2018-09-13 12:57 UTC by Geod24

Better reviewed commit-by commit and with whitespace changes off.

2018-09-13 13:05 UTC, jacob-carlborg approved these changes

2018-09-13 13:57 UTC, PetarKirov approved these changes

2018-09-13 21:28 UTC, WalterBright commented
Please follow this: "My PR is as minimal as possible (smaller, focused PRs are easier to review than big ones)".
This is one large PR that seems to be about 4 independent issues.

> Better reviewed commit-by commit

Please split into 4 PRs, for exactly that reason.

2018-09-13 21:29 UTC, WalterBright requested changes
Split into 4 PRs.

2018-09-14 02:49 UTC, Geod24 commented
@WalterBright : So be it, I stripped that PR down to 1 commit.

2018-09-14 04:39 UTC, merged