dmd.dmodule: Remove C++ linkage from static members
dlang/dmd pull request #8767
Opened 2018-09-29 19:43 UTC by ibuclaw

And make them free functions.

(Module is peculiar as the driver interacts with it, so is left alone for now...)

2018-09-29 19:56 UTC, WalterBright requested changes
Please fix the title, as the current title has nothing to do with the actual changes.

Please rename `resolve` to something that is both a little more illuminating as to its purpose, and something that is greppable. There are too many diverse functions already named `resolve`.

2018-09-29 21:55 UTC, ibuclaw commented
Fixed up as per discussion https://github.com/dlang/dmd/pull/8770#issuecomment-425675677

2018-09-30 09:49 UTC, jacob-carlborg approved these changes

2018-09-30 11:10 UTC, ibuclaw commented
Cherry-picked into #8773.

2018-09-30 11:10 UTC, closed without merging