bring const to RootObject.equals()
dlang/dmd pull request #9570
Opened 2019-04-06 05:04 UTC by WalterBright

2019-04-06 06:34 UTC, thewilsonator commented
Semaphore:
```
dmd/identifier.d:85:19: error: function dmd.identifier.Identifier.equals does not override any function, did you mean to override 'extern (C++) dmd.root.rootobject.RootObject.equals'?
     override bool equals(const RootObject o) const
                   ^
```

2019-04-06 07:33 UTC, WalterBright commented
It's a strange error. It should compile everywhere else, and does.

2019-04-06 08:01 UTC, jacob-carlborg requested changes

2019-04-06 08:01 UTC, jacob-carlborg commented on src/dmd/func.d
> +	    auto faf1 = fa1 ? fa1.toAliasFunc() : fd1;
Indentation is off.

2019-04-06 08:01 UTC, jacob-carlborg commented on src/dmd/func.d
> +	    bool b2 = fa2 !is null;
Indentation if off.

2019-04-06 08:02 UTC, WalterBright commented
I've failed again at making `equals()` const. But these changes move things along a bit.

The stumbling block is `denum.EnumDeclaration.getMemtype()` resolving a forward reference to an enum.

2019-04-06 08:05 UTC, WalterBright commented
`overloadApply()` is another problem, because it prints error messages, which modify the dsymbol by setting `errors`.

2019-04-06 08:18 UTC, jacob-carlborg submitted a review, later dismissed

2019-04-07 13:22 UTC, wilzbach approved these changes

2019-04-07 13:23 UTC, merged