Fix Issue 19833 - The member as template cannot be acquired by getMember
dlang/dmd pull request #9723
Opened 2019-04-28 19:13 UTC by kubo39

2019-04-28 19:18 UTC, ghost requested changes

2019-04-28 19:18 UTC, Basile-z commented on test/compilable/test19833.d
> +enum x = TT!2.xxx;
Can you `static` `assert` that `x == 2`, please ?

2019-04-28 19:24 UTC, ghost approved these changes
Thanks, LGTM.

2019-04-29 09:35 UTC, thewilsonator approved these changes

2019-04-29 10:42 UTC, merged