update Loc.filename to use a dstring instead of a cstring
dlang/dmd pull request #9745
Opened 2019-05-03 18:50 UTC by benjones

It looks like Loc.opEquals can be removed as it's now just the compiler default.  Am I missing something, or should I just delete it?

2019-05-03 20:14 UTC, jacob-carlborg approved these changes

2019-05-04 09:22 UTC, thewilsonator approved these changes

2019-05-04 09:39 UTC, WalterBright requested changes
No because this will increase the size of `Loc` which is used everywhere and will use a lot more memory.

2019-05-04 09:52 UTC, thewilsonator commented
Ah, good catch.

from https://github.com/thewilsonator/Dlang-AGM/blob/master/2019/Internal.md

> Loc -> location_t (index into source/file managers memory) to save memory

hopefully we can get this done next week.

2019-05-04 10:13 UTC, WalterBright commented
`Loc` can and should be compressed to 8 bytes. 2 bytes for an index into a file table, 3 bytes for line, 3 bytes for column. Or something like that. Properly encapsulated so the scheme can be modified without needing to update anything else.

2019-05-04 10:18 UTC, WalterBright commented on src/dmd/errors.d
> +        !loc.filename.ptr.strstr(".d-mixin-") &&
All these `.ptr` uses assume the string is 0 terminated, which is a fairly dangerous assumption. The use of `strstr` is also wrong. See https://www.tutorialspoint.com/c_standard_library/c_function_strstr.htm

2019-05-04 10:19 UTC, WalterBright commented on src/dmd/errors.d
> +        !loc.filename.ptr.strstr(".d-mixin-") &&
The reason I dislike C string handling so much is because every time I review a use of the C string functions, I find a bug in it.

2019-05-04 11:02 UTC, thewilsonator commented
> Loc can and should be compressed to 8 bytes. 2 bytes for an index into a file table, 3 bytes for line, 3 bytes for column. Or something like that. Properly encapsulated so the scheme can be modified without needing to update anything else.

Awsome, lets make this happen at dconf.

2019-05-04 12:01 UTC, jacob-carlborg commented
> Loc can and should be compressed to 8 bytes. 2 bytes for an index into a file table, 3 bytes for line, 3 bytes for column. Or something like that. Properly encapsulated so the scheme can be modified without needing to update anything else.

Clang only uses four bytes. I’m guessing it’s only an index into a table. I assume speed is less important when reporting diagnostics.

2019-05-04 14:46 UTC, benjones commented
Good points, I'll close this.

2019-05-04 14:46 UTC, closed without merging

2019-05-04 20:33 UTC, WalterBright commented
You can compress it further if you reduce the number of lines/files/columns that can be handled. For example, column number can be reduced to 7 bits, and just "peg" at 128. The line/column can actually be merged, as it seems doubtful that a location will simultaneously need both 65000 lines and 65000 columns. 4 bytes gives 4 billion unique values, which ought to be enough for anyone.

2019-05-05 18:26 UTC, benjones commented
Or maybe only store the byte position in the file and compute the line number and column number as needed when reporting errors?

2019-05-05 18:35 UTC, jacob-carlborg commented
Having the byte position would be nice as well. It allows to do source code transformations.

2019-05-05 18:40 UTC, benjones commented
I won't be at DConf, but keep me posted if there's work to do on this transformation.

2019-05-05 19:29 UTC, thewilsonator commented
Will do. I think what will get done at the conference (unless someone gets very motivate at the hackathon) is deciding what should happen which will be reported on at some point soon after.