[refactor] dmd.mtype: Add Type.ischaracter property, use it.
dlang/dmd pull request #9777
Opened 2019-05-12 13:47 UTC by ibuclaw

Pet peeve that comes up every so often, not being able to distinguish between integral and character types other than using `t.isintegral() && t.ty != Tchar && t.ty != Twchar && t.ty != Tdchar`.

2019-05-12 13:53 UTC, jacob-carlborg commented on src/dmd/mtype.d
> +    bool ischaracter()
Please use camel case to follow the standard D style guide.

2019-05-12 13:57 UTC, jacob-carlborg reviewed
Looks good otherwise.

2019-05-15 14:36 UTC, WalterBright commented on src/dmd/mtype.d
> +    override bool ischaracter()
This creates a virtual function, but the virtual-ity is never used in anywhere. I also suspect the 3 tests are far more efficient than virtual dispatch.

2019-05-15 14:36 UTC, WalterBright requested changes
Make a non-virtual function that does it with 3 tests instead.

2019-05-15 15:33 UTC, ibuclaw commented
I didn't look too hard as other possible uses, such as single use variables that are initialized with `t.nextOf()` and used in the given `ischaracter()` test.

2019-06-30 09:31 UTC, jpf91 commented
ping @ibuclaw

2019-11-12 12:29 UTC, RazvanN7 commented
ping @ibuclaw

2020-03-29 22:37 UTC, closed without merging