Fix Issue 15110 - pragma(inline) rarely works how I want it to
dlang/dmd pull request #9978
Opened 2019-06-05 12:40 UTC by JinShil

2019-06-05 12:41 UTC, thewilsonator commented
A little more description would be useful...

Also cc @TurkeyMan

2019-06-05 13:08 UTC, JinShil commented
Requires https://github.com/dlang/phobos/pull/7059

2019-06-05 14:20 UTC, thewilsonator commented
see also https://github.com/dlang/dmd/pull/7690 (Still haven't been able to figure out why that one fails on Ocean yet).

2019-06-05 22:48 UTC, WalterBright requested changes
The reason this is not done is because always doing an inline scan slows down the compiler.

2019-06-05 22:51 UTC, WalterBright commented
Doing this in away that doesn't always require an inline scan is a much more difficult fix than this is.

2019-06-05 23:07 UTC, JinShil commented
> The reason this is not done is because always doing an inline scan slows down the compiler.

This claim does make sense, but I'm not seeing any significant difference.  There are other things in a build that contribute much more to the time than this.

Here's my data compiling Phobos:

With this PR:
```
time make -f posix.mak

# Take 1
real	0m33.876s
user	0m31.966s
sys	0m1.602s

# Take 2
real	0m40.413s
user	0m38.207s
sys	0m1.830s
```

Without this PR:
```
time make -f posix.mak

# Take 1
real	0m47.470s
user	0m44.997s
sys	0m2.032s

# Take 2
real	0m33.681s
user	0m31.786s
sys	0m1.587s
```

Also most of the inline scanning is gated here https://github.com/dlang/dmd/blob/e9ef759494405e26749a11b3554f4d1cee719c1a/src/dmd/inline.d#L1691-L1694 which probably explains the insignificant change in compile times.

> Doing this in away that doesn't always require an inline scan is a much more difficult fix than this is.

Then I suggest merging this and adding a bug report to implement the more difficult fix as an improvement.

2019-06-05 23:35 UTC, WalterBright commented
1. The way you're doing timings is not accurate enough.

2. "insignificant" costs have a way of adding up. DMD has been steadily slowing down with all these insignificant costs. Not only does it have to do the scanning, it has to do semantic analysis of every function called - a task it currently skips.

> Then I suggest merging this and adding a bug report to implement the more difficult fix as an improvement.

No, because the bug is not that significant in that its effect is minor, but this PR negatively affects everyone. There are too many higher priority things I need to work on.

2019-06-05 23:35 UTC, closed without merging

2019-06-05 23:43 UTC, JinShil commented
Here are timings for just the compiling stage of the phobos build:

With this PR:
```

2019-06-05 23:45 UTC, JinShil commented
> No, because the bug is not that significant in that its effect is minor, but this PR negatively affects everyone.

It doesn't look like it negatively affects anyone, and would positively affect a few people including myself.

2019-06-05 23:52 UTC, WalterBright commented
A 1% slowdown is significant.

2019-06-06 00:09 UTC, JinShil commented
Would you be willing toadvise me with any specifics to improve this PR to your satisfaction?

2019-06-06 08:01 UTC, WalterBright commented
I don't really know of a good way to do it that isn't slow, or I'd have done it already.